(() => {
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)], hidden=e=>!e||e.classList.contains('hidden');
  const focusBack=new WeakMap(), overlays=[['#modalBackdrop','#cancelModal'],['#batchAlbumBackdrop','#cancelBatchAlbum'],['#renameBackdrop','#cancelRename'],['#mergeBackdrop','#cancelMerge'],['#compareView','#closeCompare']];
  let trigger=null,curveIndex=0,longTimer=0,longCard=null,gesture=null,dragRow=null;
  const eye=on=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="none" stroke="currentColor" stroke-width="1.8" d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="3" fill="${on?'currentColor':'none'}" stroke="currentColor" stroke-width="1.6"/></svg>`;
  const blendOptions=v=>['normal','multiply','screen','overlay','softlight'].map(x=>`<option value="${x}" ${x===v?'selected':''}>${x==='softlight'?'Soft Light':x[0].toUpperCase()+x.slice(1)}</option>`).join('');

  function syncAria(){
    ['#editor','#compareView','#modalBackdrop','#batchAlbumBackdrop','#renameBackdrop','#mergeBackdrop'].forEach(s=>{const n=$(s);if(n)n.setAttribute('aria-hidden',String(hidden(n)));});
    $$('[data-route]').forEach(b=>b.classList.contains('active')?b.setAttribute('aria-current','page'):b.removeAttribute('aria-current'));
    $$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.classList.contains('active'))));
    $$('#ratingButtons button').forEach(b=>b.setAttribute('aria-pressed',String(b.classList.contains('on'))));
    const p=(s,v)=>$(s)?.setAttribute('aria-pressed',String(!!v));p('#filterToggle',!hidden($('#filterBar')));p('#selectPhotosBtn',!hidden($('#batchBar')));p('#favoriteBtn',$('#favoriteBtn')?.textContent.trim()==='♥');p('#pickBtn',$('#pickBtn')?.classList.contains('on'));p('#rejectBtn',$('#rejectBtn')?.classList.contains('rejected'));p('#beforeAfterBtn',$('#beforeAfterBtn')?.classList.contains('active'));p('#beforeSplitBtn',$('#beforeSplitBtn')?.classList.contains('active'));p('#panelToggle',$('#panelToggle')?.classList.contains('active'));p('#fullscreenBtn',$('#fullscreenBtn')?.classList.contains('active'));p('#mobileFullscreenBtn',$('#fullscreenBtn')?.classList.contains('active'));
    const editor=$('#editor');if(editor&&typeof editorMode!=='undefined')editor.dataset.mode=editorMode;
  }
  const rangeText=i=>i.id==='beforeSplitRange'?`Split at ${i.value}%`:`${i.getAttribute('aria-label')||'Value'}: ${(+i.value>0?'+':'')+i.value}`;
  function enhance(root=document){$$('input[type="range"]',root).forEach(i=>i.setAttribute('aria-valuetext',rangeText(i)));$$('.mask-tool-card > span,.tool-tabs button > span,.mobile-editor-dock button > span',root).forEach(s=>s.setAttribute('aria-hidden','true'));}
  const focusables=o=>$$('button:not([disabled]),[href],input:not([disabled]),select:not([disabled]),textarea:not([disabled]),[tabindex]:not([tabindex="-1"])',o).filter(n=>n.offsetParent!==null&&n.getAttribute('aria-hidden')!=='true');
  function activeOverlay(){for(let i=overlays.length-1;i>=0;i--){const o=$(overlays[i][0]);if(o&&!hidden(o))return[o,overlays[i][1]];}return null;}
  function observeOverlay(o){let was=hidden(o);new MutationObserver(()=>{const now=hidden(o);o.setAttribute('aria-hidden',String(now));if(!now&&was){const f=trigger&&document.contains(trigger)?trigger:document.activeElement;if(f&&!o.contains(f))focusBack.set(o,f);requestAnimationFrame(()=>focusables(o)[0]?.focus());}else if(now&&!was){const f=focusBack.get(o);focusBack.delete(o);requestAnimationFrame(()=>f&&document.contains(f)&&f.focus());}was=now;}).observe(o,{attributes:true,attributeFilter:['class']});}

  function curveName(c,pts){if(!c||!pts?.length)return;curveIndex=Math.max(0,Math.min(pts.length-1,curveIndex));const p=pts[curveIndex];c.setAttribute('role','application');c.setAttribute('aria-label',`Tone curve. Point ${curveIndex+1} of ${pts.length}, input ${Math.round(p.x*100)}%, output ${Math.round(p.y*100)}%. Left and right select points. Up and down adjust output. Alt plus left or right adjusts input. Enter adds a point. Delete removes an interior point.`);}
  function curveKeys(e){const c=e.target.closest?.('#toneCurveCanvas');if(!c||typeof ensureCurvePoints!=='function'||typeof currentPhoto==='undefined'||!currentPhoto)return;const ks=['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter','Delete','Backspace','Home','End'];if(!ks.includes(e.key))return;const pts=ensureCurvePoints();curveIndex=Math.max(0,Math.min(pts.length-1,curveIndex));if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&!e.altKey){e.preventDefault();curveIndex=Math.max(0,Math.min(pts.length-1,curveIndex+(e.key==='ArrowRight'?1:-1)));curveName(c,pts);return;}if(e.key==='Home'||e.key==='End'){e.preventDefault();curveIndex=e.key==='Home'?0:pts.length-1;curveName(c,pts);return;}const p=pts[curveIndex],next=pts.map(x=>({...x})),step=e.shiftKey?.05:.01;let changed=false;if(e.key==='ArrowUp'||e.key==='ArrowDown'){e.preventDefault();next[curveIndex].y=Math.max(0,Math.min(1,p.y+(e.key==='ArrowUp'?step:-step)));changed=true;}else if((e.key==='ArrowLeft'||e.key==='ArrowRight')&&e.altKey&&curveIndex>0&&curveIndex<pts.length-1){e.preventDefault();next[curveIndex].x=Math.max(next[curveIndex-1].x+.005,Math.min(next[curveIndex+1].x-.005,p.x+(e.key==='ArrowRight'?step:-step)));changed=true;}else if(e.key==='Enter'&&curveIndex<pts.length-1){e.preventDefault();const n=pts[curveIndex+1];next.splice(curveIndex+1,0,{x:(p.x+n.x)/2,y:(p.y+n.y)/2});curveIndex++;changed=true;}else if((e.key==='Delete'||e.key==='Backspace')&&curveIndex>0&&curveIndex<pts.length-1){e.preventDefault();next.splice(curveIndex,1);curveIndex=Math.min(curveIndex,next.length-1);changed=true;}if(!changed)return;captureHistory();currentPhoto.edits.curvePoints=next;syncCurveSlidersFromPoints(next);captureHistory();drawToneCurve();renderCanvas($('#editorCanvas'));debouncedSave();curveName(c,next);}

  if(typeof captureHistory==='function'){const base=captureHistory;captureHistory=function(...a){const r=base.apply(this,a);try{if(history.length>60){const d=history.length-60;history.splice(0,d);historyIndex=Math.max(-1,historyIndex-d);}}catch{}return r;};}
  if(typeof renderCanvas==='function'){const base=renderCanvas;let pending=null,busy=false,raf=0;const flush=async()=>{raf=0;if(busy||!pending)return;const j=pending;pending=null;busy=true;try{await base(j.c,j.m,false);}finally{busy=false;if(pending&&!raf)raf=requestAnimationFrame(flush);}};renderCanvas=function(c,m=1400,original=false){if(c?.id!=='editorCanvas'||original)return base(c,m,original);const preview=typeof EDITOR_PREVIEW_MAX_SIZE==='number'?EDITOR_PREVIEW_MAX_SIZE:960;pending={c,m:Math.min(m||preview,preview)};if(!raf)raf=requestAnimationFrame(flush);return Promise.resolve();};}

  function stackOrder(item,fallback){return Number.isFinite(+item.stackOrder)?+item.stackOrder:fallback;}
  function selected(kind,id){return kind==='mask'?id===activeLocalId:kind==='adjustment'?id===activeLayerId:id===activeImageLayerId;}
  function thumbFor(kind,item){if(kind==='image'){const p=photos.find(x=>x.id===item.sourcePhotoId);return p?`<img src="${blobUrl(p,true)}" alt="">`:'<span aria-hidden="true">▭</span>';}return currentPhoto?`<img src="${blobUrl(currentPhoto,true)}" alt="">`:'<span aria-hidden="true">▭</span>';}
  function maskThumb(kind,item){return kind==='mask'?`<canvas width="72" height="48" data-stack-mask-thumb="${item.id}" aria-label="Mask thumbnail"></canvas>`:'<span class="stack-mask-full" aria-hidden="true"></span>';}
  function selectAttr(kind,id){return kind==='mask'?`data-local-select="${id}"`:kind==='adjustment'?`data-layer-select="${id}"`:`data-image-layer-select="${id}"`;}
  function toggleAttr(kind,id){return kind==='mask'?`data-local-toggle="${id}"`:kind==='adjustment'?`data-layer-toggle="${id}"`:`data-image-layer-toggle="${id}"`;}
  function stackRow(kind,item,order){const name=kind==='mask'?maskLabel(item):item.name||(kind==='adjustment'?'Adjustment':'Image Layer'),active=selected(kind,item.id),opacity=Math.round((item.opacity??1)*100),mods=kind==='mask'?(item.modifiers||[]):[];return `<div class="stack-entry" data-stack-entry="${item.id}" data-stack-kind="${kind}" data-stack-order="${order}" draggable="true"><div class="unified-layer-row ${active?'active':''}" role="option" aria-selected="${active}" tabindex="${active?'0':'-1'}" data-stack-kind="${kind}" data-stack-id="${item.id}"><button class="stack-grab" type="button" aria-label="Drag to reorder" title="Drag to reorder">⠿</button><button class="stack-content-thumb" ${selectAttr(kind,item.id)} aria-label="Select ${esc(name)}">${thumbFor(kind,item)}</button><button class="stack-mask-thumb" ${selectAttr(kind,item.id)} aria-label="Select ${esc(name)} mask">${maskThumb(kind,item)}</button><div class="stack-main"><button class="stack-name" ${selectAttr(kind,item.id)} data-stack-name="${kind}|${item.id}"><b>${esc(name)}</b><small>${kind==='mask'?`${mods.length+1} component${mods.length?'s':''}`:kind==='adjustment'?'Adjustment layer':'Image layer'}</small></button>${kind==='mask'?'':`<div class="stack-inline"><label><span class="visually-hidden">Blend mode</span><select data-stack-blend="${kind}|${item.id}" aria-label="${esc(name)} blend mode">${blendOptions(item.blend||'normal')}</select></label><label class="stack-opacity"><span>${opacity}%</span><input type="range" min="0" max="100" value="${opacity}" data-stack-opacity="${kind}|${item.id}" aria-label="${esc(name)} opacity"></label></div>`}</div><button class="stack-eye" ${toggleAttr(kind,item.id)} aria-label="${item.enabled===false?'Show':'Hide'} ${esc(name)}">${eye(item.enabled!==false)}</button><button class="stack-more" type="button" data-stack-more="${kind}|${item.id}" aria-label="More options for ${esc(name)}">⋮</button></div>${mods.length?`<div class="stack-modifiers">${mods.map(m=>`<div class="stack-modifier"><span class="stack-tree-mark" aria-hidden="true">${m.operation==='subtract'?'−':m.operation==='intersect'?'∩':'＋'}</span><span>${esc(maskLabel(m))}</span><small>${esc(m.operation||'add')}</small></div>`).join('')}</div>`:''}</div>`;}
  if(typeof renderLayersPanel==='function')renderLayersPanel=function(){
    const masks=currentPhoto.localEdits||[],adjustments=currentPhoto.adjustmentLayers||[],images=currentPhoto.imageLayers||[];if(adjustments[0]&&!activeLayerId)activeLayerId=adjustments[0].id;if(images[0]&&!activeImageLayerId)activeImageLayerId=images[0].id;
    const rows=[...masks.map((x,i)=>({kind:'mask',item:x,order:stackOrder(x,i)})),...adjustments.map((x,i)=>({kind:'adjustment',item:x,order:stackOrder(x,1000+i)})),...images.map((x,i)=>({kind:'image',item:x,order:stackOrder(x,2000+i)}))].sort((a,b)=>a.order-b.order);
    const refs=photos.filter(p=>p.id!==currentPhoto.id),add=`<div class="unified-layer-add"><button id="newAdjustmentLayer" class="primary-action">＋ Adjustment</button><select id="imageLayerSource" aria-label="Image layer source"><option value="">Choose local photo</option>${refs.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('')}</select><button id="addImageLayer">＋ Image</button><button class="secondary" data-panel-jump="masks">＋ Mask</button></div>`;
    const detail=activeLayerId&&adjustments.some(x=>x.id===activeLayerId)?`<div class="unified-layer-detail"><b>Selected adjustment</b>${sliderMarkup([...panelDefs.light,...panelDefs.color],adjustments.find(x=>x.id===activeLayerId).edits,'layer-edit')}<div class="layer-actions"><button id="duplicateLayer">Duplicate</button><button id="deleteLayer" class="danger-mini">Delete</button></div></div>`:'';
    return accordionSection('layers','Layers',`${add}${rows.length?`<div class="unified-layer-stack" role="listbox" aria-label="Layers and masks">${rows.map(r=>stackRow(r.kind,r.item,r.order)).join('')}</div>`:'<div class="mask-empty">Add a mask, adjustment, or image layer.</div>'}${detail}`,'pro',`${rows.length} item${rows.length===1?'':'s'}`);
  };
  function stackItem(kind,id){return kind==='mask'?currentPhoto.localEdits.find(x=>x.id===id):kind==='adjustment'?currentPhoto.adjustmentLayers.find(x=>x.id===id):currentPhoto.imageLayers.find(x=>x.id===id);}
  function redrawMaskThumbs(){$$('[data-stack-mask-thumb]').forEach(c=>{const m=currentPhoto?.localEdits?.find(x=>x.id===c.dataset.stackMaskThumb);if(!m)return;const x=c.getContext('2d');x.fillStyle='#050505';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#fff';x.fillStyle='rgba(255,255,255,.82)';x.lineWidth=3;if(m.type==='linear'){const gx=x.createLinearGradient(0,0,c.width,c.height);gx.addColorStop(0,'#000');gx.addColorStop(1,'#fff');x.fillStyle=gx;x.fillRect(0,0,c.width,c.height);}else if(m.type==='radial'){x.beginPath();x.ellipse((m.cx??.5)*c.width,(m.cy??.5)*c.height,(m.rx??.28)*c.width,(m.ry??.22)*c.height,0,0,Math.PI*2);x.fill();}else if(['subject','person','object','sky','background'].includes(m.type)){x.beginPath();x.ellipse(c.width*.5,c.height*.52,c.width*.27,c.height*.37,0,0,Math.PI*2);x.fill();}else{for(const s of m.strokes||[]){x.beginPath();for(let i=0;i<(s.points||[]).length;i++){const p=s.points[i],px=(p.x??0)*c.width,py=(p.y??0)*c.height;i?x.lineTo(px,py):x.moveTo(px,py);}x.stroke();}if(!(m.strokes||[]).length){x.beginPath();x.arc(c.width*.5,c.height*.5,Math.min(c.width,c.height)*.24,0,Math.PI*2);x.fill();}}});}
  function rerenderStack(){renderControls();requestAnimationFrame(redrawMaskThumbs);}
  function reorderSameKind(kind,fromId,toId){const arr=kind==='mask'?currentPhoto.localEdits:kind==='adjustment'?currentPhoto.adjustmentLayers:currentPhoto.imageLayers,from=arr.findIndex(x=>x.id===fromId),to=arr.findIndex(x=>x.id===toId);if(from<0||to<0||from===to)return;captureHistory();const [x]=arr.splice(from,1);arr.splice(to,0,x);arr.forEach((v,i)=>v.stackOrder=(kind==='mask'?0:kind==='adjustment'?1000:2000)+i);captureHistory();rerenderStack();renderCanvas($('#editorCanvas'));debouncedSave();}

  const blobData=b=>new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(b)}),dataBlob=async d=>(await fetch(d)).blob();
  async function backup(){const b=$('#backupProject');if(b)b.disabled=true;try{const ps=await getAll('photos'),as=await getAll('albums'),out=[];for(let i=0;i<ps.length;i++){const p={...ps[i]};for(const k of ['blob','originalBlob','thumbnailBlob','aiSourceBlob'])if(p[k] instanceof Blob)p[k]={__blob:true,data:await blobData(p[k])};out.push(p);if(b)b.textContent=`Backing up ${i+1}/${ps.length}…`;}const file=new Blob([JSON.stringify({format:'darkroom-project-bundle',version:1,created:new Date().toISOString(),photos:out,albums:as})],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(file);a.download=`DarkRoom-backup-${new Date().toISOString().slice(0,10)}.darkroom.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Project backup created');}catch(e){console.error(e);toast('Could not create project backup');}finally{if(b){b.disabled=false;b.textContent='Back up project';}}}
  async function restore(file){try{const p=JSON.parse(await file.text());if(p?.format!=='darkroom-project-bundle'||!Array.isArray(p.photos)||!Array.isArray(p.albums))throw Error('Invalid bundle');if(!confirm(`Restore ${p.photos.length} photos and ${p.albums.length} albums?`))return;for(const photo of p.photos){for(const k of ['blob','originalBlob','thumbnailBlob','aiSourceBlob'])if(photo[k]?.__blob)photo[k]=await dataBlob(photo[k].data);await put('photos',photo);}for(const a of p.albums)await put('albums',a);await refreshData();toast('Project restored');}catch(e){console.error(e);toast('Could not restore this DarkRoom backup');}}
  function backupUI(){const s=$('#storageView .storage-detail');if(!s||$('#backupProject'))return;const d=document.createElement('div');d.className='project-backup-tools';d.innerHTML='<h4>Project backup</h4><p>Export the complete local library, originals, masks, layers, and edit state.</p><div class="project-backup-actions"><button id="backupProject" class="secondary">Back up project</button><label class="secondary project-restore">Restore project<input id="restoreProjectInput" type="file" accept=".json,.darkroom.json,application/json" hidden></label></div>';s.insertBefore(d,s.querySelector('.danger')||null);$('#backupProject').onclick=backup;$('#restoreProjectInput').onchange=e=>{const f=e.target.files?.[0];if(f)restore(f);e.target.value='';};}
  function exportWarning(){const c=$('#controls');if(!c||!currentPhoto)return;const s=c.querySelector('[data-section="export"],.export-options,.export-panel');if(s&&!s.querySelector('.metadata-warning')){const p=document.createElement('p');p.className='feature-note metadata-warning';p.setAttribute('role','note');p.innerHTML='<b>Metadata notice:</b> rendered exports may not retain all EXIF/IPTC/XMP fields. Keep the original for authoritative metadata.';s.prepend(p);}}
  if(typeof toast==='function'){const base=toast;toast=function(msg){if(/^Could not import/i.test(String(msg))){navigator.storage?.estimate?.().then(e=>base(e.quota&&e.usage/e.quota>.92?'Storage is nearly full. Free browser storage or back up and remove photos, then try again.':msg)).catch(()=>base(msg));return;}return base(msg);};}

  document.addEventListener('click',e=>{const t=e.target.closest('button,a,input,select,summary,label');if(t)trigger=t;const jump=e.target.closest('[data-panel-jump]');if(jump&&typeof currentPanel!=='undefined'){currentPanel=jump.dataset.panelJump;renderControls();}requestAnimationFrame(()=>{syncAria();backupUI();exportWarning();redrawMaskThumbs();});},true);
  document.addEventListener('dblclick',e=>{const b=e.target.closest('[data-stack-name]');if(!b)return;const[kind,id]=b.dataset.stackName.split('|'),item=stackItem(kind,id);if(!item)return;const old=kind==='mask'?maskLabel(item):item.name||'',input=document.createElement('input');input.className='stack-rename-input';input.value=old;b.replaceWith(input);input.focus();input.select();const done=()=>{const v=input.value.trim();if(v&&v!==old){captureHistory();item.name=v;captureHistory();debouncedSave();}rerenderStack();};input.onkeydown=x=>{if(x.key==='Enter')input.blur();if(x.key==='Escape'){input.value=old;input.blur();}};input.onblur=done;});
  document.addEventListener('change',e=>{const s=e.target.closest('[data-stack-blend]');if(!s)return;const[k,id]=s.dataset.stackBlend.split('|'),item=stackItem(k,id);if(!item)return;captureHistory();item.blend=s.value;captureHistory();renderCanvas($('#editorCanvas'));debouncedSave();});
  document.addEventListener('input',e=>{if(e.target.matches('input[type="range"]'))e.target.setAttribute('aria-valuetext',rangeText(e.target));const s=e.target.closest('[data-stack-opacity]');if(!s)return;const[k,id]=s.dataset.stackOpacity.split('|'),item=stackItem(k,id);if(!item)return;item.opacity=+s.value/100;s.previousElementSibling.textContent=`${s.value}%`;renderCanvas($('#editorCanvas'));debouncedSave();});
  document.addEventListener('dragstart',e=>{const x=e.target.closest('[data-stack-entry]');if(x){dragRow={kind:x.dataset.stackKind,id:x.dataset.stackEntry};e.dataTransfer.effectAllowed='move';}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-stack-entry]'))e.preventDefault();});document.addEventListener('drop',e=>{const x=e.target.closest('[data-stack-entry]');if(!x||!dragRow)return;e.preventDefault();if(x.dataset.stackKind===dragRow.kind)reorderSameKind(dragRow.kind,dragRow.id,x.dataset.stackEntry);dragRow=null;});
  document.addEventListener('pointerdown',e=>{const card=e.target.closest?.('.photo-card');if(card&&e.pointerType!=='mouse'){longCard=card;longTimer=setTimeout(()=>{if(longCard){setSelectionMode(true);togglePhotoSelection(longCard.dataset.photo);navigator.vibrate?.(20);longCard=null;}},450);}if(e.target.closest?.('#editorCanvas')&&e.pointerType!=='mouse'&&typeof zoom!=='undefined'&&zoom<=1.05)gesture={x:e.clientX,y:e.clientY,t:performance.now()};},{passive:true});
  document.addEventListener('pointerup',e=>{clearTimeout(longTimer);longTimer=0;longCard=null;if(!gesture)return;const g=gesture;gesture=null,dx=e.clientX-g.x,dy=e.clientY-g.y;if(performance.now()-g.t>700)return;if(Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.3&&currentPhoto){const list=filteredPhotos(),i=list.findIndex(p=>p.id===currentPhoto.id),n=i+(dx<0?1:-1);if(n>=0&&n<list.length)openEditor(list[n].id);}else if(photoOnly&&Math.abs(dy)>70&&Math.abs(dy)>Math.abs(dx)*1.3){dy<0?setFlag('picked'):setFlag('rejected');}},{passive:true});
  document.addEventListener('pointercancel',()=>{clearTimeout(longTimer);longCard=null;gesture=null;},{passive:true});
  document.addEventListener('keydown',e=>{curveKeys(e);const row=e.target.closest?.('[role="option"][data-stack-kind]');if(row){const rows=$$('[role="option"][data-stack-kind]',row.closest('[role="listbox"]')),i=rows.indexOf(row);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();rows[Math.max(0,Math.min(rows.length-1,i+(e.key==='ArrowDown'?1:-1)))]?.focus();}else if(e.key==='Enter'||e.key===' '){e.preventDefault();row.querySelector('[data-local-select],[data-layer-select],[data-image-layer-select]')?.click();}}const a=activeOverlay();if(a){const[o,close]=a;if(e.key==='Escape'){e.preventDefault();e.stopPropagation();($(close,o)||$(close))?.click();return;}if(e.key==='Tab'){const f=focusables(o),first=f[0],last=f.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}},true);
  overlays.forEach(([s])=>{const o=$(s);if(o)observeOverlay(o);});const controls=$('#controls');if(controls)new MutationObserver(()=>{enhance(controls);exportWarning();redrawMaskThumbs();const c=$('#toneCurveCanvas');if(c&&typeof curvePointsForEdit==='function')curveName(c,curvePointsForEdit());}).observe(controls,{childList:true,subtree:true});new MutationObserver(()=>{syncAria();backupUI();}).observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});
  syncAria();enhance();backupUI();requestAnimationFrame(redrawMaskThumbs);
})();