const DarkRoomAI=(()=>{
 let libPromise=null,segmenterPromise=null,backgroundPromise=null,depthPromise=null,upscalerPromise=null,detectorPromise=null,lastError='';
 const LIB='https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1/+esm';
 async function lib(){if(!libPromise)libPromise=import(LIB).catch(e=>{lastError=e.message;throw e});return libPromise}
 async function makePipeline(task,model,{quantized=true}={}){const {pipeline,env}=await lib();try{env.allowLocalModels=false;env.useBrowserCache=true}catch{}const gpu=!!navigator.gpu,options={device:gpu?'webgpu':'wasm'};if(quantized)options.dtype=gpu?'q4':'q8';try{return await pipeline(task,model,options)}catch(e){if(gpu){lastError='WebGPU fallback: '+e.message;return pipeline(task,model,quantized?{device:'wasm',dtype:'q8'}:{device:'wasm'})}throw e}}
 async function segmenter(){if(!segmenterPromise)segmenterPromise=makePipeline('image-segmentation','Xenova/segformer-b0-finetuned-ade-512-512').catch(e=>{segmenterPromise=null;lastError=e.message;throw e});return segmenterPromise}
 async function backgroundRemover(){if(!backgroundPromise)backgroundPromise=makePipeline('background-removal','Xenova/modnet',{quantized:false}).catch(e=>{backgroundPromise=null;lastError=e.message;throw e});return backgroundPromise}
 async function depthEstimator(){if(!depthPromise)depthPromise=makePipeline('depth-estimation','onnx-community/depth-anything-v2-small').catch(e=>{depthPromise=null;lastError=e.message;throw e});return depthPromise}
 async function upscaler(){if(!upscalerPromise)upscalerPromise=makePipeline('image-to-image','Xenova/swin2SR-lightweight-x2-64').catch(e=>{upscalerPromise=null;lastError=e.message;throw e});return upscalerPromise}
 async function detector(){if(!detectorPromise)detectorPromise=makePipeline('zero-shot-object-detection','Xenova/owlvit-base-patch32').catch(e=>{detectorPromise=null;lastError=e.message;throw e});return detectorPromise}
 function rawMask(mask){if(!mask)return null;const w=mask.width||mask.size?.[0]||mask.dims?.at?.(-1),h=mask.height||mask.size?.[1]||mask.dims?.at?.(-2),data=mask.data;if(!w||!h||!data)return null;const out=new Array(w*h);if(data.length===w*h){for(let i=0;i<out.length;i++)out[i]=Math.round((data[i]>1?data[i]/255:data[i])*255)}else{for(let i=0;i<out.length;i++){const a=data[i*4+3],r=data[i*4];out[i]=a!==undefined?a:r||0}}return{w,h,data:out}}
 const includes=(label,terms)=>terms.some(t=>label.includes(t));
 function labelsFor(type){const map={sky:['sky'],person:['person','human'],face:['face','head'],skin:['skin','face'],hair:['hair'],clothes:['shirt','clothes','clothing','coat','dress','pants','skirt'],clothing:['shirt','clothes','clothing','coat','dress','pants','skirt'],teeth:['teeth','mouth'],eyes:['eye'],lips:['mouth','lip'],water:['water','sea','river','lake','pool'],vegetation:['tree','grass','plant','flower','vegetation'],architecture:['building','house','wall','door','window','skyscraper','bridge'],mountains:['mountain','hill','rock'],snow:['snow'],ground:['earth','ground','dirt','field','sand'],artificialGround:['road','sidewalk','floor','pavement']};return map[type]||[]}
 function combine(results,type){const parsed=results.map(r=>({label:String(r.label||'').toLowerCase(),score:r.score??1,mask:rawMask(r.mask)})).filter(x=>x.mask);if(!parsed.length)return null;const w=parsed[0].mask.w,h=parsed[0].mask.h,out=new Array(w*h).fill(0);let chosen=parsed;if(type==='subject'||type==='object'){chosen=parsed.filter(x=>!includes(x.label,['sky','wall','floor','road','grass','water','background','ceiling']));if(!chosen.length)chosen=parsed.slice().sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,1);if(type==='object')chosen=chosen.slice().sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,1)}else if(type==='background'){const subject=combine(results,'subject');if(!subject)return null;return{w:subject.w,h:subject.h,data:subject.data.map(v=>255-v)}}else{const terms=labelsFor(type);chosen=parsed.filter(x=>includes(x.label,terms));if(!chosen.length)return null}for(const x of chosen)for(let i=0;i<out.length;i++)out[i]=Math.max(out[i],x.mask.data[i]||0);return{w,h,data:out}}
 async function matte(blob,invert=false){const p=await backgroundRemover(),url=URL.createObjectURL(blob);try{const result=await p(url),raw=Array.isArray(result)?result[0]:result,r=rawMask(raw);if(!r)return null;if(invert)r.data=r.data.map(v=>255-v);return r}finally{URL.revokeObjectURL(url)}}
 async function segment(blob,type){if(type==='subject'){try{const r=await matte(blob,false);if(r)return r}catch(e){lastError=e.message}}if(type==='background'){try{const r=await matte(blob,true);if(r)return r}catch(e){lastError=e.message}}const p=await segmenter(),url=URL.createObjectURL(blob);try{const result=await p(url,{threshold:.35,mask_threshold:.35});return combine(Array.isArray(result)?result:[],type)}finally{URL.revokeObjectURL(url)}}
 async function objectBox(blob,prompt){const p=await detector(),url=URL.createObjectURL(blob);try{const results=await p(url,[prompt],{threshold:.08});if(!results?.length)return null;const best=results.slice().sort((a,b)=>(b.score||0)-(a.score||0))[0];return{label:best.label,score:best.score,box:best.box}}finally{URL.revokeObjectURL(url)}}
 function normalizeDepth(raw){if(!raw)return null;const w=raw.width||raw.size?.[0],h=raw.height||raw.size?.[1],data=raw.data;if(!w||!h||!data)return null;let mn=Infinity,mx=-Infinity;for(const v of data){mn=Math.min(mn,v);mx=Math.max(mx,v)}const range=Math.max(1e-6,mx-mn),out=new Array(w*h);if(data.length===w*h)for(let i=0;i<out.length;i++)out[i]=Math.round((data[i]-mn)/range*255);else for(let i=0;i<out.length;i++)out[i]=data[i*4]||0;return{w,h,data:out}}
 async function depth(blob){const p=await depthEstimator(),url=URL.createObjectURL(blob);try{const result=await p(url);return normalizeDepth(result?.predicted_depth)||normalizeDepth(result?.depth)}finally{URL.revokeObjectURL(url)}}
 function rawImageToBlob(raw){return new Promise((resolve,reject)=>{try{const w=raw.width,h=raw.height,ch=raw.channels||3,data=raw.data||raw;const rgba=new Uint8ClampedArray(w*h*4);for(let i=0;i<w*h;i++){rgba[i*4]=data[i*ch]||0;rgba[i*4+1]=data[i*ch+1]??rgba[i*4];rgba[i*4+2]=data[i*ch+2]??rgba[i*4];rgba[i*4+3]=255}const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').putImageData(new ImageData(rgba,w,h),0,0);c.toBlob(b=>b?resolve({blob:b,width:w,height:h}):reject(new Error('AI upscale encoding failed')),'image/png')}catch(e){reject(e)}})}
 async function upscale(blob,passes=1){let current=blob,width=0,height=0;passes=Math.max(1,Math.min(2,passes|0));const p=await upscaler();for(let i=0;i<passes;i++){const url=URL.createObjectURL(current);try{const raw=await p(url);const converted=await rawImageToBlob(raw);current=converted.blob;width=converted.width;height=converted.height}finally{URL.revokeObjectURL(url)}}return{blob:current,width,height}}
 function status(){return{webgpu:!!navigator.gpu,wasm:typeof WebAssembly!=='undefined',segmenterLoaded:!!segmenterPromise,backgroundLoaded:!!backgroundPromise,depthLoaded:!!depthPromise,upscalerLoaded:!!upscalerPromise,detectorLoaded:!!detectorPromise,lastError}}
 return{segment,matte,objectBox,depth,upscale,status};
})();
