const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB_NAME='darkroom-db', DB_VERSION=1; let db; let photos=[]; let albums=[]; let currentPhoto=null; let currentPanel='light'; let currentRoute='library'; let gridMode=5;
const defaultEdits=()=>({exposure:0,contrast:0,highlights:0,shadows:0,whites:0,blacks:0,temp:0,tint:0,vibrance:0,saturation:0,texture:0,clarity:0,dehaze:0,vignette:0,grain:0,sharpness:0,noise:0});
const panelDefs={
 light:[['exposure','Exposure',-100,100],['contrast','Contrast',-100,100],['highlights','Highlights',-100,100],['shadows','Shadows',-100,100],['whites','Whites',-100,100],['blacks','Blacks',-100,100]],
 color:[['temp','Temperature',-100,100],['tint','Tint',-100,100],['vibrance','Vibrance',-100,100],['saturation','Saturation',-100,100]],
 effects:[['texture','Texture',-100,100],['clarity','Clarity',-100,100],['dehaze','Dehaze',-100,100],['vignette','Vignette',-100,100],['grain','Grain',0,100]],
 detail:[['sharpness','Sharpening',0,100],['noise','Noise Reduction',0,100]]
};
function reqP(req){return new Promise((res,rej)=>{req.onsuccess=()=>res(req.result);req.onerror=()=>rej(req.error)})}
async function initDB(){db=await new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('photos')) d.createObjectStore('photos',{keyPath:'id'});if(!d.objectStoreNames.contains('albums')) d.createObjectStore('albums',{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});await refreshData();}
async function getAll(store){return reqP(db.transaction(store).objectStore(store).getAll())}
async function put(store,obj){return reqP(db.transaction(store,'readwrite').objectStore(store).put(obj))}
async function del(store,id){return reqP(db.transaction(store,'readwrite').objectStore(store).delete(id))}
async function clearStore(store){return reqP(db.transaction(store,'readwrite').objectStore(store).clear())}
async function refreshData(){photos=await getAll('photos');albums=await getAll('albums');render();updateStorage();}
function uid(){return crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2)}
function fmtBytes(n){if(!n)return '0 MB';if(n<1048576)return (n/1024).toFixed(0)+' KB';if(n<1073741824)return (n/1048576).toFixed(n<10485760?1:0)+' MB';return (n/1073741824).toFixed(2)+' GB'}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),1800)}
function blobUrl(p){if(!p._url)p._url=URL.createObjectURL(p.blob);return p._url}
async function importFiles(files){const imgs=[...files].filter(f=>f.type.startsWith('image/'));if(!imgs.length)return;toast(`Importing ${imgs.length} photo${imgs.length>1?'s':''}…`);for(const f of imgs){let dimensions={width:0,height:0};try{dimensions=await imageDimensions(f)}catch{} const rec={id:uid(),name:f.name,type:f.type,size:f.size,created:Date.now(),modified:f.lastModified||Date.now(),width:dimensions.width,height:dimensions.height,blob:f,edits:defaultEdits(),favorite:false,rating:0,albumIds:[]};await put('photos',rec)}await refreshData();toast(`${imgs.length} photo${imgs.length>1?'s':''} added`)}
function imageDimensions(blob){return new Promise((res,rej)=>{const im=new Image(),u=URL.createObjectURL(blob);im.onload=()=>{res({width:im.naturalWidth,height:im.naturalHeight});URL.revokeObjectURL(u)};im.onerror=rej;im.src=u})}
function filteredPhotos(){let list=[...photos];if(currentRoute==='favorites')list=list.filter(p=>p.favorite);if(currentRoute==='recent')list=list.filter(p=>Date.now()-p.created<7*86400000);const q=$('#searchInput').value.trim().toLowerCase();if(q)list=list.filter(p=>{const albumNames=p.albumIds?.map(id=>albums.find(a=>a.id===id)?.name||'').join(' ')||'';return `${p.name} ${albumNames} ${new Date(p.created).toLocaleDateString()}`.toLowerCase().includes(q)});const s=$('#sortSelect').value;if(s==='old')list.sort((a,b)=>a.created-b.created);else if(s==='name')list.sort((a,b)=>a.name.localeCompare(b.name));else if(s==='rating')list.sort((a,b)=>b.rating-a.rating);else list.sort((a,b)=>b.created-a.created);return list}
function render(){renderPhotos();renderAlbums();$('#allCount').textContent=photos.length;document.querySelectorAll('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===currentRoute));}
function renderPhotos(){const g=$('#photoGrid'), empty=$('#emptyState');let list=filteredPhotos();const titles={library:['All Photos','Your photos, stored on this device.'],recent:['Recently Added','Photos imported in the last 7 days.'],favorites:['Favorites','Photos you have marked as favorites.']};if(titles[currentRoute]){$('#viewTitle').textContent=titles[currentRoute][0];$('#viewSubtitle').textContent=titles[currentRoute][1]};empty.style.display=list.length?'none':'flex';g.style.display=list.length?'grid':'none';g.innerHTML=list.map(p=>`<article class="photo-card" data-photo="${p.id}"><img src="${blobUrl(p)}" alt="${esc(p.name)}" loading="lazy"><div class="photo-overlay"><span class="stars">${p.rating?'★'.repeat(p.rating):''}</span><span class="fav-dot">${p.favorite?'♥':''}</span></div></article>`).join('');$$('.photo-card').forEach(c=>c.onclick=()=>openEditor(c.dataset.photo));if(innerWidth>760)g.style.gridTemplateColumns=`repeat(${gridMode},minmax(0,1fr))`}
function renderAlbums(){const ag=$('#albumGrid');if(!albums.length){ag.innerHTML='<div class="info-card"><b>No albums yet</b><p>Create an album to group photos without duplicating their files.</p></div>';return}ag.innerHTML=albums.map(a=>{const ps=photos.filter(p=>p.albumIds?.includes(a.id)).slice(0,4);return `<article class="album-card" data-album="${a.id}"><div class="album-cover">${ps.length?ps.map(p=>`<img src="${blobUrl(p)}">`).join(''):'<div class="album-empty">▱</div>'}</div><h3>${esc(a.name)}</h3><small>${photos.filter(p=>p.albumIds?.includes(a.id)).length} photos</small></article>`}).join('')}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function updateStorage(){const used=photos.reduce((n,p)=>n+(p.size||0),0);let quota=0,estimateUsed=0;try{const e=await navigator.storage.estimate();quota=e.quota||0;estimateUsed=e.usage||0}catch{} const pct=quota?Math.min(100,estimateUsed/quota*100):0;$('#storageBig').textContent=fmtBytes(used);$('#photoStorage').textContent=fmtBytes(used);$('#quotaStorage').textContent=quota?fmtBytes(Math.max(0,quota-estimateUsed)):'Browser controlled';$('#usageBar').style.width=pct+'%';$('#sideMeter').style.width=pct+'%';$('#sideStorage').textContent=`${fmtBytes(used)} stored locally`;$('#donut').style.background=`conic-gradient(#e1e1e1 ${pct*3.6}deg,#242424 0)`}
function route(r){currentRoute=r;$$('.view').forEach(v=>v.classList.remove('active'));if(r==='albums')$('#albumsView').classList.add('active');else if(r==='storage')$('#storageView').classList.add('active');else $('#libraryView').classList.add('active');render();if(innerWidth<760)document.title=`DarkRoom — ${r[0].toUpperCase()+r.slice(1)}`}
function openEditor(id){currentPhoto=photos.find(p=>p.id===id);if(!currentPhoto)return;currentPhoto.edits={...defaultEdits(),...(currentPhoto.edits||{})};$('#editor').classList.remove('hidden');$('#editor').setAttribute('aria-hidden','false');$('#editorName').textContent=currentPhoto.name;$('#editorMeta').textContent=`${currentPhoto.width||'—'} × ${currentPhoto.height||'—'} · ${fmtBytes(currentPhoto.size)}`;$('#editorImage').src=blobUrl(currentPhoto);$('#favoriteBtn').textContent=currentPhoto.favorite?'♥':'♡';currentPanel='light';renderControls();updatePreview();updateRating();}
function closeEditor(){if(!currentPhoto)return;put('photos',currentPhoto).then(refreshData);$('#editor').classList.add('hidden');$('#editor').setAttribute('aria-hidden','true');currentPhoto=null}
function renderControls(){if(!currentPhoto)return;$$('#toolTabs button').forEach(b=>b.classList.toggle('active',b.dataset.panel===currentPanel));const c=$('#controls');if(currentPanel==='info'){c.innerHTML=`<div class="info-grid"><div class="info-cell"><small>Filename</small>${esc(currentPhoto.name)}</div><div class="info-cell"><small>Dimensions</small>${currentPhoto.width||'—'} × ${currentPhoto.height||'—'}</div><div class="info-cell"><small>File size</small>${fmtBytes(currentPhoto.size)}</div><div class="info-cell"><small>Imported</small>${new Date(currentPhoto.created).toLocaleString()}</div></div>`;return}c.innerHTML=panelDefs[currentPanel].map(([key,label,min,max])=>`<div class="control"><label><span>${label}</span><b id="v-${key}">${currentPhoto.edits[key]>0?'+':''}${currentPhoto.edits[key]}</b></label><input type="range" min="${min}" max="${max}" value="${currentPhoto.edits[key]}" data-edit="${key}"></div>`).join('');$$('[data-edit]').forEach(r=>r.oninput=()=>{currentPhoto.edits[r.dataset.edit]=+r.value;$('#v-'+r.dataset.edit).textContent=(+r.value>0?'+':'')+r.value;updatePreview();debouncedSave()})}
let saveTimer;function debouncedSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>currentPhoto&&put('photos',currentPhoto),350)}
function cssFilters(e){const exposure=100+e.exposure*.65,contrast=100+e.contrast*.75,sat=100+e.saturation*.8+e.vibrance*.35,bright=exposure+e.whites*.12+e.shadows*.06-e.blacks*.05, sepia=Math.max(0,e.temp)*.18;return `brightness(${bright}%) contrast(${contrast}%) saturate(${sat}%) sepia(${sepia}%)`}
function updatePreview(){const e=currentPhoto.edits;const im=$('#editorImage');im.style.filter=cssFilters(e);im.style.transform=`scale(${1+Math.max(0,e.texture+e.clarity)*.0002})`;const v=Math.max(0,-e.vignette)/100;im.style.boxShadow=v?`0 0 ${70+v*80}px ${v*25}px rgba(0,0,0,${.25+v*.55}) inset`:'none'}
function updateRating(){$$('#ratingButtons button').forEach(b=>b.classList.toggle('on',+b.dataset.rate<=currentPhoto.rating))}
async function exportPhoto(){if(!currentPhoto)return;toast('Rendering export…');const bmp=await createImageBitmap(currentPhoto.blob);const max=4096,scale=Math.min(1,max/Math.max(bmp.width,bmp.height));const w=Math.round(bmp.width*scale),h=Math.round(bmp.height*scale);const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d');const e=currentPhoto.edits;ctx.filter=cssFilters(e);ctx.drawImage(bmp,0,0,w,h);ctx.filter='none';if(e.vignette<0){const strength=Math.min(.85,-e.vignette/100*.8),grad=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.2,w/2,h/2,Math.max(w,h)*.72);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(1,`rgba(0,0,0,${strength})`);ctx.fillStyle=grad;ctx.fillRect(0,0,w,h)}if(e.grain>0){const count=Math.round(w*h*Math.min(.08,e.grain/100*.045));ctx.globalAlpha=Math.min(.18,e.grain/100*.2);for(let i=0;i<count;i++){const v=Math.random()*255|0;ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(Math.random()*w,Math.random()*h,1,1)}ctx.globalAlpha=1}const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.92));const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=currentPhoto.name.replace(/\.[^.]+$/,'')+'-darkroom.jpg';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Export ready')}
function showAlbumModal(){const m=$('#modalBackdrop');m.classList.remove('hidden');$('#albumName').value='';setTimeout(()=>$('#albumName').focus(),50)}
function hideAlbumModal(){$('#modalBackdrop').classList.add('hidden')}
async function createAlbum(){const name=$('#albumName').value.trim();if(!name)return;await put('albums',{id:uid(),name,created:Date.now()});hideAlbumModal();await refreshData();toast('Album created')}

$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));$('#storageBtn').onclick=()=>route('storage');$('#importTop').onclick=$('#emptyImport').onclick=$('#mobileAdd').onclick=()=>$('#fileInput').click();$('#fileInput').onchange=e=>{importFiles(e.target.files);e.target.value=''};$('#searchInput').oninput=()=>{if(!['library','recent','favorites'].includes(currentRoute))route('library');else renderPhotos()};$('#sortSelect').onchange=renderPhotos;$('#gridSizeBtn').onclick=()=>{gridMode=gridMode===5?4:gridMode===4?6:5;renderPhotos()};$('#newAlbumBtn').onclick=showAlbumModal;$('#cancelModal').onclick=hideAlbumModal;$('#createAlbum').onclick=createAlbum;$('#albumName').onkeydown=e=>{if(e.key==='Enter')createAlbum()};$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))hideAlbumModal()};$('#closeEditor').onclick=closeEditor;$('#exportBtn').onclick=exportPhoto;$('#favoriteBtn').onclick=()=>{currentPhoto.favorite=!currentPhoto.favorite;$('#favoriteBtn').textContent=currentPhoto.favorite?'♥':'♡';debouncedSave()};$$('#toolTabs button').forEach(b=>b.onclick=()=>{currentPanel=b.dataset.panel;renderControls()});$('#resetEdits').onclick=()=>{currentPhoto.edits=defaultEdits();renderControls();updatePreview();debouncedSave();toast('Edits reset')};$$('#ratingButtons button').forEach(b=>b.onclick=()=>{currentPhoto.rating=+b.dataset.rate===currentPhoto.rating?0:+b.dataset.rate;updateRating();debouncedSave()});$('#deletePhoto').onclick=async()=>{if(!confirm('Delete this photo from DarkRoom local storage?'))return;const id=currentPhoto.id;$('#editor').classList.add('hidden');currentPhoto=null;await del('photos',id);await refreshData();toast('Photo deleted')};$('#clearLibrary').onclick=async()=>{if(!confirm('Delete every photo and album stored by DarkRoom in this browser? This cannot be undone.'))return;await clearStore('photos');await clearStore('albums');await refreshData();toast('Local library deleted')};window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#editor').classList.contains('hidden'))closeEditor()});window.addEventListener('resize',()=>renderPhotos());
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
initDB().catch(e=>{console.error(e);toast('Could not open local storage')});
