const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const DB_NAME='darkroom-db', DB_VERSION=2; let db,photos=[],albums=[],currentPhoto=null,currentRoute='library',currentAlbumId=null,currentPanel='light',gridMode=5,saveTimer;
let zoom=1,panX=0,panY=0,drag=null,pinch=null,renderToken=0;
const defaultEdits=()=>({exposure:0,contrast:0,highlights:0,shadows:0,whites:0,blacks:0,temp:0,tint:0,vibrance:0,saturation:0,texture:0,clarity:0,dehaze:0,vignette:0,grain:0,sharpness:0,noise:0,rotation:0,flipX:false,flipY:false});
const panelDefs={light:[['exposure','Exposure',-100,100],['contrast','Contrast',-100,100],['highlights','Highlights',-100,100],['shadows','Shadows',-100,100],['whites','Whites',-100,100],['blacks','Blacks',-100,100]],color:[['temp','Temperature',-100,100],['tint','Tint',-100,100],['vibrance','Vibrance',-100,100],['saturation','Saturation',-100,100]],effects:[['texture','Texture',-100,100],['clarity','Clarity',-100,100],['dehaze','Dehaze',-100,100],['vignette','Vignette',-100,100],['grain','Grain',0,100]],detail:[['sharpness','Sharpening',0,100],['noise','Noise Reduction',0,100]]};
function reqP(r){return new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function initDB(){db=await new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=()=>{const d=r.result;if(!d.objectStoreNames.contains('photos'))d.createObjectStore('photos',{keyPath:'id'});if(!d.objectStoreNames.contains('albums'))d.createObjectStore('albums',{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)});try{await navigator.storage?.persist?.()}catch{}await refreshData()}
const getAll=s=>reqP(db.transaction(s).objectStore(s).getAll()); const put=(s,o)=>reqP(db.transaction(s,'readwrite').objectStore(s).put(o)); const del=(s,id)=>reqP(db.transaction(s,'readwrite').objectStore(s).delete(id)); const clearStore=s=>reqP(db.transaction(s,'readwrite').objectStore(s).clear());
async function refreshData(){photos=await getAll('photos');albums=await getAll('albums');render();updateStorage()}
const uid=()=>crypto.randomUUID?.()||Date.now()+'-'+Math.random().toString(16).slice(2); const fmtBytes=n=>!n?'0 MB':n<1048576?(n/1024).toFixed(0)+' KB':n<1073741824?(n/1048576).toFixed(n<10485760?1:0)+' MB':(n/1073741824).toFixed(2)+' GB';
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._tm);t._tm=setTimeout(()=>t.classList.remove('show'),1800)}
function blobUrl(p){if(!p._url)p._url=URL.createObjectURL(p.blob);return p._url}
function imageDimensions(blob){return new Promise((res,rej)=>{const i=new Image(),u=URL.createObjectURL(blob);i.onload=()=>{res({width:i.naturalWidth,height:i.naturalHeight});URL.revokeObjectURL(u)};i.onerror=e=>{URL.revokeObjectURL(u);rej(e)};i.src=u})}
async function importFiles(files){const imgs=[...files].filter(f=>f.type.startsWith('image/'));if(!imgs.length)return toast('No supported images selected');toast(`Importing ${imgs.length} photo${imgs.length>1?'s':''}…`);for(const f of imgs){try{const d=await imageDimensions(f);await put('photos',{id:uid(),name:f.name,type:f.type,size:f.size,created:Date.now(),modified:f.lastModified||Date.now(),width:d.width,height:d.height,blob:f,edits:defaultEdits(),favorite:false,rating:0,albumIds:[]})}catch(e){console.error(e)}}await refreshData();toast(`${imgs.length} photo${imgs.length>1?'s':''} added`)}
function filteredPhotos(){let list=[...photos];if(currentRoute==='favorites')list=list.filter(p=>p.favorite);if(currentRoute==='recent')list=list.filter(p=>Date.now()-p.created<7*864e5);if(currentRoute==='album')list=list.filter(p=>p.albumIds?.includes(currentAlbumId));const q=$('#searchInput').value.trim().toLowerCase();if(q)list=list.filter(p=>`${p.name} ${(p.albumIds||[]).map(id=>albums.find(a=>a.id===id)?.name||'').join(' ')} ${new Date(p.created).toLocaleDateString()}`.toLowerCase().includes(q));const s=$('#sortSelect').value;list.sort(s==='old'?(a,b)=>a.created-b.created:s==='name'?(a,b)=>a.name.localeCompare(b.name):s==='rating'?(a,b)=>b.rating-a.rating:(a,b)=>b.created-a.created);return list}
function render(){renderPhotos();renderAlbums();$('#allCount').textContent=photos.length;$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===currentRoute||(currentRoute==='album'&&b.dataset.route==='albums')))}
function renderPhotos(){const g=$('#photoGrid'),empty=$('#emptyState'),list=filteredPhotos();let title='All Photos',sub='Your photos, stored on this device.';if(currentRoute==='recent'){title='Recently Added';sub='Photos imported in the last 7 days.'}if(currentRoute==='favorites'){title='Favorites';sub='Photos you marked as favorites.'}if(currentRoute==='album'){const a=albums.find(x=>x.id===currentAlbumId);title=a?.name||'Album';sub=`${list.length} photo${list.length===1?'':'s'} · stored locally`;}
$('#viewTitle').textContent=title;$('#viewSubtitle').textContent=sub;$('#albumActions').hidden=currentRoute!=='album';empty.style.display=list.length?'none':'flex';g.style.display=list.length?'grid':'none';g.innerHTML=list.map(p=>`<article class="photo-card" data-photo="${p.id}"><img src="${blobUrl(p)}" alt="${esc(p.name)}" loading="lazy"><div class="photo-overlay"><span>${p.rating?'★'.repeat(p.rating):''}</span><span>${p.favorite?'♥':''}</span></div></article>`).join('');$$('.photo-card').forEach(c=>c.onclick=()=>openEditor(c.dataset.photo));if(innerWidth>760)g.style.gridTemplateColumns=`repeat(${gridMode},minmax(0,1fr))`}
function renderAlbums(){const ag=$('#albumGrid');if(!albums.length){ag.innerHTML='<div class="info-card"><b>No albums yet</b><p>Create an album to group photos without duplicating files.</p></div>';return}ag.innerHTML=albums.map(a=>{const ps=photos.filter(p=>p.albumIds?.includes(a.id));return `<article class="album-card" data-album="${a.id}"><div class="album-cover">${ps.slice(0,4).map(p=>`<img src="${blobUrl(p)}" alt="">`).join('')||'<div class="album-empty">▱</div>'}</div><h3>${esc(a.name)}</h3><small>${ps.length} photos</small></article>`}).join('');$$('.album-card').forEach(c=>c.onclick=()=>{currentAlbumId=c.dataset.album;route('album')})}
async function updateStorage(){const photoBytes=photos.reduce((n,p)=>n+(p.size||0),0);let q=0,u=0,persisted=false;try{const e=await navigator.storage.estimate();q=e.quota||0;u=e.usage||0;persisted=await navigator.storage.persisted?.()||false}catch{}const pct=q?Math.min(100,u/q*100):0;$('#storageBig').textContent=fmtBytes(photoBytes);$('#photoStorage').textContent=fmtBytes(photoBytes);$('#quotaStorage').textContent=q?fmtBytes(Math.max(0,q-u)):'Browser controlled';$('#storageMode').textContent=persisted?'Persistent local storage':'Browser-managed local storage';$('#usageBar').style.width=pct+'%';$('#sideMeter').style.width=pct+'%';$('#sideStorage').textContent=`${fmtBytes(photoBytes)} stored locally`;$('#donut').style.background=`conic-gradient(#e1e1e1 ${pct*3.6}deg,#242424 0)`}
function route(r){currentRoute=r;$$('.view').forEach(v=>v.classList.remove('active'));if(r==='albums')$('#albumsView').classList.add('active');else if(r==='storage')$('#storageView').classList.add('active');else $('#libraryView').classList.add('active');render()}
function filterString(e){const bright=100+e.exposure*.55+e.whites*.16+e.shadows*.10-e.blacks*.10+e.highlights*.05;const contrast=100+e.contrast*.65+e.clarity*.25+e.texture*.12+e.dehaze*.30+e.sharpness*.08;const sat=100+e.saturation*.75+e.vibrance*.35+e.dehaze*.10;const sepia=Math.max(0,e.temp)*.16;const hue=e.tint*.12-Math.max(0,e.temp)*.08;const blur=Math.max(0,e.noise)*.012;return `brightness(${Math.max(10,bright)}%) contrast(${Math.max(10,contrast)}%) saturate(${Math.max(0,sat)}%) sepia(${sepia}%) hue-rotate(${hue}deg) blur(${blur}px)`}
function applyTransform(){const w=$('#canvasWrap');w.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
function resetZoom(){zoom=1;panX=panY=0;applyTransform()}
async function renderCanvas(canvas,maxSize=1800){if(!currentPhoto)return;const token=canvas.id==='editorCanvas'?++renderToken:null,bmp=await createImageBitmap(currentPhoto.blob),e=currentPhoto.edits;const rot=((e.rotation||0)%360+360)%360,swap=rot===90||rot===270,baseW=swap?bmp.height:bmp.width,baseH=swap?bmp.width:bmp.height,scale=Math.min(1,maxSize/Math.max(baseW,baseH)),w=Math.max(1,Math.round(baseW*scale)),h=Math.max(1,Math.round(baseH*scale));if(token!==null&&token!==renderToken){bmp.close?.();return}canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{alpha:false});ctx.save();ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);ctx.filter=filterString(e);ctx.translate(w/2,h/2);ctx.rotate(rot*Math.PI/180);ctx.scale(e.flipX?-1:1,e.flipY?-1:1);ctx.drawImage(bmp,-bmp.width*scale/2,-bmp.height*scale/2,bmp.width*scale,bmp.height*scale);ctx.restore();ctx.filter='none';if(e.vignette){const s=Math.abs(e.vignette)/100*.75,g=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.22,w/2,h/2,Math.max(w,h)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,e.vignette<0?`rgba(0,0,0,${s})`:`rgba(255,255,255,${s*.45})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}if(e.grain>0){const count=Math.min(180000,Math.round(w*h*e.grain/100*.025));ctx.globalAlpha=Math.min(.18,e.grain/500);for(let i=0;i<count;i++){const v=Math.random()*255|0;ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(Math.random()*w,Math.random()*h,1,1)}ctx.globalAlpha=1}bmp.close?.()}
async function openEditor(id){currentPhoto=photos.find(p=>p.id===id);if(!currentPhoto)return;currentPhoto.edits={...defaultEdits(),...(currentPhoto.edits||{})};$('#editor').classList.remove('hidden');$('#editor').setAttribute('aria-hidden','false');$('#editorName').textContent=currentPhoto.name;$('#editorMeta').textContent=`${currentPhoto.width||'—'} × ${currentPhoto.height||'—'} · ${fmtBytes(currentPhoto.size)}`;$('#favoriteBtn').textContent=currentPhoto.favorite?'♥':'♡';currentPanel='light';resetZoom();renderControls();updateRating();await renderCanvas($('#editorCanvas'))}
async function closeEditor(){if(!currentPhoto)return;await put('photos',currentPhoto);$('#editor').classList.add('hidden');$('#editor').setAttribute('aria-hidden','true');currentPhoto=null;await refreshData()}
function renderControls(){if(!currentPhoto)return;$$('#toolTabs button').forEach(b=>b.classList.toggle('active',b.dataset.panel===currentPanel));const c=$('#controls');if(currentPanel==='transform'){const e=currentPhoto.edits;c.innerHTML=`<div class="transform-tools"><button data-transform="left">↶ Rotate</button><button data-transform="right">↷ Rotate</button><button data-transform="flipX">↔ Flip H</button><button data-transform="flipY">↕ Flip V</button></div>`;$$('[data-transform]').forEach(b=>b.onclick=()=>{if(b.dataset.transform==='left')e.rotation=(e.rotation-90)%360;if(b.dataset.transform==='right')e.rotation=(e.rotation+90)%360;if(b.dataset.transform==='flipX')e.flipX=!e.flipX;if(b.dataset.transform==='flipY')e.flipY=!e.flipY;renderCanvas($('#editorCanvas'));debouncedSave()});return}if(currentPanel==='albums'){c.innerHTML=`<div class="album-membership">${albums.length?albums.map(a=>`<label><input type="checkbox" data-album-toggle="${a.id}" ${(currentPhoto.albumIds||[]).includes(a.id)?'checked':''}> ${esc(a.name)}</label>`).join(''):'<p>No albums yet. Create one from Albums.</p>'}</div>`;$$('[data-album-toggle]').forEach(i=>i.onchange=()=>{const ids=new Set(currentPhoto.albumIds||[]);i.checked?ids.add(i.dataset.albumToggle):ids.delete(i.dataset.albumToggle);currentPhoto.albumIds=[...ids];debouncedSave()});return}if(currentPanel==='info'){c.innerHTML=`<div class="info-grid"><div class="info-cell"><small>Filename</small>${esc(currentPhoto.name)}</div><div class="info-cell"><small>Dimensions</small>${currentPhoto.width} × ${currentPhoto.height}</div><div class="info-cell"><small>File size</small>${fmtBytes(currentPhoto.size)}</div><div class="info-cell"><small>Imported</small>${new Date(currentPhoto.created).toLocaleString()}</div></div>`;return}c.innerHTML=panelDefs[currentPanel].map(([key,label,min,max])=>`<div class="control"><label><span>${label}</span><b id="v-${key}">${currentPhoto.edits[key]>0?'+':''}${currentPhoto.edits[key]}</b></label><input type="range" min="${min}" max="${max}" value="${currentPhoto.edits[key]}" data-edit="${key}"></div>`).join('');$$('[data-edit]').forEach(r=>r.oninput=()=>{currentPhoto.edits[r.dataset.edit]=+r.value;$('#v-'+r.dataset.edit).textContent=(+r.value>0?'+':'')+r.value;renderCanvas($('#editorCanvas'));debouncedSave()})}
function debouncedSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>currentPhoto&&put('photos',currentPhoto),300)}
function updateRating(){$$('#ratingButtons button').forEach(b=>b.classList.toggle('on',+b.dataset.rate<=currentPhoto.rating))}
async function exportPhoto(){if(!currentPhoto)return;toast('Rendering export…');const c=document.createElement('canvas');await renderCanvas(c,4096);const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.92));if(!blob)return toast('Export failed');const name=currentPhoto.name.replace(/\.[^.]+$/,'')+'-darkroom.jpg';if(navigator.share&&navigator.canShare?.({files:[new File([blob],name,{type:'image/jpeg'})]})){try{await navigator.share({files:[new File([blob],name,{type:'image/jpeg'})],title:name});return toast('Shared')}catch{}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('Export ready')}
function showAlbumModal(){const m=$('#modalBackdrop');m.classList.remove('hidden');$('#albumName').value='';setTimeout(()=>$('#albumName').focus(),50)}function hideAlbumModal(){$('#modalBackdrop').classList.add('hidden')}
async function createAlbum(){const name=$('#albumName').value.trim();if(!name)return;await put('albums',{id:uid(),name,created:Date.now()});hideAlbumModal();await refreshData();toast('Album created')}
async function renameAlbum(){const a=albums.find(x=>x.id===currentAlbumId);if(!a)return;const name=prompt('Rename album',a.name)?.trim();if(!name)return;a.name=name;await put('albums',a);await refreshData()}
async function deleteAlbum(){const a=albums.find(x=>x.id===currentAlbumId);if(!a||!confirm(`Delete album “${a.name}”? Photos will stay in your library.`))return;for(const p of photos.filter(p=>p.albumIds?.includes(a.id))){p.albumIds=p.albumIds.filter(id=>id!==a.id);await put('photos',p)}await del('albums',a.id);currentAlbumId=null;route('albums');await refreshData();toast('Album deleted')}
function initZoom(){const vp=$('#photoViewport');vp.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.5,Math.min(8,zoom*(e.deltaY<0?1.12:.89)));applyTransform()},{passive:false});vp.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag={x:e.clientX-panX,y:e.clientY-panY};vp.setPointerCapture(e.pointerId)});vp.addEventListener('pointermove',e=>{if(!drag)return;panX=e.clientX-drag.x;panY=e.clientY-drag.y;applyTransform()});vp.addEventListener('pointerup',()=>drag=null);vp.addEventListener('touchstart',e=>{if(e.touches.length===1)drag={x:e.touches[0].clientX-panX,y:e.touches[0].clientY-panY};if(e.touches.length===2){const [a,b]=e.touches;pinch={d:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),z:zoom};drag=null}},{passive:true});vp.addEventListener('touchmove',e=>{if(e.touches.length===1&&drag){panX=e.touches[0].clientX-drag.x;panY=e.touches[0].clientY-drag.y;applyTransform()}if(e.touches.length===2&&pinch){const [a,b]=e.touches,d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);zoom=Math.max(.5,Math.min(8,pinch.z*d/pinch.d));applyTransform()}},{passive:true});vp.addEventListener('touchend',()=>{drag=null;pinch=null})}
$$('[data-route]').forEach(b=>b.onclick=()=>route(b.dataset.route));$('#storageBtn').onclick=()=>route('storage');['#importTop','#emptyImport','#mobileAdd'].forEach(s=>$(s).onclick=()=>$('#fileInput').click());$('#fileInput').onchange=e=>{importFiles(e.target.files);e.target.value=''};$('#searchInput').oninput=()=>{if(!['library','recent','favorites','album'].includes(currentRoute))route('library');else renderPhotos()};$('#sortSelect').onchange=renderPhotos;$('#gridSizeBtn').onclick=()=>{gridMode=gridMode===5?4:gridMode===4?6:5;renderPhotos()};$('#newAlbumBtn').onclick=showAlbumModal;$('#cancelModal').onclick=hideAlbumModal;$('#createAlbum').onclick=createAlbum;$('#albumName').onkeydown=e=>{if(e.key==='Enter')createAlbum()};$('#modalBackdrop').onclick=e=>{if(e.target===$('#modalBackdrop'))hideAlbumModal()};$('#closeEditor').onclick=closeEditor;$('#exportBtn').onclick=exportPhoto;$('#favoriteBtn').onclick=()=>{currentPhoto.favorite=!currentPhoto.favorite;$('#favoriteBtn').textContent=currentPhoto.favorite?'♥':'♡';debouncedSave()};$$('#toolTabs button').forEach(b=>b.onclick=()=>{currentPanel=b.dataset.panel;renderControls()});$('#resetEdits').onclick=()=>{currentPhoto.edits=defaultEdits();renderControls();renderCanvas($('#editorCanvas'));debouncedSave();toast('Edits reset')};$$('#ratingButtons button').forEach(b=>b.onclick=()=>{currentPhoto.rating=+b.dataset.rate===currentPhoto.rating?0:+b.dataset.rate;updateRating();debouncedSave()});$('#deletePhoto').onclick=async()=>{if(!confirm('Delete this photo from DarkRoom local storage?'))return;const id=currentPhoto.id;$('#editor').classList.add('hidden');currentPhoto=null;await del('photos',id);await refreshData();toast('Photo deleted')};$('#clearLibrary').onclick=async()=>{if(!confirm('Delete every photo and album stored by DarkRoom in this browser? This cannot be undone.'))return;await clearStore('photos');await clearStore('albums');await refreshData();toast('Local library deleted')};$('#renameAlbum').onclick=renameAlbum;$('#deleteAlbum').onclick=deleteAlbum;$('#zoomIn').onclick=()=>{zoom=Math.min(8,zoom*1.25);applyTransform()};$('#zoomOut').onclick=()=>{zoom=Math.max(.5,zoom/1.25);applyTransform()};$('#zoomReset').onclick=resetZoom;window.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#editor').classList.contains('hidden'))closeEditor();if((e.ctrlKey||e.metaKey)&&e.key==='0'){e.preventDefault();resetZoom()}});window.addEventListener('resize',renderPhotos);initZoom();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(console.error));initDB().catch(e=>{console.error(e);toast('Could not open local storage')});
