function syncEditorMeta(){if(!currentPhoto)return;$('#editorName').textContent=currentPhoto.name;$('#editorMeta').textContent=`${currentPhoto.width||'—'} × ${currentPhoto.height||'—'} · ${fmtBytes(currentPhoto.size)}`;$('#favoriteBtn').textContent=currentPhoto.favorite?'♥':'♡';updateRating();$('#pickBtn').classList.toggle('on',currentPhoto.flag==='picked');$('#rejectBtn').classList.toggle('rejected',currentPhoto.flag==='rejected');$('#beforeAfterBtn').style.background=beforeMode?'#3b3b3b':''}
async function closeEditor(){if(!currentPhoto)return;await put('photos',currentPhoto);$('#editor').classList.add('hidden');$('#editor').setAttribute('aria-hidden','true');currentPhoto=null;beforeMode=false;await refreshData()}
function sliderMarkup(defs){return defs.map(([key,label,min,max])=>`<div class="control"><label><span>${label}</span><b id="v-${key}">${currentPhoto.edits[key]>0?'+':''}${currentPhoto.edits[key]}</b></label><input type="range" min="${min}" max="${max}" value="${currentPhoto.edits[key]}" data-edit="${key}"></div>`).join('')}
function renderControls(){if(!currentPhoto)return;$$('#toolTabs button').forEach(b=>b.classList.toggle('active',b.dataset.panel===currentPanel));const c=$('#controls');
 if(currentPanel==='presets'){c.innerHTML=`<div class="section-title"><span>Presets</span><small>Local</small></div><div class="preset-grid">${Object.entries(presets).map(([name,p])=>`<button class="preset-button" data-preset="${name}"><b>${name}</b><small>${Object.keys(p).slice(0,2).join(' · ')}</small></button>`).join('')}</div>`;$$('[data-preset]').forEach(b=>b.onclick=()=>{captureHistory();currentPhoto.edits={...currentPhoto.edits,...presets[b.dataset.preset]};captureHistory();renderCanvas($('#editorCanvas'));debouncedSave();toast(`${b.dataset.preset} applied`)});return}
 if(currentPanel==='transform'){const e=currentPhoto.edits;c.innerHTML=`<div class="section-title"><span>Crop & Rotate</span><small>Nondestructive</small></div><div class="transform-tools"><button data-transform="left">↶ Rotate Left</button><button data-transform="right">↷ Rotate Right</button><button data-transform="flipX">↔ Flip Horizontal</button><button data-transform="flipY">↕ Flip Vertical</button></div><div class="crop-controls"><div class="control"><label><span>Straighten</span><b id="v-angle">${e.angle>0?'+':''}${e.angle}</b></label><input type="range" min="-45" max="45" value="${e.angle}" data-edit="angle"></div><div class="crop-row">${['original','1:1','4:3','3:2','16:9','9:16'].map(a=>`<button class="panel-button ${e.cropAspect===a?'active':''}" data-aspect="${a}">${a==='original'?'Original':a}</button>`).join('')}</div></div>`;bindSliders();$$('[data-transform]').forEach(b=>b.onclick=()=>{captureHistory();if(b.dataset.transform==='left')e.rotation=(e.rotation-90)%360;if(b.dataset.transform==='right')e.rotation=(e.rotation+90)%360;if(b.dataset.transform==='flipX')e.flipX=!e.flipX;if(b.dataset.transform==='flipY')e.flipY=!e.flipY;captureHistory();renderCanvas($('#editorCanvas'));debouncedSave()});$$('[data-aspect]').forEach(b=>b.onclick=()=>{captureHistory();e.cropAspect=b.dataset.aspect;captureHistory();renderControls();renderCanvas($('#editorCanvas'));debouncedSave()});return}
 if(currentPanel==='albums'){c.innerHTML=`<div class="section-title"><span>Add to Albums</span><small>${currentPhoto.albumIds.length} selected</small></div><div class="album-membership">${albums.length?albums.map(a=>`<label><input type="checkbox" data-album-toggle="${a.id}" ${currentPhoto.albumIds.includes(a.id)?'checked':''}> ${esc(a.name)}</label>`).join(''):'<p>No albums yet. Create one from Albums.</p>'}</div>`;$$('[data-album-toggle]').forEach(i=>i.onchange=()=>{captureHistory();const ids=new Set(currentPhoto.albumIds);i.checked?ids.add(i.dataset.albumToggle):ids.delete(i.dataset.albumToggle);currentPhoto.albumIds=[...ids];captureHistory();debouncedSave()});return}
 if(currentPanel==='info'){c.innerHTML=`<div class="section-title"><span>Info</span><small>Local metadata</small></div><div class="info-grid"><div class="info-cell"><small>Filename</small>${esc(currentPhoto.name)}</div><div class="info-cell"><small>Dimensions</small>${currentPhoto.width} × ${currentPhoto.height}</div><div class="info-cell"><small>File type</small>${esc(currentPhoto.type||'Unknown')}</div><div class="info-cell"><small>File size</small>${fmtBytes(currentPhoto.size)}</div><div class="info-cell"><small>Imported</small>${new Date(currentPhoto.created).toLocaleString()}</div><div class="info-cell"><small>Modified</small>${new Date(currentPhoto.modified).toLocaleString()}</div><div class="info-cell"><small>Rating</small>${currentPhoto.rating||'Unrated'}</div><div class="info-cell"><small>Flag</small>${currentPhoto.flag}</div></div>`;return}
 const defs=panelDefs[currentPanel];c.innerHTML=`<div class="section-title"><span>${currentPanel[0].toUpperCase()+currentPanel.slice(1)}</span><small>Adjustments</small></div>${sliderMarkup(defs)}`;bindSliders()}
function bindSliders(){$$('[data-edit]').forEach(r=>{r.onpointerdown=()=>captureHistory();r.oninput=()=>{currentPhoto.edits[r.dataset.edit]=+r.value;const v=$('#v-'+r.dataset.edit);if(v)v.textContent=(+r.value>0?'+':'')+r.value;renderCanvas($('#editorCanvas'))};r.onchange=()=>{captureHistory();debouncedSave()}})}
function debouncedSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>currentPhoto&&put('photos',currentPhoto),250)}
function updateRating(){$$('#ratingButtons button').forEach(b=>b.classList.toggle('on',+b.dataset.rate<=currentPhoto.rating))}
async function exportPhoto(){if(!currentPhoto)return;toast('Rendering export…');const c=document.createElement('canvas');await renderCanvas(c,4096,false);const blob=await new Promise(res=>c.toBlob(res,'image/jpeg',.92));if(!blob)return toast('Export failed');const name=currentPhoto.name.replace(/\.[^.]+$/,'')+'-darkroom.jpg';const file=new File([blob],name,{type:'image/jpeg'});if(navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({files:[file],title:name});return toast('Shared')}catch(e){if(e.name!=='AbortError')console.warn(e)}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000);toast('Export ready')}
function showAlbumModal(){$('#modalBackdrop').classList.remove('hidden');$('#albumName').value='';setTimeout(()=>$('#albumName').focus(),50)}function hideAlbumModal(){$('#modalBackdrop').classList.add('hidden')}
async function createAlbum(){const name=$('#albumName').value.trim();if(!name)return;await put('albums',{id:uid(),name,created:Date.now()});hideAlbumModal();await refreshData();toast('Album created')}
async function renameAlbum(){const a=albums.find(x=>x.id===currentAlbumId);if(!a)return;const name=prompt('Rename album',a.name)?.trim();if(!name)return;a.name=name;await put('albums',a);await refreshData();toast('Album renamed')}
async function deleteAlbum(){const a=albums.find(x=>x.id===currentAlbumId);if(!a||!confirm(`Delete album “${a.name}”? Photos will stay in your library.`))return;for(const p of albumPhotos(a.id)){p.albumIds=p.albumIds.filter(id=>id!==a.id);await put('photos',p)}await del('albums',a.id);currentAlbumId=null;route('albums');await refreshData();toast('Album deleted')}
function setFlag(flag){captureHistory();currentPhoto.flag=currentPhoto.flag===flag?'none':flag;captureHistory();syncEditorMeta();debouncedSave()}
function initZoom(){const vp=$('#photoViewport');vp.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.25,Math.min(8,zoom*(e.deltaY<0?1.12:.89)));applyTransform()},{passive:false});vp.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;drag={x:e.clientX-panX,y:e.clientY-panY};vp.setPointerCapture(e.pointerId)});vp.addEventListener('pointermove',e=>{if(!drag)return;panX=e.clientX-drag.x;panY=e.clientY-drag.y;applyTransform()});vp.addEventListener('pointerup',()=>drag=null);vp.addEventListener('pointercancel',()=>drag=null);vp.addEventListener('touchstart',e=>{if(e.touches.length===1)drag={x:e.touches[0].clientX-panX,y:e.touches[0].clientY-panY};if(e.touches.length===2){const [a,b]=e.touches;pinch={d:Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY),z:zoom};drag=null}},{passive:true});vp.addEventListener('touchmove',e=>{if(e.touches.length===1&&drag){panX=e.touches[0].clientX-drag.x;panY=e.touches[0].clientY-drag.y;applyTransform()}if(e.touches.length===2&&pinch){const [a,b]=e.touches,d=Math.hypot(a.clientX-b.clientX,a.clientY-b.clientY);zoom=Math.max(.25,Math.min(8,pinch.z*d/pinch.d));applyTransform()}},{passive:true});vp.addEventListener('touchend',()=>{drag=null;pinch=null});vp.ondblclick=()=>{zoom=zoom===1?2:1;panX=panY=0;applyTransform()}}
