(function(root){
'use strict';
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const clamp255=v=>Math.max(0,Math.min(255,v));
const mix=(a,b,t)=>a+(b-a)*t;
const curveModelCache=new WeakMap();
function curveModel(input){if(!Array.isArray(input)||input.length<2)return null;const cached=curveModelCache.get(input);if(cached)return cached;const points=[];for(const raw of input.filter(p=>Number.isFinite(+p?.x)&&Number.isFinite(+p?.y)).map(p=>({x:clamp(+p.x),y:clamp(+p.y)})).sort((a,b)=>a.x-b.x)){const previous=points.at(-1);if(previous&&Math.abs(previous.x-raw.x)<.0001)previous.y=raw.y;else points.push(raw)}if(points.length<2){curveModelCache.set(input,null);return null}const n=points.length,h=[],delta=[];for(let i=0;i<n-1;i++){h[i]=Math.max(.0001,points[i+1].x-points[i].x);delta[i]=(points[i+1].y-points[i].y)/h[i]}const tangent=new Array(n).fill(0);if(n===2)tangent[0]=tangent[1]=delta[0];else{tangent[0]=((2*h[0]+h[1])*delta[0]-h[0]*delta[1])/(h[0]+h[1]);if(Math.sign(tangent[0])!==Math.sign(delta[0]))tangent[0]=0;else if(Math.sign(delta[0])!==Math.sign(delta[1])&&Math.abs(tangent[0])>Math.abs(3*delta[0]))tangent[0]=3*delta[0];for(let i=1;i<n-1;i++){if(delta[i-1]*delta[i]<=0)tangent[i]=0;else{const w1=2*h[i]+h[i-1],w2=h[i]+2*h[i-1];tangent[i]=(w1+w2)/(w1/delta[i-1]+w2/delta[i])}}const last=n-1;tangent[last]=((2*h[last-1]+h[last-2])*delta[last-1]-h[last-1]*delta[last-2])/(h[last-1]+h[last-2]);if(Math.sign(tangent[last])!==Math.sign(delta[last-1]))tangent[last]=0;else if(Math.sign(delta[last-1])!==Math.sign(delta[last-2])&&Math.abs(tangent[last])>Math.abs(3*delta[last-1]))tangent[last]=3*delta[last-1]}const model={points,h,delta,tangent};curveModelCache.set(input,model);return model}
function curveValue(points,l){const model=curveModel(points);if(!model)return clamp(l);const p=model.points;if(l<=p[0].x)return clamp(p[0].y+(l-p[0].x)*model.tangent[0]);if(l>=p.at(-1).x)return clamp(p.at(-1).y+(l-p.at(-1).x)*model.tangent.at(-1));let i=0;while(i<p.length-2&&l>p[i+1].x)i++;const t=(l-p[i].x)/model.h[i],t2=t*t,t3=t2*t,h00=2*t3-3*t2+1,h10=t3-2*t2+t,h01=-2*t3+3*t2,h11=t3-t2;return clamp(h00*p[i].y+h10*model.h[i]*model.tangent[i]+h01*p[i+1].y+h11*model.h[i]*model.tangent[i+1])}
function rgbToHsl(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b),d=mx-mn;let h=0,s=0,l=(mx+mn)/2;if(d){s=d/(1-Math.abs(2*l-1));if(mx===r)h=((g-b)/d)%6;else if(mx===g)h=(b-r)/d+2;else h=(r-g)/d+4;h=(h*60+360)%360}return[h,s,l]}
function hslToRgb(h,s,l){h=((h%360)+360)%360;s=clamp(s);l=clamp(l);const c=(1-Math.abs(2*l-1))*s,x=c*(1-Math.abs((h/60)%2-1)),m=l-c/2;let r=0,g=0,b=0;if(h<60){r=c;g=x}else if(h<120){r=x;g=c}else if(h<180){g=c;b=x}else if(h<240){g=x;b=c}else if(h<300){r=x;b=c}else{r=c;b=x}return[(r+m)*255,(g+m)*255,(b+m)*255]}
const BANDS=[['Red',0],['Orange',30],['Yellow',60],['Green',120],['Aqua',180],['Blue',240],['Purple',280],['Magenta',325]];
function hueBand(h){let best=BANDS[0],bd=999;for(const p of BANDS){const d=Math.min(Math.abs(h-p[1]),360-Math.abs(h-p[1]));if(d<bd){bd=d;best=p}}return best[0]}
function curveLuma(l,e){if(Array.isArray(e.curvePoints)&&e.curvePoints.length>=2)return curveValue(e.curvePoints,l);const knobs=[[.03,e.curveBlacks||0,.16],[.25,e.curveShadows||0,.22],[.5,e.curveMidtones||0,.24],[.75,e.curveHighlights||0,.22],[.97,e.curveWhites||0,.16]];let v=l;for(const [center,val,amp] of knobs){const fall=clamp(1-Math.abs(l-center)/.28);v+=val/100*amp*fall}return clamp(v)}
function grade(r,g,b,l,e){let hue=0,sat=0,lum=0;const balance=(e.gradeBalance||0)/100,split=.5+balance*.18,blend=clamp((e.gradeBlending??50)/100,.05,1);if(l<split-.12){hue=e.gradeShadowHue||0;sat=e.gradeShadowSat||0;lum=e.gradeShadowLum||0}else if(l>split+.12){hue=e.gradeHighHue||0;sat=e.gradeHighSat||0;lum=e.gradeHighLum||0}else{hue=e.gradeMidHue||0;sat=e.gradeMidSat||0;lum=e.gradeMidLum||0}let [h,s,li]=rgbToHsl(r,g,b);if(sat){const dh=((hue-h+540)%360)-180;h+=dh*Math.abs(sat)/125*blend;s=clamp(s+sat/280*blend)}li=clamp(li+lum/100*.22);return hslToRgb(h,s,li)}
function applyTonePixel(r,g,b,e={}){
 if(![r,g,b].every(Number.isFinite))return[0,0,0];
 let R=r/255,G=g/255,B=b/255;
 const temp=(e.temp||0)/100,tint=(e.tint||0)/100;R*=1+temp*.19+tint*.035;B*=1-temp*.19+tint*.035;G*=1-tint*.105;
 const exp=Math.pow(2,(e.exposure||0)/50);R*=exp;G*=exp;B*=exp;
 let l=.2126*R+.7152*G+.0722*B;
 const sh=(e.shadows||0)/100,hi=(e.highlights||0)/100,wh=(e.whites||0)/100,bl=(e.blacks||0)/100;
 const shadowMask=Math.pow(1-clamp(l),2),highMask=Math.pow(clamp(l),2);const tone=sh*.43*shadowMask+hi*.32*highMask+wh*.18*clamp((l-.5)/.5)+bl*.18*clamp((.5-l)/.5);R+=tone;G+=tone;B+=tone;
 const contrast=1+(e.contrast||0)/100*.72+(e.localContrast||0)/100*.12;R=(R-.5)*contrast+.5;G=(G-.5)*contrast+.5;B=(B-.5)*contrast+.5;
 const gamma=Math.max(.35,Math.min(2.5,(e.gamma??100)/100));R=Math.pow(clamp(R),1/gamma);G=Math.pow(clamp(G),1/gamma);B=Math.pow(clamp(B),1/gamma);
 l=.2126*R+.7152*G+.0722*B;const target=curveLuma(clamp(l),e),ratio=l>.001?target/l:1;R*=ratio;G*=ratio;B*=ratio;
 let [h,s,li]=rgbToHsl(clamp(R)*255,clamp(G)*255,clamp(B)*255);const band=hueBand(h),satAdj=(e['sat'+band]||0)/100,hueAdj=(e['hue'+band]||0)/100,lumAdj=(e['lum'+band]||0)/100,globalSat=(e.saturation||0)/100,vib=(e.vibrance||0)/100*(1-s);h+=hueAdj*45;if(globalSat<=-1)s=0;else s=clamp(s*(1+globalSat*.85+satAdj*.7)+vib*.45);li=clamp(li+lumAdj*.22);[R,G,B]=hslToRgb(h,s,li).map(v=>v/255);
 const deh=(e.dehaze||0)/100,clar=(e.clarity||0)/100,texture=(e.texture||0)/100,lc=(e.localContrast||0)/100;const cc=1+deh*.28+clar*.12+texture*.06+lc*.15;R=(R-.5)*cc+.5-deh*.025;G=(G-.5)*cc+.5-deh*.025;B=(B-.5)*cc+.5-deh*.025;
 [R,G,B]=grade(clamp(R)*255,clamp(G)*255,clamp(B)*255,clamp(li),e).map(v=>v/255);
 const fade=(e.fade||0)/100;if(fade>0){R=mix(R,.5,fade*.16);G=mix(G,.5,fade*.16);B=mix(B,.5,fade*.16)}
 if(globalSat<=-1){const mono=clamp(.2126*R+.7152*G+.0722*B);R=G=B=mono}
 if(![R,G,B].every(Number.isFinite))return[clamp255(r),clamp255(g),clamp255(b)];
 return[clamp(R)*255,clamp(G)*255,clamp(B)*255];
}
function localAdjustPixel(r,g,b,a,strength){if(!strength)return[r,g,b];const e={gamma:100,gradeBlending:50};for(const [k,v] of Object.entries(a||{}))e[k]=typeof v==='number'?v*strength:v;return applyTonePixel(r,g,b,e)}
function dist(x1,y1,x2,y2){return Math.hypot(x1-x2,y1-y2)}
function brushMask(mask,x,y,r=128,g=128,b=128){let best=0;for(const stroke of mask.strokes||[]){const radius=(stroke.size||mask.size||.08)/2,feather=stroke.feather??mask.feather??.6;let sv=0;for(const p of stroke.points||[]){const d=dist(x,y,p.x,p.y);if(d<radius){const hard=radius*(1-feather*.88),v=d<=hard?1:1-(d-hard)/Math.max(.0001,radius-hard);sv=Math.max(sv,clamp(v)*Math.abs(stroke.flow??mask.flow??1))}}if(stroke.autoMask&&stroke.target){const t=stroke.target,tol=stroke.edgeTolerance||85,similarity=clamp(1-Math.hypot(r-t[0],g-t[1],b-t[2])/tol);sv*=similarity}best=stroke.erase?best*(1-sv):Math.max(best,sv)}return best}
function rasterMask(mask,x,y){const r=mask.raster;if(!r||!r.data||!r.w||!r.h)return 0;const ix=Math.max(0,Math.min(r.w-1,Math.round(x*(r.w-1)))),iy=Math.max(0,Math.min(r.h-1,Math.round(y*(r.h-1))));return (r.data[iy*r.w+ix]||0)/255}
function rangeBand(value,lo,hi,soft=.08){return clamp(Math.min((value-lo)/Math.max(.001,soft),(hi-value)/Math.max(.001,soft),1))}
function primitiveMaskValue(mask,x,y,r,g,b,luma){let v=0;if(['brush','dodge','burn','heal','clone'].includes(mask.type))v=brushMask(mask,x,y,r,g,b);else if(mask.type==='radial'){const a=(mask.angle||0)*Math.PI/180,ca=Math.cos(a),sa=Math.sin(a),px=x-(mask.cx??.5),py=y-(mask.cy??.5),dx=(px*ca+py*sa)/(mask.rx||.3),dy=(-px*sa+py*ca)/(mask.ry||.3),d=Math.hypot(dx,dy);v=clamp((1-d)/Math.max(.001,mask.feather||.4))}else if(mask.type==='linear'){const ang=(mask.angle||0)*Math.PI/180,nx=Math.cos(ang),ny=Math.sin(ang),p=(x-(mask.cx??.5))*nx+(y-(mask.cy??.5))*ny;v=clamp(.5-p/Math.max(.02,mask.feather||.25))}else if(mask.type==='luminance'){v=rangeBand(luma,mask.lo??.25,mask.hi??.75,mask.feather??.1)}else if(mask.type==='parametric'){const [h,s]=rgbToHsl(r,g,b),hue=(h||0)/360,sat=s||0;v=rangeBand(luma,mask.lumaLo??0,mask.lumaHi??1,mask.softness??.08);if(mask.useHue){const target=(mask.hue??180)/360,tol=(mask.hueTolerance??45)/360,d=Math.min(Math.abs(hue-target),1-Math.abs(hue-target));v*=clamp(1-d/Math.max(.001,tol))}if(mask.useSaturation)v*=rangeBand(sat,mask.satLo??0,mask.satHi??1,mask.softness??.08)}else if(mask.type==='hue'){const [h]=rgbToHsl(r,g,b),target=mask.hue??0,tol=mask.tolerance??35,d=Math.min(Math.abs(h-target),360-Math.abs(h-target));v=clamp(1-d/Math.max(1,tol))}else if(mask.type==='depth'){const raw=rasterMask(mask,x,y);v=rangeBand(raw,mask.lo??.2,mask.hi??.8,mask.feather??.08)}else if(mask.type==='color'){const t=mask.target||[128,128,128],tol=mask.tolerance||80;v=clamp(1-Math.hypot(r-t[0],g-t[1],b-t[2])/tol)}else if(mask.type==='box'){const b0=mask.box||{xmin:0,ymin:0,xmax:1,ymax:1},fx=Math.min(x-b0.xmin,b0.xmax-x),fy=Math.min(y-b0.ymin,b0.ymax-y),edge=Math.min(fx,fy);v=x>=b0.xmin&&x<=b0.xmax&&y>=b0.ymin&&y<=b0.ymax?clamp(edge/Math.max(.001,mask.feather||.03)):0}else v=rasterMask(mask,x,y);if(mask.refine){const edge=(mask.refine.edge||0)/100,expand=(mask.refine.expand||0)/100,feather=Math.max(.02,(mask.refine.feather??0)/100);v=clamp((v-.5-expand*.35)*(1+edge*2)+.5);if(feather>0)v=clamp((v-(.5-feather))/(feather*2))}return clamp(v)}
function maskValue(mask,x,y,r,g,b,luma){if(mask.enabled===false)return 0;let v=primitiveMaskValue(mask,x,y,r,g,b,luma);for(const mod of mask.modifiers||[]){let mv=primitiveMaskValue(mod,x,y,r,g,b,luma);if(mod.invert)mv=1-mv;if(mod.operation==='subtract')v*=1-mv;else if(mod.operation==='intersect')v*=mv;else v=Math.max(v,mv)}if(mask.intersect){const iv=rangeBand(luma,mask.intersect.lo??.2,mask.intersect.hi??.8,mask.intersect.feather??.08);v*=iv}if(mask.invert)v=1-v;return clamp(v*(mask.density??1)*(mask.opacity??1))}
function isSkin(r,g,b){const mx=Math.max(r,g,b),mn=Math.min(r,g,b);return r>65&&g>28&&b>15&&mx-mn>10&&r>g*.94&&r>b*1.05}
function smartMaskRaster(data,w,h,type){const out=new Array(w*h).fill(0);let br=0,bg=0,bb=0,n=0;for(let y=0;y<h;y++)for(let x=0;x<w;x++){if(x<3||y<3||x>=w-3||y>=h-3){const i=(y*w+x)*4;br+=data[i];bg+=data[i+1];bb+=data[i+2];n++}}br/=n||1;bg/=n||1;bb/=n||1;
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2],yn=y/Math.max(1,h-1),xn=x/Math.max(1,w-1),center=clamp(1-Math.hypot(xn-.5,yn-.48)/.72),edgeDist=Math.hypot(r-br,g-bg,b-bb)/255,lum=(.2126*r+.7152*g+.0722*b)/255,sat=(Math.max(r,g,b)-Math.min(r,g,b))/255,skin=isSkin(r,g,b)?1:0;let v=0;
 if(type==='sky'){const blue=clamp((b-Math.max(r*.84,g*.79)+40)/110),top=clamp((.84-yn)/.58);v=top*(.25+.75*blue)}
 else if(type==='person'){v=clamp(skin*.8+center*.38)*clamp((1.02-yn)/.78)}
 else if(type==='subject'||type==='object'){v=clamp(edgeDist*1.85)*(.22+.78*center)}
 else if(type==='background'){v=1-clamp(edgeDist*1.85)*(.22+.78*center)}
 else if(type==='highlights'){v=clamp((lum-.52)/.38)}
 else if(type==='shadows'){v=clamp((.48-lum)/.38)}
 else if(type==='water'){const blue=clamp((b-r+30)/110),bottom=clamp((yn-.32)/.58);v=blue*bottom}
 else if(type==='vegetation'){v=clamp((g-Math.max(r*.9,b)+28)/100)}
 else if(type==='architecture'){const neutral=1-clamp((Math.max(r,g,b)-Math.min(r,g,b))/90);v=neutral*clamp(edgeDist*1.5)}
 else if(type==='ground'){v=clamp((yn-.48)/.42)*(1-clamp((b-r+30)/120)*.6)}
 else if(type==='artificialGround'){const neutral=1-clamp(sat/.5),lower=clamp((yn-.45)/.45);v=neutral*lower*clamp(edgeDist*1.25+.2)}
 else if(type==='snow'){const bright=clamp((lum-.58)/.35),neutral=1-clamp(sat/.28);v=bright*neutral}
 else if(type==='mountains'){const neutral=1-clamp(sat/.45),mid=clamp(1-Math.abs(yn-.43)/.34);v=neutral*mid*clamp(edgeDist*1.7)}
 else if(type==='skin'){v=skin*clamp(center*1.4)}
 else if(type==='face'){const region=clamp(1-Math.hypot((xn-.5)/.33,(yn-.34)/.27));v=clamp(skin*.8+region*.26)*region}
 else if(type==='hair'){const region=clamp(1-Math.hypot((xn-.5)/.38,(yn-.22)/.26)),dark=clamp((.58-lum)/.42);v=region*clamp(dark*.75+sat*.25)}
 else if(type==='eyes'){const yy=clamp(1-Math.abs(yn-.34)/.075),left=clamp(1-Math.abs(xn-.40)/.10),right=clamp(1-Math.abs(xn-.60)/.10),dark=clamp((.62-lum)/.45);v=yy*Math.max(left,right)*(.4+.6*dark)}
 else if(type==='teeth'){const region=clamp(1-Math.hypot((xn-.5)/.20,(yn-.51)/.10)),bright=clamp((lum-.48)/.38),neutral=1-clamp(sat/.35);v=region*bright*neutral}
 else if(type==='lips'){const region=clamp(1-Math.hypot((xn-.5)/.20,(yn-.50)/.10)),red=clamp((r-Math.max(g,b)+15)/80);v=region*red}
 else if(type==='clothing'||type==='clothes'){const lower=clamp((yn-.47)/.38),body=clamp(1-Math.abs(xn-.5)/.38);v=lower*body*(1-skin*.8)}
 out[y*w+x]=Math.round(clamp(v)*255)}return{w,h,data:out}}
function analyzePixels(data){let lsum=0,lsq=0,sat=0,n=0,hi=0,sh=0,rr=0,gg=0,bb=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2],l=(.2126*r+.7152*g+.0722*b)/255,mx=Math.max(r,g,b),mn=Math.min(r,g,b);lsum+=l;lsq+=l*l;sat+=(mx-mn)/255;rr+=r;gg+=g;bb+=b;n++;if(l>.92)hi++;if(l<.08)sh++}const mean=lsum/Math.max(1,n),sd=Math.sqrt(Math.max(0,lsq/Math.max(1,n)-mean*mean));return{mean,contrast:sd,saturation:sat/Math.max(1,n),highlights:hi/Math.max(1,n),shadows:sh/Math.max(1,n),r:rr/Math.max(1,n),g:gg/Math.max(1,n),b:bb/Math.max(1,n)}}
function autoEdits(stats){return{exposure:Math.round(clamp((.48-stats.mean)*120,-30,30)),contrast:Math.round(clamp((.20-stats.contrast)*90,-12,22)),highlights:stats.highlights>.04?-28:-10,shadows:stats.shadows>.08?28:12,whites:6,blacks:-6,vibrance:Math.round(clamp((.28-stats.saturation)*45,0,18)),saturation:0,clarity:5,dehaze:2}}
function matchLook(source,target){const lumDelta=(target.mean-source.mean)*105,satDelta=(target.saturation-source.saturation)*90;const warm=((target.r-target.b)-(source.r-source.b))/255*55;return{exposure:Math.round(clamp(lumDelta,-35,35)),contrast:Math.round(clamp((target.contrast-source.contrast)*120,-30,30)),vibrance:Math.round(clamp(satDelta,-30,30)),temp:Math.round(clamp(warm,-35,35)),tint:Math.round(clamp(((target.r+target.b)/2-target.g-((source.r+source.b)/2-source.g))/255*35,-25,25))}}
function applyLocalEdits(data,w,h,locals=[]){for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;let r=data[i],g=data[i+1],b=data[i+2],l=(.2126*r+.7152*g+.0722*b)/255;for(const mask of locals){const mv=maskValue(mask,x/Math.max(1,w-1),y/Math.max(1,h-1),r,g,b,l);if(mv<=.001)continue;const out=localAdjustPixel(r,g,b,mask.adjust,mv);r=out[0];g=out[1];b=out[2];l=(.2126*r+.7152*g+.0722*b)/255}data[i]=r;data[i+1]=g;data[i+2]=b}return data}
function boxBlur(data,w,h,radius=1){radius=Math.max(1,Math.min(8,Math.round(radius)));const out=new Uint8ClampedArray(data.length),tmp=new Uint8ClampedArray(data.length);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let rr=0,gg=0,bb=0,c=0;for(let dx=-radius;dx<=radius;dx++){const xx=Math.max(0,Math.min(w-1,x+dx)),i=(y*w+xx)*4;rr+=data[i];gg+=data[i+1];bb+=data[i+2];c++}const o=(y*w+x)*4;tmp[o]=rr/c;tmp[o+1]=gg/c;tmp[o+2]=bb/c;tmp[o+3]=data[o+3]}for(let y=0;y<h;y++)for(let x=0;x<w;x++){let rr=0,gg=0,bb=0,c=0;for(let dy=-radius;dy<=radius;dy++){const yy=Math.max(0,Math.min(h-1,y+dy)),i=(yy*w+x)*4;rr+=tmp[i];gg+=tmp[i+1];bb+=tmp[i+2];c++}const o=(y*w+x)*4;out[o]=rr/c;out[o+1]=gg/c;out[o+2]=bb/c;out[o+3]=tmp[o+3]}return out}
function chromaDenoise(data,w,h,strength){if(!strength)return new Uint8ClampedArray(data);const blur=boxBlur(data,w,h,1+strength/35),out=new Uint8ClampedArray(data),t=clamp(strength/120);for(let i=0;i<data.length;i+=4){const l=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2],bl=.2126*blur[i]+.7152*blur[i+1]+.0722*blur[i+2];out[i]=clamp255(l+(blur[i]-bl)*(1-t)+(data[i]-l)*(1-t));out[i+1]=clamp255(l+(blur[i+1]-bl)*(1-t)+(data[i+1]-l)*(1-t));out[i+2]=clamp255(l+(blur[i+2]-bl)*(1-t)+(data[i+2]-l)*(1-t))}return out}
function detailProcess(data,w,h,noise=0,sharp=0,e={}){let base=new Uint8ClampedArray(data);const lumNoise=Math.max(noise,e.luminanceNoise||0);if(lumNoise>0){const blur=boxBlur(base,w,h,lumNoise/25+1),t=clamp(lumNoise/125);for(let i=0;i<base.length;i+=4){const edge=Math.abs(base[i]-blur[i])+Math.abs(base[i+1]-blur[i+1])+Math.abs(base[i+2]-blur[i+2]),protect=clamp(edge/100),tt=t*(1-protect*.75);base[i]=mix(base[i],blur[i],tt);base[i+1]=mix(base[i+1],blur[i+1],tt);base[i+2]=mix(base[i+2],blur[i+2],tt)}}if(e.colorNoise>0)base=chromaDenoise(base,w,h,e.colorNoise);const sharpen=Math.max(sharp,e.deblur||0);if(sharpen>0){const blur=boxBlur(base,w,h,e.deblur>0?2:1),a=sharpen/100*(e.deblur>0?1.55:1.25);for(let i=0;i<base.length;i+=4){base[i]=clamp255(base[i]+(base[i]-blur[i])*a);base[i+1]=clamp255(base[i+1]+(base[i+1]-blur[i+1])*a);base[i+2]=clamp255(base[i+2]+(base[i+2]-blur[i+2])*a)}}if(e.artifactReduction>0){const smooth=boxBlur(base,w,h,1),t=e.artifactReduction/100*.28;for(let i=0;i<base.length;i+=4){base[i]=mix(base[i],smooth[i],t);base[i+1]=mix(base[i+1],smooth[i+1],t);base[i+2]=mix(base[i+2],smooth[i+2],t)}}return base}
function portraitProcess(data,w,h,e){if(!(e.skinSmooth||e.skinTone||e.shine||e.blemish||e.underEye||e.teeth||e.eyes||e.lips||e.hair||e.contour||e.faceLight||e.faceRestore))return data;const blurred=boxBlur(data,w,h,2),out=new Uint8ClampedArray(data);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,r=data[i],g=data[i+1],b=data[i+2],xn=x/w,yn=y/h,skin=isSkin(r,g,b),face=clamp(1-Math.hypot((xn-.5)/.35,(yn-.38)/.34));if(skin&&e.skinSmooth){const t=e.skinSmooth/100*.72*face;out[i]=mix(r,blurred[i],t);out[i+1]=mix(g,blurred[i+1],t);out[i+2]=mix(b,blurred[i+2],t)}if(skin&&e.skinTone){const avg=(out[i]+out[i+1]+out[i+2])/3,t=e.skinTone/100*.18;out[i]=mix(out[i],avg*1.06,t);out[i+1]=mix(out[i+1],avg,t);out[i+2]=mix(out[i+2],avg*.94,t)}if(skin&&e.shine){const l=(out[i]+out[i+1]+out[i+2])/765;if(l>.66){const t=e.shine/100*.35;out[i]=mix(out[i],blurred[i],t);out[i+1]=mix(out[i+1],blurred[i+1],t);out[i+2]=mix(out[i+2],blurred[i+2],t)}}if(e.faceLight&&face){const d=e.faceLight/100*28*face;out[i]=clamp255(out[i]+d);out[i+1]=clamp255(out[i+1]+d);out[i+2]=clamp255(out[i+2]+d)}const eyeBand=clamp(1-Math.abs(yn-.34)/.06)*Math.max(clamp(1-Math.abs(xn-.4)/.09),clamp(1-Math.abs(xn-.6)/.09));if(e.eyes&&eyeBand){const t=e.eyes/100*.3*eyeBand;out[i]=clamp255(out[i]*(1+t));out[i+1]=clamp255(out[i+1]*(1+t));out[i+2]=clamp255(out[i+2]*(1+t))}const mouth=clamp(1-Math.hypot((xn-.5)/.20,(yn-.52)/.08));if(e.teeth&&mouth&&r>150&&g>130&&b>110){const t=e.teeth/100*.45*mouth;out[i]=mix(out[i],245,t);out[i+1]=mix(out[i+1],245,t);out[i+2]=mix(out[i+2],240,t)}if(e.lips&&mouth&&r>g){const t=Math.abs(e.lips)/100*.35*mouth;out[i]=e.lips>0?clamp255(out[i]*(1+t)):mix(out[i],g,t);out[i+1]=e.lips>0?out[i+1]*(1-t*.18):out[i+1];}const hairRegion=clamp(1-Math.hypot((xn-.5)/.40,(yn-.20)/.24));if(e.hair&&hairRegion){const blur=blurred[i],a=e.hair/100*.55*hairRegion;out[i]=clamp255(out[i]+(out[i]-blur)*a);out[i+1]=clamp255(out[i+1]+(out[i+1]-blurred[i+1])*a);out[i+2]=clamp255(out[i+2]+(out[i+2]-blurred[i+2])*a)}if(e.contour&&face){const side=clamp(Math.abs(xn-.5)/.28),d=-e.contour/100*18*side*face;out[i]=clamp255(out[i]+d);out[i+1]=clamp255(out[i+1]+d);out[i+2]=clamp255(out[i+2]+d)}if(e.faceRestore&&face){const t=e.faceRestore/100*.48*face,detail=e.faceRestore/100*.18*face;for(let c=0;c<3;c++){const base=out[i+c],smooth=blurred[i+c];out[i+c]=clamp255(mix(base,smooth,t*.34)+(base-smooth)*detail+6*t)}}}return out}
function restoreProcess(data,w,h,e){let out=new Uint8ClampedArray(data);if(e.dustRemoval>0||e.blemish>0){const blur=boxBlur(out,w,h,1),strength=Math.max(e.dustRemoval||0,e.blemish||0)/100;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4,d=Math.abs(out[i]-blur[i])+Math.abs(out[i+1]-blur[i+1])+Math.abs(out[i+2]-blur[i+2]);if(d>110-strength*45){const t=clamp(strength*(d-80)/180);out[i]=mix(out[i],blur[i],t);out[i+1]=mix(out[i+1],blur[i+1],t);out[i+2]=mix(out[i+2],blur[i+2],t)}}}if(e.lineRemoval>0){const src=new Uint8ClampedArray(out),t=e.lineRemoval/100*.7;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4;for(let c=0;c<3;c++){const hAvg=(src[i-4+c]+src[i+4+c])/2,vAvg=(src[i-w*4+c]+src[i+w*4+c])/2,dH=Math.abs(src[i+c]-hAvg),dV=Math.abs(src[i+c]-vAvg);if(Math.max(dH,dV)>60)out[i+c]=mix(src[i+c],dH>dV?hAvg:vAvg,t)}}}return out}
function relightProcess(data,w,h,e,depth){if(!(e.relightForeground||e.relightBackground||e.rimLight||e.relightWarmth))return data;const out=new Uint8ClampedArray(data),fg=e.relightForeground/100,bg=e.relightBackground/100,dir=(e.relightDirection??50)/100,warm=e.relightWarmth/100,soft=(e.relightSoftness??50)/100,rim=e.rimLight/100;for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4;let d=y/Math.max(1,h-1);if(depth?.data){const dx=Math.min(depth.w-1,Math.round(x/Math.max(1,w-1)*(depth.w-1))),dy=Math.min(depth.h-1,Math.round(y/Math.max(1,h-1)*(depth.h-1)));d=(depth.data[dy*depth.w+dx]||0)/255}const front=d,background=1-d,delta=(fg*front+bg*background)*45,directional=(x/Math.max(1,w-1)-dir),fall=1-clamp(Math.abs(directional)/(soft*.8+.18)),light=delta*(.65+.35*fall)+rim*28*clamp(Math.abs(d-.5)*2);out[i]=clamp255(out[i]+light+warm*10);out[i+1]=clamp255(out[i+1]+light+warm*2);out[i+2]=clamp255(out[i+2]+light-warm*10)}return out}
function inpaint(data,w,h,mask,iterations=10){const out=new Uint8ClampedArray(data),mark=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,l=(out[i]+out[i+1]+out[i+2])/765;if(maskValue(mask,x/Math.max(1,w-1),y/Math.max(1,h-1),out[i],out[i+1],out[i+2],l)>.2)mark[y*w+x]=1}for(let pass=0;pass<iterations;pass++){const src=new Uint8ClampedArray(out),next=new Uint8Array(mark),rad=Math.min(7,2+pass);for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const idx=y*w+x;if(!mark[idx])continue;let rr=0,gg=0,bbv=0,ws=0;for(let yy=-rad;yy<=rad;yy++)for(let xx=-rad;xx<=rad;xx++){const nx=x+xx,ny=y+yy;if(nx<0||ny<0||nx>=w||ny>=h)continue;const ni=ny*w+nx;if(mark[ni])continue;const p=ni*4,wt=1/(1+Math.hypot(xx,yy));rr+=src[p]*wt;gg+=src[p+1]*wt;bbv+=src[p+2]*wt;ws+=wt}if(ws){const p=idx*4;out[p]=rr/ws;out[p+1]=gg/ws;out[p+2]=bbv/ws;out[p+3]=255;next[idx]=0}}mark.set(next);if(!mark.some(Boolean))break}return out}
function clonePaint(data,w,h,mask,dx=-.12,dy=-.12){const src=new Uint8ClampedArray(data),out=new Uint8ClampedArray(data);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,l=(src[i]+src[i+1]+src[i+2])/765,mv=maskValue(mask,x/Math.max(1,w-1),y/Math.max(1,h-1),src[i],src[i+1],src[i+2],l);if(mv<=.001)continue;const sx=Math.max(0,Math.min(w-1,Math.round(x+dx*w))),sy=Math.max(0,Math.min(h-1,Math.round(y+dy*h))),si=(sy*w+sx)*4;for(let c=0;c<3;c++)out[i+c]=mix(out[i+c],src[si+c],mv)}return out}
function promptColor(prompt=''){const p=prompt.toLowerCase(),m={red:[210,70,60],orange:[220,125,45],yellow:[225,205,70],green:[70,150,85],blue:[65,110,205],purple:[125,85,180],pink:[220,120,165],white:[235,235,235],black:[25,25,25],gray:[125,125,125],grey:[125,125,125],brown:[115,75,48]};for(const [k,v] of Object.entries(m))if(p.includes(k))return v;return null}
function generativeFill(data,w,h,mask,prompt=''){const color=promptColor(prompt);if(!color)return inpaint(data,w,h,mask,14);const out=new Uint8ClampedArray(data);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*4,l=(out[i]+out[i+1]+out[i+2])/765,mv=maskValue(mask,x/Math.max(1,w-1),y/Math.max(1,h-1),out[i],out[i+1],out[i+2],l);if(mv<=.001)continue;const noise=(Math.sin(x*12.9898+y*78.233)*43758.5453)%1;for(let c=0;c<3;c++)out[i+c]=mix(out[i+c],clamp255(color[c]+noise*8),mv*.9)}return out}

function blendMode(base,top,mode='normal'){const b=base/255,t=top/255;let v=t;if(mode==='multiply')v=b*t;else if(mode==='screen')v=1-(1-b)*(1-t);else if(mode==='overlay')v=b<.5?2*b*t:1-2*(1-b)*(1-t);else if(mode==='softlight')v=(1-2*t)*b*b+2*t*b;return clamp255(v*255)}
function applyAdjustmentLayers(data,w,h,layers=[]){let out=new Uint8ClampedArray(data);for(const layer of layers||[]){if(layer.enabled===false)continue;const opacity=clamp(layer.opacity??1),mode=layer.blend||'normal';for(let i=0;i<out.length;i+=4){const p=applyTonePixel(out[i],out[i+1],out[i+2],layer.edits||{});for(let c=0;c<3;c++)out[i+c]=mix(out[i+c],blendMode(out[i+c],p[c],mode),opacity)}}return out}
function applyLUT(data,lut,intensity=1){if(!lut?.size||!lut?.data?.length||!intensity)return new Uint8ClampedArray(data);const size=lut.size,table=lut.data,out=new Uint8ClampedArray(data),at=(r,g,b,c)=>table[((b*size+g)*size+r)*3+c]??0;for(let i=0;i<data.length;i+=4){const rf=data[i]/255*(size-1),gf=data[i+1]/255*(size-1),bf=data[i+2]/255*(size-1),r0=Math.floor(rf),g0=Math.floor(gf),b0=Math.floor(bf),r1=Math.min(size-1,r0+1),g1=Math.min(size-1,g0+1),b1=Math.min(size-1,b0+1),tr=rf-r0,tg=gf-g0,tb=bf-b0;for(let c=0;c<3;c++){const c000=at(r0,g0,b0,c),c100=at(r1,g0,b0,c),c010=at(r0,g1,b0,c),c110=at(r1,g1,b0,c),c001=at(r0,g0,b1,c),c101=at(r1,g0,b1,c),c011=at(r0,g1,b1,c),c111=at(r1,g1,b1,c),c00=mix(c000,c100,tr),c10=mix(c010,c110,tr),c01=mix(c001,c101,tr),c11=mix(c011,c111,tr),c0=mix(c00,c10,tg),c1=mix(c01,c11,tg),v=mix(c0,c1,tb)*255;out[i+c]=mix(data[i+c],v,clamp(intensity))}out[i+3]=data[i+3]}return out}
function qualityMetrics(data,w,h){let edge=0,edgeSq=0,n=0,hi=0,sh=0,sat=0;const lum=(x,y)=>{const i=(y*w+x)*4;return .2126*data[i]+.7152*data[i+1]+.0722*data[i+2]};for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=(y*w+x)*4,l=lum(x,y),lap=4*l-lum(x-1,y)-lum(x+1,y)-lum(x,y-1)-lum(x,y+1);edge+=lap;edgeSq+=lap*lap;n++;if(l>247)hi++;if(l<8)sh++;sat+=(Math.max(data[i],data[i+1],data[i+2])-Math.min(data[i],data[i+1],data[i+2]))/255}const variance=Math.max(0,edgeSq/Math.max(1,n)-(edge/Math.max(1,n))**2);return{sharpness:Math.round(clamp(Math.sqrt(variance)/45)*100),highlights:hi/Math.max(1,n),shadows:sh/Math.max(1,n),colorfulness:sat/Math.max(1,n)}}
function redEyeProcess(data,w,h,strength=0){if(!strength)return new Uint8ClampedArray(data);const out=new Uint8ClampedArray(data),t=clamp(strength/100);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const xn=x/Math.max(1,w-1),yn=y/Math.max(1,h-1),eyeBand=clamp(1-Math.abs(yn-.34)/.075)*Math.max(clamp(1-Math.abs(xn-.4)/.10),clamp(1-Math.abs(xn-.6)/.10));if(!eyeBand)continue;const i=(y*w+x)*4,r=out[i],g=out[i+1],b=out[i+2];if(r>g*1.28&&r>b*1.22){const target=(g+b)/2,amt=t*eyeBand;out[i]=mix(r,target,amt);out[i+1]=mix(g,Math.max(g,target*.9),amt*.2);out[i+2]=mix(b,Math.max(b,target*.9),amt*.2)}}return out}
function frequencyProcess(data,w,h,smooth=0,detail=0){if(!smooth&&!detail)return new Uint8ClampedArray(data);const low=boxBlur(data,w,h,Math.max(1,Math.round(1+smooth/22))),out=new Uint8ClampedArray(data),st=clamp(smooth/100)*.72,dt=detail/100*1.4;for(let i=0;i<out.length;i+=4)for(let c=0;c<3;c++){const high=data[i+c]-low[i+c];out[i+c]=clamp255(mix(data[i+c],low[i+c],st)+high*dt)}return out}
function mergeAverage(images){if(!images?.length)return null;const len=images[0].length,out=new Uint8ClampedArray(len);for(let i=0;i<len;i+=4){let r=0,g=0,b=0,a=0;for(const d of images){r+=d[i];g+=d[i+1];b+=d[i+2];a+=d[i+3]}out[i]=r/images.length;out[i+1]=g/images.length;out[i+2]=b/images.length;out[i+3]=a/images.length}return out}
function mergeHDR(images){if(!images?.length)return null;const len=images[0].length,out=new Uint8ClampedArray(len);for(let i=0;i<len;i+=4){let rr=0,gg=0,bb=0,ws=0;for(const d of images){const l=(.2126*d[i]+.7152*d[i+1]+.0722*d[i+2])/255,wt=.08+Math.exp(-((l-.5)*(l-.5))/.075);rr+=d[i]*wt;gg+=d[i+1]*wt;bb+=d[i+2]*wt;ws+=wt}out[i]=rr/ws;out[i+1]=gg/ws;out[i+2]=bb/ws;out[i+3]=255}return out}
function mergeFocus(images,w,h){if(!images?.length)return null;const out=new Uint8ClampedArray(images[0]),luma=(d,x,y)=>{const i=(y*w+x)*4;return .2126*d[i]+.7152*d[i+1]+.0722*d[i+2]};for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){let best=0,bestScore=-1;for(let j=0;j<images.length;j++){const d=images[j],l=luma(d,x,y),score=Math.abs(4*l-luma(d,x-1,y)-luma(d,x+1,y)-luma(d,x,y-1)-luma(d,x,y+1));if(score>bestScore){bestScore=score;best=j}}const i=(y*w+x)*4,d=images[best];out[i]=d[i];out[i+1]=d[i+1];out[i+2]=d[i+2];out[i+3]=255}return out}


function encodeTIFF(data,w,h){const entries=10,ifdOffset=8,ifdSize=2+entries*12+4,bitsOffset=ifdOffset+ifdSize,pixelOffset=(bitsOffset+6+1)&~1,pixelBytes=w*h*3,buf=new ArrayBuffer(pixelOffset+pixelBytes),v=new DataView(buf);v.setUint8(0,0x49);v.setUint8(1,0x49);v.setUint16(2,42,true);v.setUint32(4,ifdOffset,true);v.setUint16(ifdOffset,entries,true);let at=ifdOffset+2;const entry=(tag,type,count,value)=>{v.setUint16(at,tag,true);v.setUint16(at+2,type,true);v.setUint32(at+4,count,true);if(type===3&&count===1){v.setUint16(at+8,value,true);v.setUint16(at+10,0,true)}else v.setUint32(at+8,value,true);at+=12};entry(256,4,1,w);entry(257,4,1,h);entry(258,3,3,bitsOffset);entry(259,3,1,1);entry(262,3,1,2);entry(273,4,1,pixelOffset);entry(277,3,1,3);entry(278,4,1,h);entry(279,4,1,pixelBytes);entry(284,3,1,1);v.setUint32(at,0,true);v.setUint16(bitsOffset,8,true);v.setUint16(bitsOffset+2,8,true);v.setUint16(bitsOffset+4,8,true);const out=new Uint8Array(buf);let p=pixelOffset;for(let i=0;i<data.length;i+=4){out[p++]=data[i];out[p++]=data[i+1];out[p++]=data[i+2]}return out}
function histogram(data,bins=64){const out={r:new Array(bins).fill(0),g:new Array(bins).fill(0),b:new Array(bins).fill(0),l:new Array(bins).fill(0)};for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2],l=.2126*r+.7152*g+.0722*b;out.r[Math.min(bins-1,r*bins>>8)]++;out.g[Math.min(bins-1,g*bins>>8)]++;out.b[Math.min(bins-1,b*bins>>8)]++;out.l[Math.min(bins-1,l*bins>>8)]++}return out}
root.DarkRoomEngine={clamp,mix,curveValue,rgbToHsl,hslToRgb,applyTonePixel,localAdjustPixel,maskValue,smartMaskRaster,analyzePixels,autoEdits,matchLook,applyLocalEdits,applyAdjustmentLayers,applyLUT,qualityMetrics,redEyeProcess,frequencyProcess,mergeAverage,mergeHDR,mergeFocus,encodeTIFF,boxBlur,chromaDenoise,detailProcess,portraitProcess,restoreProcess,relightProcess,inpaint,clonePaint,generativeFill,histogram};
})(typeof globalThis!=='undefined'?globalThis:this);
