/* Optional high-quality local inpainting backend.
 * Moebius-compatible ONNX orchestration, written for DarkRoom's local-first workflow.
 * Model weights are downloaded from Hugging Face once and cached in Cache Storage.
 */
const DarkRoomGenerative=(()=>{
 const IMG=512,LAT=64,SCALE=.13025,NOISE_OFFSET=.0357,HALF_IDS=10;
 const MODEL_BASE='https://huggingface.co/simonw/Moebius-ONNX/resolve/main';
 const CACHE='darkroom-moebius-v1';
 let ortPromise=null,pipelinePromise=null,lastError='',progressState={stage:'idle',loaded:0,total:0};
 const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
 function status(){return{available:!!navigator.gpu,loaded:!!pipelinePromise,progress:{...progressState},lastError,modelBase:MODEL_BASE}}
 async function ort(){if(!ortPromise)ortPromise=import('https://cdn.jsdelivr.net/npm/onnxruntime-web@1.27.0/dist/ort.webgpu.bundle.min.mjs');return ortPromise}
 async function persistent(){try{if(await navigator.storage?.persisted?.())return true;return await navigator.storage?.persist?.()||false}catch{return false}}
 async function modelBytes(name,onProgress){const url=`${MODEL_BASE}/${name}`;let cache=null;try{cache=await caches.open(CACHE);const hit=await cache.match(url);if(hit){const b=await hit.arrayBuffer();onProgress?.(b.byteLength,b.byteLength,true);return new Uint8Array(b)}}catch{}const r=await fetch(url);if(!r.ok)throw new Error(`${name}: HTTP ${r.status}`);const total=+(r.headers.get('content-length')||0),reader=r.body?.getReader();let bytes;if(reader&&total){bytes=new Uint8Array(total);let at=0;for(;;){const{done,value}=await reader.read();if(done)break;bytes.set(value,at);at+=value.length;onProgress?.(at,total,false)}}else{bytes=new Uint8Array(await r.arrayBuffer());onProgress?.(bytes.length,bytes.length,false)}if(cache)try{await cache.put(url,new Response(bytes.slice().buffer,{headers:{'content-type':'application/octet-stream','content-length':String(bytes.length)}}))}catch{}return bytes}
 function makeDDIM(steps=20){const betas=new Float64Array(1000),a=Math.sqrt(.00085),b=Math.sqrt(.012);for(let i=0;i<1000;i++){const q=a+(b-a)*(i/999);betas[i]=q*q}const ac=new Float64Array(1000);let acc=1;for(let i=0;i<1000;i++){acc*=1-betas[i];ac[i]=acc}const ratio=Math.floor(1000/steps),ts=[];for(let i=0;i<steps;i++)ts.push(Math.round(i*ratio));ts.reverse();return{ac,timesteps:ts.slice(Math.max(steps-Math.min(Math.floor(steps*.99),steps),0))}}
 function ddimStep(eps,sample,t,prev,ddim){const at=ddim.ac[t],ap=prev>=0?ddim.ac[prev]:1,sa=Math.sqrt(at),sb=Math.sqrt(1-at),spa=Math.sqrt(ap),spb=Math.sqrt(1-ap),out=new Float32Array(sample.length);for(let i=0;i<out.length;i++){const x0=(sample[i]-sb*eps[i])/sa;out[i]=spa*x0+spb*eps[i]}return out}
 function rng(seed){let s=seed>>>0;return()=>{s|=0;s=s+0x6d2b79f5|0;let t=Math.imul(s^s>>>15,1|s);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
 function randn(n,seed){const r=rng(seed),o=new Float32Array(n);for(let i=0;i<n;i++){let u=0,v=0;while(!u)u=r();while(!v)v=r();o[i]=Math.sqrt(-2*Math.log(u))*Math.cos(2*Math.PI*v)}return o}
 function fittedCanvas(src,w,h){const c=document.createElement('canvas');c.width=c.height=IMG;const x=c.getContext('2d');x.fillStyle='#000';x.fillRect(0,0,IMG,IMG);const sc=Math.min(IMG/w,IMG/h),dw=Math.round(w*sc),dh=Math.round(h*sc),dx=Math.floor((IMG-dw)/2),dy=Math.floor((IMG-dh)/2);x.imageSmoothingQuality='high';x.drawImage(src,dx,dy,dw,dh);return{canvas:c,rect:{x:dx,y:dy,w:dw,h:dh}}}
 function chw(c){const d=c.getContext('2d').getImageData(0,0,IMG,IMG).data,o=new Float32Array(3*IMG*IMG),p=IMG*IMG;for(let i=0;i<p;i++){o[i]=d[i*4]/127.5-1;o[p+i]=d[i*4+1]/127.5-1;o[2*p+i]=d[i*4+2]/127.5-1}return o}
 function maskCanvas(mask,rect){const c=document.createElement('canvas');c.width=c.height=IMG;const x=c.getContext('2d');x.fillStyle='#fff';for(const stroke of mask.strokes||[]){const rad=(stroke.size||mask.size||.08)*Math.min(rect.w,rect.h)/2;x.globalAlpha=Math.min(1,Math.abs(stroke.flow??mask.flow??1));x.lineCap=x.lineJoin='round';x.strokeStyle='#fff';x.fillStyle='#fff';x.lineWidth=Math.max(2,rad*2);const pts=stroke.points||[];if(!pts.length)continue;x.beginPath();for(let i=0;i<pts.length;i++){const px=rect.x+pts[i].x*rect.w,py=rect.y+pts[i].y*rect.h;i?x.lineTo(px,py):x.moveTo(px,py)}pts.length===1?x.arc(rect.x+pts[0].x*rect.w,rect.y+pts[0].y*rect.h,rad,0,Math.PI*2):x.stroke();if(pts.length===1)x.fill()}x.globalAlpha=1;return c}
 function maskBinary(c){const d=c.getContext('2d').getImageData(0,0,IMG,IMG).data,o=new Float32Array(IMG*IMG);for(let i=0;i<o.length;i++)o[i]=d[i*4+3]>=64?1:0;return o}
 function maskedCHW(image,mask){const o=new Float32Array(image.length),p=IMG*IMG;for(let c=0;c<3;c++)for(let i=0;i<p;i++)o[c*p+i]=image[c*p+i]*(1-mask[i]);return o}
 function maskLatent(mask){const o=new Float32Array(LAT*LAT);for(let y=0;y<LAT;y++)for(let x=0;x<LAT;x++)o[y*LAT+x]=mask[(y*8)*IMG+x*8];return o}
 function decodedImage(ch){const out=new ImageData(IMG,IMG),p=IMG*IMG;for(let i=0;i<p;i++){for(let c=0;c<3;c++)out.data[i*4+c]=Math.round(clamp((ch[c*p+i]+1)/2)*255);out.data[i*4+3]=255}return out}
 function paste(result,orig,mask){const mc=document.createElement('canvas');mc.width=mc.height=IMG;const md=new ImageData(IMG,IMG);for(let i=0;i<mask.length;i++){const v=mask[i]*255;md.data[i*4]=md.data[i*4+1]=md.data[i*4+2]=v;md.data[i*4+3]=255}mc.getContext('2d').putImageData(md,0,0);const blur=document.createElement('canvas');blur.width=blur.height=IMG;const bx=blur.getContext('2d');bx.filter='blur(3px)';bx.drawImage(mc,0,0);const bm=bx.getImageData(0,0,IMG,IMG).data,od=orig.getContext('2d').getImageData(0,0,IMG,IMG).data,out=new ImageData(IMG,IMG);for(let i=0;i<mask.length;i++){const m=bm[i*4]/255;for(let c=0;c<3;c++)out.data[i*4+c]=Math.round(result.data[i*4+c]*m+od[i*4+c]*(1-m));out.data[i*4+3]=255}const c=document.createElement('canvas');c.width=c.height=IMG;c.getContext('2d').putImageData(out,0,0);return c}
 class Pipeline{async load(onProgress){if(!navigator.gpu)throw new Error('High Quality Local AI requires WebGPU');const O=await ort(),opts={executionProviders:['webgpu'],graphOptimizationLevel:'all'};await persistent();const load=async(name,label,idx)=>{progressState={stage:`${label} ${idx}/3`,loaded:0,total:0};return modelBytes(name,(l,t,cached)=>{progressState={stage:cached?`${label} cached`:`Downloading ${label}`,loaded:l,total:t};onProgress?.(progressState)})};this.enc=await O.InferenceSession.create(await load('vae_encoder.onnx','VAE encoder',1),opts);this.dec=await O.InferenceSession.create(await load('vae_decoder.onnx','VAE decoder',2),opts);this.unet=await O.InferenceSession.create(await load('unet.onnx','UNet',3),opts);this.O=O;progressState={stage:'ready',loaded:1,total:1}}
  async encode(a){const O=this.O,r=await this.enc.run({image:new O.Tensor('float32',a,[1,3,IMG,IMG])}),m=r.moments.data,o=new Float32Array(4*LAT*LAT);for(let i=0;i<o.length;i++)o[i]=m[i]*SCALE;return o}
  async decode(a){const O=this.O,s=new Float32Array(a.length);for(let i=0;i<a.length;i++)s[i]=a[i]/SCALE;const r=await this.dec.run({latent:new O.Tensor('float32',s,[1,4,LAT,LAT])});return decodedImage(r.image.data)}
  async cfg(lat,mask,masked,t,g){const O=this.O,p=LAT*LAT,nine=new Float32Array(9*p);nine.set(lat,0);nine.set(mask,4*p);nine.set(masked,5*p);const two=new Float32Array(18*p);two.set(nine);two.set(nine,9*p);const ids=new BigInt64Array(20);for(let i=0;i<10;i++){ids[i]=BigInt(10+i);ids[10+i]=BigInt(i)}const r=await this.unet.run({latent:new O.Tensor('float32',two,[2,9,LAT,LAT]),timesteps:new O.Tensor('int64',new BigInt64Array([BigInt(t),BigInt(t)]),[2]),input_ids:new O.Tensor('int64',ids,[2,10])}),noise=r.noise.data,n=4*p,o=new Float32Array(n);for(let i=0;i<n;i++)o[i]=noise[i]+g*(noise[n+i]-noise[i]);return o}
  async run(image,mask,{steps=20,guidance=2,seed=42,onProgress}={}){const imageA=chw(image),maskB=maskBinary(mask),masked=await this.encode(maskedCHW(imageA,maskB)),m64=maskLatent(maskB),dd=makeDDIM(steps),p=LAT*LAT;let lat=randn(4*p,seed),off=randn(4,seed^0x9e3779b9);for(let c=0;c<4;c++)for(let i=0;i<p;i++)lat[c*p+i]+=NOISE_OFFSET*off[c];for(let i=0;i<dd.timesteps.length;i++){onProgress?.({stage:'Denoising',loaded:i+1,total:dd.timesteps.length});const t=dd.timesteps[i],prev=i+1<dd.timesteps.length?dd.timesteps[i+1]:-1,eps=await this.cfg(lat,m64,masked,t,guidance);lat=ddimStep(eps,lat,t,prev,dd);await new Promise(r=>setTimeout(r,0))}onProgress?.({stage:'Decoding',loaded:0,total:1});return paste(await this.decode(lat),image,maskB)} }
 async function pipeline(onProgress){if(!pipelinePromise)pipelinePromise=(async()=>{const p=new Pipeline();await p.load(onProgress);return p})().catch(e=>{pipelinePromise=null;lastError=e.message;throw e});return pipelinePromise}
 async function inpaint(blob,mask,{steps=20,guidance=2,seed=42,onProgress}={}){if(!navigator.gpu)throw new Error('WebGPU unavailable');const bmp=await createImageBitmap(blob),ow=bmp.width,oh=bmp.height,fit=fittedCanvas(bmp,ow,oh);bmp.close?.();const mc=maskCanvas(mask,fit.rect),p=await pipeline(onProgress),sq=await p.run(fit.canvas,mc,{steps,guidance,seed,onProgress}),out=document.createElement('canvas');out.width=fit.rect.w;out.height=fit.rect.h;out.getContext('2d').drawImage(sq,fit.rect.x,fit.rect.y,fit.rect.w,fit.rect.h,0,0,out.width,out.height);const final=document.createElement('canvas');final.width=ow;final.height=oh;final.getContext('2d').drawImage(out,0,0,final.width,final.height);const result=await new Promise((res,rej)=>final.toBlob(b=>b?res(b):rej(new Error('Could not encode AI result')),'image/png'));return result}
 async function clearCache(){try{await caches.delete(CACHE)}catch{}pipelinePromise=null}
 return{inpaint,status,clearCache,makeDDIM,ddimStep};
})();
