function filteredPhotos(){let list=[...photos];if(currentRoute==='favorites')list=list.filter(p=>p.favorite);if(currentRoute==='recent')list=list.filter(p=>Date.now()-p.created<7*864e5);if(currentRoute==='flagged')list=list.filter(p=>p.flag==='picked');if(currentRoute==='album')list=list.filter(p=>p.albumIds?.includes(currentAlbumId));if(activeFilter==='picked')list=list.filter(p=>p.flag==='picked');else if(activeFilter==='rejected')list=list.filter(p=>p.flag==='rejected');else if(/^\d$/.test(activeFilter))list=list.filter(p=>p.rating>=+activeFilter);else if(activeFilter.startsWith('color-'))list=list.filter(p=>p.colorLabel===activeFilter.slice(6));const q=$('#searchInput').value.trim().toLowerCase();if(q)list=list.filter(p=>`${p.name} ${(p.albumIds||[]).map(id=>albums.find(a=>a.id===id)?.name||'').join(' ')} ${new Date(p.created).toLocaleDateString()} ${p.favorite?'favorite':''} ${p.flag} ${p.colorLabel}`.toLowerCase().includes(q));const s=$('#sortSelect').value;list.sort(s==='old'?(a,b)=>a.created-b.created:s==='name'?(a,b)=>a.name.localeCompare(b.name):s==='rating'?(a,b)=>b.rating-a.rating:(a,b)=>b.created-a.created);return list}
function syncBatchPresetOptions(){const el=$('#batchPreset');if(!el)return;const current=el.value;el.innerHTML='<option value="">Preset…</option>'+Object.keys(typeof allPresets==='function'?allPresets():presets).map(n=>`<option value="${esc(n)}">${esc(n)}</option>`).join('');el.value=current}function render(){renderPhotos();renderAlbums();renderSidebarAlbums();syncBatchPresetOptions();$('#allCount').textContent=photos.length;$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===currentRoute||(currentRoute==='album'&&b.dataset.route==='albums')));updateBatchBar()}
function renderPhotos(){const g=$('#photoGrid'),empty=$('#emptyState'),list=filteredPhotos();let title='All Photos',sub='Photos stored on this device.',eyebrow='LIBRARY';if(currentRoute==='recent'){title='Recently Added';sub='Photos imported in the last 7 days.'}if(currentRoute==='favorites'){title='Favorites';sub='Photos you marked as favorites.'}if(currentRoute==='flagged'){title='Picked';sub='Photos flagged as picks.'}if(currentRoute==='album'){const a=albums.find(x=>x.id===currentAlbumId);title=a?.name||'Album';sub=`${list.length} photo${list.length===1?'':'s'} · stored locally`;eyebrow='ALBUM'}$('#viewTitle').textContent=title;$('#viewSubtitle').textContent=sub;$('#viewEyebrow').textContent=eyebrow;$('#albumActions').hidden=currentRoute!=='album';empty.style.display=list.length?'none':'flex';g.style.display=list.length?'grid':'none';g.innerHTML=list.map(p=>`<article class="photo-card ${p.rating||p.favorite||p.flag!=='none'?'has-meta':''} ${selectionMode?'selection-mode':''} ${selectedPhotoIds.has(p.id)?'selected':''}" data-photo="${p.id}" tabindex="0"><img src="${blobUrl(p,true)}" alt="${esc(p.name)}" loading="lazy">${p.colorLabel&&p.colorLabel!=='none'?`<i class="color-label-dot ${p.colorLabel}"></i>`:''}<div class="photo-overlay"><span>${p.flag==='picked'?'<b class="flag-picked">⚑</b>':p.flag==='rejected'?'<b class="flag-rejected">⚑</b>':''} ${p.rating?'★'.repeat(p.rating):''}</span><span>${p.favorite?'♥':''}</span></div>${p.analysis?`<span class="quality-badge" title="${qualityLabel(p)}">F${p.analysis.sharpness}</span>`:''}${selectionMode?'<span class="selection-hint">Select</span>':''}</article>`).join('');$$('.photo-card').forEach(c=>{c.onclick=()=>selectionMode?togglePhotoSelection(c.dataset.photo):openEditor(c.dataset.photo);c.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();c.click()}}});if(innerWidth>760)g.style.gridTemplateColumns=`repeat(${gridMode},minmax(0,1fr))`}
function albumPhotos(id){return photos.filter(p=>p.albumIds?.includes(id))}
function renderAlbums(){const ag=$('#albumGrid');if(!albums.length){ag.innerHTML='<div class="info-card"><b>No albums yet</b><p>Create an album to group photos without duplicating files.</p></div>';return}ag.innerHTML=albums.map(a=>{const ps=albumPhotos(a.id);return `<article class="album-card" data-album="${a.id}"><div class="album-cover">${ps.slice(0,4).map(p=>`<img src="${blobUrl(p,true)}" alt="">`).join('')||'<div class="album-empty">▱</div>'}</div><h3>${esc(a.name)}</h3><small>${ps.length} photos</small></article>`}).join('');$$('.album-card').forEach(c=>c.onclick=()=>openAlbum(c.dataset.album))}
function renderSidebarAlbums(){const s=$('#sidebarAlbums');s.innerHTML=albums.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(a=>`<button class="sidebar-album ${currentRoute==='album'&&currentAlbumId===a.id?'active':''}" data-side-album="${a.id}">${esc(a.name)}</button>`).join('');$$('[data-side-album]').forEach(b=>b.onclick=()=>openAlbum(b.dataset.sideAlbum))}
function openAlbum(id){currentAlbumId=id;route('album')}
function setSelectionMode(on){selectionMode=on;selectedPhotoIds.clear();$('#selectPhotosBtn').classList.toggle('active',on);renderPhotos();updateBatchBar()}
function togglePhotoSelection(id){selectedPhotoIds.has(id)?selectedPhotoIds.delete(id):selectedPhotoIds.add(id);renderPhotos();updateBatchBar()}
function selectedPhotos(){return photos.filter(p=>selectedPhotoIds.has(p.id))}
function updateBatchBar(){const bar=$('#batchBar');if(!bar)return;bar.classList.toggle('hidden',!selectionMode);$('#batchCount').textContent=`${selectedPhotoIds.size} selected`;['batchFavorite','batchPick','batchReject','batchRating','batchColor','batchPreset','batchAuto','batchPaste','batchAlbum','batchAnalyze','batchCompare','batchRename','batchCombine','batchExport'].forEach(id=>$('#'+id).disabled=!selectedPhotoIds.size)}
async function batchMutate(fn,msg){const list=selectedPhotos();for(const p of list){fn(p);await put('photos',p)}await refreshData();selectedPhotoIds=new Set(list.map(p=>p.id));renderPhotos();updateBatchBar();toast(msg)}
async function batchFavorite(){await batchMutate(p=>p.favorite=true,'Favorites updated')}
async function batchPick(){await batchMutate(p=>p.flag='picked','Photos picked')}
async function batchReject(){await batchMutate(p=>p.flag='rejected','Photos rejected')}
function batchSelectAll(){for(const p of filteredPhotos())selectedPhotoIds.add(p.id);renderPhotos();updateBatchBar()}
async function batchRate(v){if(v==='')return;await batchMutate(p=>p.rating=+v,'Ratings updated')}
async function batchColor(v){if(v==='')return;await batchMutate(p=>p.colorLabel=v,'Color labels updated')}
async function batchAuto(){const list=selectedPhotos();if(!list.length)return;toast(`Auto-enhancing ${list.length} photos…`);for(const p of list){const stats=await statsForPhoto(p),auto=DarkRoomEngine.autoEdits(stats);p.edits={...defaultEdits(),...(p.edits||{}),...auto};await put('photos',p)}await refreshData();selectedPhotoIds=new Set(list.map(p=>p.id));renderPhotos();updateBatchBar();toast('Auto Enhance applied')}
async function batchApplyPreset(name){if(!name)return;const preset=(typeof allPresets==='function'?allPresets():presets)[name];if(!preset)return;await batchMutate(p=>p.edits={...defaultEdits(),...(p.edits||{}),...preset},`${name} applied`)}
async function batchPaste(){if(!editClipboard)return toast('Copy edits from a photo first');await batchMutate(p=>{p.edits={...defaultEdits(),...clone(editClipboard.edits||editClipboard)};p.adjustmentLayers=clone(editClipboard.adjustmentLayers||[]);p.imageLayers=clone(editClipboard.imageLayers||[]);p.lut=clone(editClipboard.lut||null);p.skyReplacementId=editClipboard.skyReplacementId||null;p.localEdits=clone(editClipboard.localEdits||[]);p.healOps=clone(editClipboard.healOps||[])},'Edits, masks and removals synced')}
function showBatchAlbum(){const b=$('#batchAlbumBackdrop'),list=$('#batchAlbumList');list.innerHTML=albums.length?albums.map(a=>`<button class="action-wide" data-batch-album-id="${a.id}">${esc(a.name)}</button>`).join(''):'<p>Create an album first.</p>';b.classList.remove('hidden');$$('[data-batch-album-id]').forEach(x=>x.onclick=()=>batchAddAlbum(x.dataset.batchAlbumId))}
async function batchAddAlbum(id){await batchMutate(p=>{const s=new Set(p.albumIds||[]);s.add(id);p.albumIds=[...s]},'Added to album');$('#batchAlbumBackdrop').classList.add('hidden')}
async function batchExport(){const list=selectedPhotos();if(!list.length)return;toast(`Exporting ${list.length} photos…`);for(const p of list)await exportPhoto(p);toast('Batch export complete')}
async function bitmapCanvasFor(p,max=1600){const image=await decodeImageElement(p.blob),scale=Math.min(1,max/Math.max(image.naturalWidth,image.naturalHeight)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(image.naturalWidth*scale));c.height=Math.max(1,Math.round(image.naturalHeight*scale));c.getContext('2d').drawImage(image,0,0,c.width,c.height);releaseDecodedImage(image);return c}
async function saveDerivedCanvas(c,name){const blob=await new Promise(r=>c.toBlob(r,'image/jpeg',.94));if(!blob)return;const rec={id:uid(),name,type:'image/jpeg',size:blob.size,created:Date.now(),modified:Date.now(),width:c.width,height:c.height,blob,edits:defaultEdits(),adjustmentLayers:[],imageLayers:[],localEdits:[],healOps:[],favorite:false,rating:0,flag:'none',albumIds:[]};await put('photos',rec);await refreshData();return rec}
async function hdrMerge(list){
 const canvases=await Promise.all(list.map(p=>bitmapCanvasFor(p))),w=Math.min(...canvases.map(c=>c.width)),h=Math.min(...canvases.map(c=>c.height));
 const datas=canvases.map(c=>{const t=document.createElement('canvas');t.width=w;t.height=h;const x=t.getContext('2d');x.drawImage(c,0,0,w,h);return x.getImageData(0,0,w,h).data});
 const out=document.createElement('canvas');out.width=w;out.height=h;const x=out.getContext('2d'),od=x.createImageData(w,h);
 for(let i=0;i<od.data.length;i+=4){let rr=0,gg=0,bb=0,ws=0;for(const d of datas){const lum=(d[i]+d[i+1]+d[i+2])/765,wt=.25+.75*(1-Math.min(1,Math.abs(lum-.5)*1.7));rr+=d[i]*wt;gg+=d[i+1]*wt;bb+=d[i+2]*wt;ws+=wt}od.data[i]=rr/ws;od.data[i+1]=gg/ws;od.data[i+2]=bb/ws;od.data[i+3]=255}x.putImageData(od,0,0);return out
}
async function focusStack(list){const cs=await Promise.all(list.map(p=>bitmapCanvasFor(p))),w=Math.min(...cs.map(c=>c.width)),h=Math.min(...cs.map(c=>c.height)),datas=cs.map(c=>{const t=document.createElement('canvas');t.width=w;t.height=h;t.getContext('2d').drawImage(c,0,0,w,h);return t.getContext('2d').getImageData(0,0,w,h).data}),out=document.createElement('canvas');out.width=w;out.height=h;const od=out.getContext('2d').createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const idx=(y*w+x)*4;let best=0,score=-1;for(let k=0;k<datas.length;k++){const d=datas[k],xl=Math.max(0,x-1),xr=Math.min(w-1,x+1),yu=Math.max(0,y-1),yd=Math.min(h-1,y+1),lum=i=>.2126*d[i]+.7152*d[i+1]+.0722*d[i+2],s=Math.abs(lum((y*w+xr)*4)-lum((y*w+xl)*4))+Math.abs(lum((yd*w+x)*4)-lum((yu*w+x)*4));if(s>score){score=s;best=k}}const d=datas[best];od.data[idx]=d[idx];od.data[idx+1]=d[idx+1];od.data[idx+2]=d[idx+2];od.data[idx+3]=255}out.getContext('2d').putImageData(od,0,0);return out}

async function noiseStack(list){const cs=await Promise.all(list.map(p=>bitmapCanvasFor(p))),w=Math.min(...cs.map(c=>c.width)),h=Math.min(...cs.map(c=>c.height)),datas=cs.map(c=>{const t=document.createElement('canvas');t.width=w;t.height=h;t.getContext('2d').drawImage(c,0,0,w,h);return t.getContext('2d').getImageData(0,0,w,h).data}),out=document.createElement('canvas');out.width=w;out.height=h;const merged=DarkRoomEngine.mergeAverage(datas);out.getContext('2d').putImageData(new ImageData(merged,w,h),0,0);return out}
async function panoramaMerge(list){const cs=await Promise.all(list.map(p=>bitmapCanvasFor(p,1200))),targetH=Math.min(900,...cs.map(c=>c.height)),parts=cs.map(c=>({c,w:Math.round(c.width*targetH/c.height)})),overlap=.16,total=Math.round(parts.reduce((n,p)=>n+p.w,0)-parts.slice(1).reduce((n,p)=>n+p.w*overlap,0)),out=document.createElement('canvas');out.width=Math.max(1,total);out.height=targetH;const x=out.getContext('2d');let dx=0;for(let i=0;i<parts.length;i++){const p=parts[i],ov=i?Math.round(p.w*overlap):0;if(i){x.save();const g=x.createLinearGradient(dx-ov,0,dx,0);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(1,'rgba(255,255,255,1)');x.globalCompositeOperation='source-over';x.globalAlpha=.75;x.drawImage(p.c,dx-ov,0,p.w,targetH);x.restore();dx+=p.w-ov}else{x.drawImage(p.c,0,0,p.w,targetH);dx=p.w}}return out}
async function batchCombinePhotos(mode){const list=selectedPhotos();if(list.length<2)return toast('Select at least two photos');toast(`${mode==='hdr'?'HDR merging':mode==='focus'?'Focus stacking':mode==='noise'?'Noise stacking':'Building panorama'} locally…`);try{const canvas=mode==='hdr'?await hdrMerge(list):mode==='focus'?await focusStack(list):mode==='noise'?await noiseStack(list):await panoramaMerge(list),name=`DarkRoom-${mode}-${new Date().toISOString().replace(/[:.]/g,'-')}.jpg`;await saveDerivedCanvas(canvas,name);toast(`${mode==='hdr'?'HDR merge':mode==='focus'?'Focus stack':mode==='noise'?'Noise stack':'Panorama'} created`)}catch(e){console.error(e);toast('Could not combine selected photos')}}
async function updateStorage(){const photoBytes=photos.reduce((n,p)=>n+(p.size||0),0);let q=0,u=0,persisted=false;try{const e=await navigator.storage.estimate();q=e.quota||0;u=e.usage||0;persisted=await navigator.storage.persisted?.()||false}catch{}const pct=q?Math.min(100,u/q*100):0;$('#storageBig').textContent=fmtBytes(photoBytes);$('#photoStorage').textContent=fmtBytes(photoBytes);$('#quotaStorage').textContent=q?fmtBytes(Math.max(0,q-u)):'Browser controlled';$('#storageMode').textContent=persisted?'Persistent local storage':'Browser-managed local storage';$('#usageBar').style.width=pct+'%';$('#sideMeter').style.width=pct+'%';$('#sideStorage').textContent=`${fmtBytes(photoBytes)} stored locally`;$('#donut').style.background=`conic-gradient(#d8d8d8 ${pct*3.6}deg,#2b2b2b 0)`}
function route(r){currentRoute=r;if(selectionMode)setSelectionMode(false);$$('.view').forEach(v=>v.classList.remove('active'));if(r==='home')$('#homeView').classList.add('active');else if(r==='albums')$('#albumsView').classList.add('active');else if(r==='storage')$('#storageView').classList.add('active');else $('#libraryView').classList.add('active');render()}
function bindPhotoImageFallbacks(){
  $$('#photoGrid img, #albumGrid img').forEach(img=>{
    img.onerror=()=>{
      const card=img.closest('[data-photo]');
      const photo=card&&photos.find(p=>p.id===card.dataset.photo);
      if(photo&&!img.dataset.originalFallback){img.dataset.originalFallback='1';img.src=blobUrl(photo,false);return}
      img.classList.add('image-missing');
      card?.classList.add('image-missing');
    };
  });
}
if(typeof MutationObserver!=='undefined')new MutationObserver(bindPhotoImageFallbacks).observe(document.body,{childList:true,subtree:true});
async function batchDelete(){
  const list=selectedPhotos();
  if(!list.length)return;
  if(!confirm(`Remove ${list.length} photo${list.length===1?'':'s'} from DarkRoom? The original files on your device will not be deleted.`))return;
  for(const p of list)await del('photos',p.id);
  selectedPhotoIds.clear();
  selectionMode=false;
  $('#selectPhotosBtn').classList.remove('active');
  await refreshData();
  updateBatchBar();
  toast(`${list.length} photo${list.length===1?'':'s'} removed from DarkRoom`);
}
