function filteredPhotos(){let list=[...photos];if(currentRoute==='favorites')list=list.filter(p=>p.favorite);if(currentRoute==='recent')list=list.filter(p=>Date.now()-p.created<7*864e5);if(currentRoute==='flagged')list=list.filter(p=>p.flag==='picked');if(currentRoute==='album')list=list.filter(p=>p.albumIds?.includes(currentAlbumId));if(activeFilter==='picked')list=list.filter(p=>p.flag==='picked');else if(activeFilter==='rejected')list=list.filter(p=>p.flag==='rejected');else if(/^\d$/.test(activeFilter))list=list.filter(p=>p.rating>=+activeFilter);const q=$('#searchInput').value.trim().toLowerCase();if(q)list=list.filter(p=>`${p.name} ${(p.albumIds||[]).map(id=>albums.find(a=>a.id===id)?.name||'').join(' ')} ${new Date(p.created).toLocaleDateString()} ${p.favorite?'favorite':''} ${p.flag}`.toLowerCase().includes(q));const s=$('#sortSelect').value;list.sort(s==='old'?(a,b)=>a.created-b.created:s==='name'?(a,b)=>a.name.localeCompare(b.name):s==='rating'?(a,b)=>b.rating-a.rating:(a,b)=>b.created-a.created);return list}
function render(){renderPhotos();renderAlbums();renderSidebarAlbums();$('#allCount').textContent=photos.length;$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===currentRoute||(currentRoute==='album'&&b.dataset.route==='albums')))}
function renderPhotos(){const g=$('#photoGrid'),empty=$('#emptyState'),list=filteredPhotos();let title='All Photos',sub='Photos stored on this device.',eyebrow='LIBRARY';if(currentRoute==='recent'){title='Recently Added';sub='Photos imported in the last 7 days.'}if(currentRoute==='favorites'){title='Favorites';sub='Photos you marked as favorites.'}if(currentRoute==='flagged'){title='Picked';sub='Photos flagged as picks.'}if(currentRoute==='album'){const a=albums.find(x=>x.id===currentAlbumId);title=a?.name||'Album';sub=`${list.length} photo${list.length===1?'':'s'} · stored locally`;eyebrow='ALBUM'}$('#viewTitle').textContent=title;$('#viewSubtitle').textContent=sub;$('#viewEyebrow').textContent=eyebrow;$('#albumActions').hidden=currentRoute!=='album';empty.style.display=list.length?'none':'flex';g.style.display=list.length?'grid':'none';g.innerHTML=list.map(p=>`<article class="photo-card ${p.rating||p.favorite||p.flag!=='none'?'has-meta':''}" data-photo="${p.id}"><img src="${blobUrl(p)}" alt="${esc(p.name)}" loading="lazy"><div class="photo-overlay"><span>${p.flag==='picked'?'<b class="flag-picked">⚑</b>':p.flag==='rejected'?'<b class="flag-rejected">⚑</b>':''} ${p.rating?'★'.repeat(p.rating):''}</span><span>${p.favorite?'♥':''}</span></div></article>`).join('');$$('.photo-card').forEach(c=>c.onclick=()=>openEditor(c.dataset.photo));if(innerWidth>760)g.style.gridTemplateColumns=`repeat(${gridMode},minmax(0,1fr))`}
function albumPhotos(id){return photos.filter(p=>p.albumIds?.includes(id))}
function renderAlbums(){const ag=$('#albumGrid');if(!albums.length){ag.innerHTML='<div class="info-card"><b>No albums yet</b><p>Create an album to group photos without duplicating files.</p></div>';return}ag.innerHTML=albums.map(a=>{const ps=albumPhotos(a.id);return `<article class="album-card" data-album="${a.id}"><div class="album-cover">${ps.slice(0,4).map(p=>`<img src="${blobUrl(p)}" alt="">`).join('')||'<div class="album-empty">▱</div>'}</div><h3>${esc(a.name)}</h3><small>${ps.length} photos</small></article>`}).join('');$$('.album-card').forEach(c=>c.onclick=()=>openAlbum(c.dataset.album))}
function renderSidebarAlbums(){const s=$('#sidebarAlbums');s.innerHTML=albums.slice().sort((a,b)=>a.name.localeCompare(b.name)).map(a=>`<button class="sidebar-album ${currentRoute==='album'&&currentAlbumId===a.id?'active':''}" data-side-album="${a.id}">${esc(a.name)}</button>`).join('');$$('[data-side-album]').forEach(b=>b.onclick=()=>openAlbum(b.dataset.sideAlbum))}
function openAlbum(id){currentAlbumId=id;route('album')}
async function updateStorage(){const photoBytes=photos.reduce((n,p)=>n+(p.size||0),0);let q=0,u=0,persisted=false;try{const e=await navigator.storage.estimate();q=e.quota||0;u=e.usage||0;persisted=await navigator.storage.persisted?.()||false}catch{}const pct=q?Math.min(100,u/q*100):0;$('#storageBig').textContent=fmtBytes(photoBytes);$('#photoStorage').textContent=fmtBytes(photoBytes);$('#quotaStorage').textContent=q?fmtBytes(Math.max(0,q-u)):'Browser controlled';$('#storageMode').textContent=persisted?'Persistent local storage':'Browser-managed local storage';$('#usageBar').style.width=pct+'%';$('#sideMeter').style.width=pct+'%';$('#sideStorage').textContent=`${fmtBytes(photoBytes)} stored locally`;$('#donut').style.background=`conic-gradient(#d8d8d8 ${pct*3.6}deg,#2b2b2b 0)`}
function route(r){currentRoute=r;$$('.view').forEach(v=>v.classList.remove('active'));if(r==='home')$('#homeView').classList.add('active');else if(r==='albums')$('#albumsView').classList.add('active');else if(r==='storage')$('#storageView').classList.add('active');else $('#libraryView').classList.add('active');render()}
