(function(root){
'use strict';
const EXCLUDED_PRESET_KEYS=new Set(['rotation','angle','flipX','flipY','cropAspect','cropX','cropY','cropZoom','geometryX','geometryY','geometryRotate','geometryScale','geometryVertical','geometryHorizontal','geometryAspect','constrainCrop','expand','superResolution','useAISource','skyReplacementOpacity']);
const IMPORTED_PRESETS=new Set(['Style','Cinematic Grade','Insta Film','Kodachrome 64','Interior Design','Shutter','Fashion Film','Olive & Earth','KDK Colour','Fuji Film']);
const copy=v=>v===undefined?undefined:(typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v)));
const same=(a,b)=>{if(a===b)return true;try{return JSON.stringify(a)===JSON.stringify(b)}catch{return false}};
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
function cleanPresetBaseline(edits={},defaults={}){const next={...copy(defaults)};for(const key of EXCLUDED_PRESET_KEYS)if(key in edits)next[key]=copy(edits[key]);return next}
function removePresetContribution(edits={},state,defaults={}){const next=state?.applied&&state?.base?{...copy(defaults),...copy(edits)}:cleanPresetBaseline(edits,defaults);if(!state?.applied||!state?.base)return next;for(const key of Object.keys(state.applied))if(same(next[key],state.applied[key]))next[key]=copy(state.base[key]);return next}
function applyPresetState(edits={},state,name,preset={},defaults={}){const base=removePresetContribution(edits,state,defaults),applied=copy(preset),next={...base,...applied},storedBase={};for(const key of Object.keys(applied))storedBase[key]=copy(base[key]);return{edits:next,state:{name,base:storedBase,applied}}}
function buildPresetPayload(edits={},defaults={},excluded=EXCLUDED_PRESET_KEYS){const out={};for(const key of Object.keys(defaults)){if(excluded.has(key))continue;if(!same(edits[key],defaults[key]))out[key]=copy(edits[key])}return out}
root.DarkRoomPresetUI={EXCLUDED_PRESET_KEYS,cleanPresetBaseline,removePresetContribution,applyPresetState,buildPresetPayload};
if(typeof document==='undefined')return;
function all(){return typeof allPresets==='function'?allPresets():presets}
function custom(){return typeof customPresets==='function'?customPresets():{}}
function selected(){const name=currentPhoto?.presetSelection?.name;return name&&Object.prototype.hasOwnProperty.call(all(),name)?name:''}
function groups(){const c=custom(),g={DarkRoom:[],"Presetpro Film Pack":[],Saved:[]};for(const name of Object.keys(all())){if(Object.prototype.hasOwnProperty.call(c,name))g.Saved.push(name);else if(IMPORTED_PRESETS.has(name))g['Presetpro Film Pack'].push(name);else g.DarkRoom.push(name)}return g}
function presetMarkupNative(){const value=selected();const opts=Object.entries(groups()).filter(([,names])=>names.length).map(([label,names])=>`<optgroup label="${esc(label)}">${names.map(name=>`<option value="${esc(name)}" ${name===value?'selected':''}>${esc(name)}</option>`).join('')}</optgroup>`).join('');return `<div class="preset-native-wrap"><select id="presetSelect" aria-label="Preset"><option value="" ${value?'':'selected'}>Choose a preset…</option>${opts}</select></div><div class="preset-save"><input id="customPresetName" maxlength="40" placeholder="Preset name" aria-label="Preset name"><button type="button" id="savePresetButton">Save preset</button></div>`}
function applyPreset(name){if(!currentPhoto||!name)return;const preset=all()[name];if(!preset)return;captureHistory();const result=applyPresetState(currentPhoto.edits||{},currentPhoto.presetSelection,name,preset,defaultEdits());currentPhoto.edits=result.edits;currentPhoto.presetSelection=result.state;captureHistory();renderControls();renderCanvas($('#editorCanvas'));debouncedSave();toast(`${name} applied`)}
function savePreset(){if(!currentPhoto)return;const input=$('#customPresetName'),name=input?.value.trim().replace(/\s+/g,' ');if(!name)return toast('Name the preset');const c=custom(),exists=Object.prototype.hasOwnProperty.call(c,name);if(!exists&&Object.prototype.hasOwnProperty.call(presets,name))return toast('That name is used by a built-in preset');if(exists&&!confirm(`Replace saved preset “${name}”?`))return;const defaults=defaultEdits(),payload=buildPresetPayload(currentPhoto.edits||{},defaults);if(!Object.keys(payload).length)return toast('No adjustable edits to save');c[name]=payload;localStorage.setItem('darkroom-user-presets',JSON.stringify(c));const base={};for(const key of Object.keys(payload))base[key]=copy(defaults[key]);currentPhoto.presetSelection={name,base,applied:copy(payload)};debouncedSave();syncBatchPresetOptions?.();renderControls();toast(exists?'Preset replaced':'Preset saved')}
function bindNativePreset(){const select=$('#presetSelect');if(!select)return;select.onchange=e=>{if(e.target.value)applyPreset(e.target.value)};select.onkeydown=e=>{if(e.key!=='ArrowDown'&&e.key!=='ArrowUp')return;e.preventDefault();const options=[...select.options].filter(o=>o.value),current=options.findIndex(o=>o.value===select.value),next=current<0?(e.key==='ArrowDown'?0:options.length-1):(current+(e.key==='ArrowDown'?1:-1)+options.length)%options.length;if(options[next])applyPreset(options[next].value)};const save=$('#savePresetButton'),input=$('#customPresetName');if(save)save.onclick=savePreset;if(input)input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();savePreset()}}}
const style=document.createElement('style');style.id='darkroom-native-preset-style';style.textContent=`#toolTabs .preset-native-wrap{width:100%;min-width:0}#toolTabs #presetSelect{display:block!important;width:100%!important;min-width:0!important;height:38px!important;min-height:38px!important;padding:0 34px 0 10px!important;border:1px solid #3a3a3a!important;border-radius:6px!important;background-color:#202020!important;color:#e8e8e8!important;font-size:12px!important;line-height:38px!important;cursor:pointer!important;pointer-events:auto!important;color-scheme:dark!important}#toolTabs #presetSelect:hover{background-color:#262626!important;border-color:#4a4a4a!important}#toolTabs #presetSelect:focus-visible{outline:2px solid var(--accent,#4ea7ff)!important;outline-offset:2px!important}#toolTabs #presetSelect option,#toolTabs #presetSelect optgroup{background:#1d1d1d!important;color:#f3f3f3!important}`;document.head.appendChild(style);
presetMarkup=presetMarkupNative;
const previousBindGeneratedControls=bindGeneratedControls;
bindGeneratedControls=function(){previousBindGeneratedControls();bindNativePreset()};
batchApplyPreset=async function(name){if(!name)return;const preset=all()[name];if(!preset)return;await batchMutate(photo=>{const result=applyPresetState(photo.edits||{},photo.presetSelection,name,preset,defaultEdits());photo.edits=result.edits;photo.presetSelection=result.state},`${name} applied`)};
})(globalThis);
