(function(root){
'use strict';
const EXCLUDED_PRESET_KEYS=new Set(['rotation','angle','flipX','flipY','cropAspect','cropX','cropY','cropZoom','geometryX','geometryY','geometryRotate','geometryScale','geometryVertical','geometryHorizontal','geometryAspect','constrainCrop','expand','superResolution','useAISource','skyReplacementOpacity']);
const IMPORTED_PRESETS=new Set(['Style','Cinematic Grade','Insta Film','Kodachrome 64','Interior Design','Shutter','Fashion Film','Olive & Earth','KDK Colour','Fuji Film']);
const copy=v=>v===undefined?undefined:(typeof structuredClone==='function'?structuredClone(v):JSON.parse(JSON.stringify(v)));
const same=(a,b)=>{if(a===b)return true;try{return JSON.stringify(a)===JSON.stringify(b)}catch{return false}};
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[ch]));
function cleanPresetBaseline(edits={},defaults={}){const next={...copy(defaults)};for(const key of EXCLUDED_PRESET_KEYS)if(key in edits)next[key]=copy(edits[key]);return next}
function removePresetContribution(edits={},state,defaults={}){const next=state?.applied&&state?.base?{...copy(defaults),...copy(edits)}:cleanPresetBaseline(edits,defaults);if(!state?.applied||!state?.base)return next;for(const key of Object.keys(state.applied))if(same(next[key],state.applied[key]))next[key]=copy(state.base[key]);return next}
function applyPresetState(edits={},state,name,preset={},defaults={}){const base=removePresetContribution(edits,state,defaults),applied=copy(preset),next={...base,...applied},storedBase={};for(const key of Object.keys(applied))storedBase[key]=copy(base[key]);return{edits:next,state:{name,base:storedBase,applied}}}
function buildPresetPayload(edits={},defaults={},excluded=EXCLUDED_PRESET_KEYS){const out={};for(const key of Object.keys(defaults)){if(excluded.has(key))continue;if(!same(edits[key],defaults[key]))out[key]=copy(edits[key])}return out}
root.DarkRoomPresetUI={EXCLUDED_PRESET_KEYS,cleanPresetBaseline,removePresetContribution,applyPresetState,buildPresetPayload};
if(typeof document==='undefined')return;
function all(){return typeof allPresets==='function'?allPresets():presets}
function custom(){return typeof customPresets==='function'?customPresets():{}}
function selected(){const name=currentPhoto?.presetSelection?.name;return name&&Object.prototype.hasOwnProperty.call(all(),name)?name:''}
function names(){return Object.keys(all())}
function groups(){const c=custom(),g={DarkRoom:[],"Presetpro Film Pack":[],Saved:[]};for(const name of names()){if(Object.prototype.hasOwnProperty.call(c,name))g.Saved.push(name);else if(IMPORTED_PRESETS.has(name))g['Presetpro Film Pack'].push(name);else g.DarkRoom.push(name)}return g}
function presetMarkupListbox(){const value=selected(),label=value||'Choose a preset…';const list=Object.entries(groups()).filter(([,items])=>items.length).map(([group,items])=>`<div class="preset-list-group" role="presentation"><div class="preset-list-group-title">${esc(group)}</div>${items.map(name=>`<button type="button" class="preset-list-option${name===value?' selected':''}" role="option" aria-selected="${name===value?'true':'false'}" data-preset-option="${esc(name)}" tabindex="-1">${esc(name)}</button>`).join('')}</div>`).join('');return `<div class="preset-listbox-wrap" data-preset-listbox><button type="button" id="presetListTrigger" class="preset-list-trigger" aria-haspopup="listbox" aria-expanded="false" aria-controls="presetListPopup"><span>${esc(label)}</span><span class="preset-list-caret" aria-hidden="true">⌄</span></button><div id="presetListPopup" class="preset-list-popup" role="listbox" aria-label="Presets" hidden>${list}</div></div><div class="preset-save"><input id="customPresetName" maxlength="40" placeholder="Preset name" aria-label="Preset name"><button type="button" id="savePresetButton">Save preset</button></div>`}
function applyPreset(name){if(!currentPhoto||!name)return;const preset=all()[name];if(!preset)return;captureHistory();const result=applyPresetState(currentPhoto.edits||{},currentPhoto.presetSelection,name,preset,defaultEdits());currentPhoto.edits=result.edits;currentPhoto.presetSelection=result.state;captureHistory();renderControls();renderCanvas($('#editorCanvas'));debouncedSave();toast(`${name} applied`);requestAnimationFrame(()=>$('#presetListTrigger')?.focus())}
function cyclePreset(delta){const list=names();if(!list.length)return;const value=selected(),index=list.indexOf(value),next=index<0?(delta>0?0:list.length-1):(index+delta+list.length)%list.length;applyPreset(list[next])}
function openList(){const trigger=$('#presetListTrigger'),popup=$('#presetListPopup');if(!trigger||!popup)return;popup.hidden=false;trigger.setAttribute('aria-expanded','true');const active=popup.querySelector('[aria-selected="true"]')||popup.querySelector('[data-preset-option]');if(active){active.tabIndex=0;active.focus();active.scrollIntoView({block:'nearest'})}}
function closeList(focusTrigger=false){const trigger=$('#presetListTrigger'),popup=$('#presetListPopup');if(!trigger||!popup)return;popup.hidden=true;trigger.setAttribute('aria-expanded','false');popup.querySelectorAll('[data-preset-option]').forEach(x=>x.tabIndex=-1);if(focusTrigger)trigger.focus()}
function savePreset(){if(!currentPhoto)return;const input=$('#customPresetName'),name=input?.value.trim().replace(/\s+/g,' ');if(!name)return toast('Name the preset');const c=custom(),exists=Object.prototype.hasOwnProperty.call(c,name);if(!exists&&Object.prototype.hasOwnProperty.call(presets,name))return toast('That name is used by a built-in preset');if(exists&&!confirm(`Replace saved preset “${name}”?`))return;const defaults=defaultEdits(),payload=buildPresetPayload(currentPhoto.edits||{},defaults);if(!Object.keys(payload).length)return toast('No adjustable edits to save');c[name]=payload;localStorage.setItem('darkroom-user-presets',JSON.stringify(c));const base={};for(const key of Object.keys(payload))base[key]=copy(defaults[key]);currentPhoto.presetSelection={name,base,applied:copy(payload)};debouncedSave();syncBatchPresetOptions?.();renderControls();toast(exists?'Preset replaced':'Preset saved')}
function bindPresetListbox(){const trigger=$('#presetListTrigger'),popup=$('#presetListPopup');if(!trigger||!popup)return;
 trigger.onclick=e=>{e.preventDefault();trigger.getAttribute('aria-expanded')==='true'?closeList():openList()};
 trigger.onkeydown=e=>{if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if(trigger.getAttribute('aria-expanded')==='true'){openList()}else cyclePreset(e.key==='ArrowDown'?1:-1);return}if(e.key==='Enter'||e.key===' '){e.preventDefault();trigger.getAttribute('aria-expanded')==='true'?closeList():openList();return}if(e.key==='Escape'){e.preventDefault();closeList();return}if(e.key==='Home'||e.key==='End'){e.preventDefault();const list=names();if(list.length)applyPreset(e.key==='Home'?list[0]:list[list.length-1])}};
 popup.onclick=e=>{const option=e.target.closest?.('[data-preset-option]');if(!option)return;e.preventDefault();applyPreset(option.dataset.presetOption)};
 popup.onkeydown=e=>{const option=e.target.closest?.('[data-preset-option]');if(!option)return;const options=[...popup.querySelectorAll('[data-preset-option]')],index=options.indexOf(option);if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();option.tabIndex=-1;const next=options[(index+(e.key==='ArrowDown'?1:-1)+options.length)%options.length];next.tabIndex=0;next.focus();next.scrollIntoView({block:'nearest'});return}if(e.key==='Home'||e.key==='End'){e.preventDefault();option.tabIndex=-1;const next=e.key==='Home'?options[0]:options[options.length-1];next.tabIndex=0;next.focus();next.scrollIntoView({block:'nearest'});return}if(e.key==='Enter'||e.key===' '){e.preventDefault();applyPreset(option.dataset.presetOption);return}if(e.key==='Escape'){e.preventDefault();closeList(true);return}if(e.key==='Tab')closeList()};
 const save=$('#savePresetButton'),input=$('#customPresetName');if(save)save.onclick=savePreset;if(input)input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();savePreset()}}
}
if(!root.__darkroomPresetOutsideBound){root.__darkroomPresetOutsideBound=true;document.addEventListener('pointerdown',e=>{const wrap=document.querySelector('[data-preset-listbox]');if(wrap&&!wrap.contains(e.target))closeList()},true)}
const style=document.createElement('style');style.id='darkroom-preset-listbox-style';style.textContent=`#toolTabs .preset-listbox-wrap{position:relative;width:100%;min-width:0;z-index:90}#toolTabs .preset-list-trigger{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:10px!important;width:100%!important;min-width:0!important;height:38px!important;padding:0 10px!important;border:1px solid #3a3a3a!important;border-radius:6px!important;background:#202020!important;color:#e8e8e8!important;font-size:12px!important;text-align:left!important;cursor:pointer!important}#toolTabs .preset-list-trigger:hover{background:#262626!important;border-color:#4a4a4a!important}#toolTabs .preset-list-trigger:focus-visible,#toolTabs .preset-list-option:focus-visible{outline:2px solid var(--accent,#4ea7ff)!important;outline-offset:1px!important}#toolTabs .preset-list-trigger>span:first-child{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#toolTabs .preset-list-caret{flex:0 0 auto;color:#999}#toolTabs .preset-list-popup{position:absolute!important;left:0!important;right:0!important;top:calc(100% + 4px)!important;z-index:1000!important;max-height:320px!important;overflow-y:auto!important;padding:4px!important;border:1px solid #444!important;border-radius:6px!important;background:#1b1b1b!important;box-shadow:0 12px 30px rgba(0,0,0,.55)!important}#toolTabs .preset-list-popup[hidden]{display:none!important}#toolTabs .preset-list-group+.preset-list-group{margin-top:4px;padding-top:4px;border-top:1px solid #303030}#toolTabs .preset-list-group-title{padding:6px 8px 4px;color:#777;font-size:9px;font-weight:700;letter-spacing:.08em;text-transform:uppercase;text-align:left}#toolTabs .preset-list-option{display:block!important;width:100%!important;height:30px!important;padding:0 8px!important;border:0!important;border-radius:3px!important;background:transparent!important;color:#d8d8d8!important;font-size:12px!important;text-align:left!important;cursor:pointer!important}#toolTabs .preset-list-option:hover,#toolTabs .preset-list-option:focus{background:#2b2b2b!important;color:#fff!important}#toolTabs .preset-list-option.selected{background:#333!important;color:#fff!important}.tool-section-body:has(.preset-listbox-wrap){overflow:visible!important}`;document.head.appendChild(style);
presetMarkup=presetMarkupListbox;
const previousBindGeneratedControls=bindGeneratedControls;
bindGeneratedControls=function(){previousBindGeneratedControls();bindPresetListbox()};
batchApplyPreset=async function(name){if(!name)return;const preset=all()[name];if(!preset)return;await batchMutate(photo=>{const result=applyPresetState(photo.edits||{},photo.presetSelection,name,preset,defaultEdits());photo.edits=result.edits;photo.presetSelection=result.state},`${name} applied`)};
})(globalThis);
