async function photoPixelsForAnalysis(photo,size=320){const bmp=await createImageBitmap(photoBlob(photo)),scale=Math.min(1,size/Math.max(bmp.width,bmp.height)),w=Math.max(2,Math.round(bmp.width*scale)),h=Math.max(2,Math.round(bmp.height*scale)),c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d',{alpha:false}).drawImage(bmp,0,0,w,h);bmp.close?.();return{data:c.getContext('2d').getImageData(0,0,w,h).data,w,h}}

function perceptualHash(data,w,h){const vals=[];for(let gy=0;gy<8;gy++)for(let gx=0;gx<8;gx++){let sum=0,n=0;const x0=Math.floor(gx*w/8),x1=Math.max(x0+1,Math.floor((gx+1)*w/8)),y0=Math.floor(gy*h/8),y1=Math.max(y0+1,Math.floor((gy+1)*h/8));for(let y=y0;y<y1;y+=Math.max(1,Math.floor((y1-y0)/3)))for(let x=x0;x<x1;x+=Math.max(1,Math.floor((x1-x0)/3))){const i=(y*w+x)*4;sum+=.2126*data[i]+.7152*data[i+1]+.0722*data[i+2];n++}vals.push(sum/Math.max(1,n))}const avg=vals.reduce((a,b)=>a+b,0)/vals.length,bits=vals.map(v=>v>=avg?1:0);let hex='';for(let i=0;i<bits.length;i+=4)hex+=parseInt(bits.slice(i,i+4).join(''),2).toString(16);return hex}
function hashDistance(a='',b=''){if(!a||!b||a.length!==b.length)return 999;let d=0;for(let i=0;i<a.length;i++){let x=parseInt(a[i],16)^parseInt(b[i],16);while(x){d+=x&1;x>>=1}}return d}
async function analyzePhotoQuality(photo){const src=await photoPixelsForAnalysis(photo),q=DarkRoomEngine.qualityMetrics(src.data,src.w,src.h),stats=DarkRoomEngine.analyzePixels(src.data);photo.analysis={...q,mean:stats.mean,contrast:stats.contrast,phash:perceptualHash(src.data,src.w,src.h),analyzedAt:Date.now()};return photo.analysis}
async function batchAnalyze(){const list=selectedPhotos();if(!list.length)return;toast(`Analyzing ${list.length} photos…`);for(const p of list){await analyzePhotoQuality(p);await put('photos',p)}await refreshData();selectedPhotoIds=new Set(list.map(p=>p.id));renderPhotos();updateBatchBar();toast('Quality analysis complete')}
function qualityLabel(p){const a=p.analysis;if(!a)return'Not analyzed';return`Focus ${a.sharpness}/100 · Highlights ${Math.round(a.highlights*100)}% · Shadows ${Math.round(a.shadows*100)}%`}
async function renderPhotoForCompare(photo,canvas){const prev=currentPhoto;currentPhoto=normalizePhoto(photo);try{await renderCanvas(canvas,1600,false)}finally{currentPhoto=prev}}
let compareZoom=1;function applyCompareZoom(){['compareLeft','compareRight'].forEach(id=>{const c=$('#'+id);if(c)c.style.transform=`scale(${compareZoom})`})}function initCompareZoom(){const v=$('#compareView');if(!v||v._zoomBound)return;v._zoomBound=true;v.addEventListener('wheel',e=>{e.preventDefault();compareZoom=Math.max(.5,Math.min(5,compareZoom*(e.deltaY<0?1.12:.89)));applyCompareZoom()},{passive:false});v.ondblclick=()=>{compareZoom=1;applyCompareZoom()}}
async function showCompare(){const list=selectedPhotos();if(list.length!==2)return toast('Select exactly 2 photos to compare');const [a,b]=list;compareZoom=1;initCompareZoom();applyCompareZoom();$('#compareView').classList.remove('hidden');$('#compareMeta').textContent=`${a.name}  vs  ${b.name}`;await renderPhotoForCompare(a,$('#compareLeft'));await renderPhotoForCompare(b,$('#compareRight'));if(!a.analysis)await analyzePhotoQuality(a);if(!b.analysis)await analyzePhotoQuality(b);$('#compareLeftMeta').textContent=`${a.name} · ${qualityLabel(a)}`;$('#compareRightMeta').textContent=`${b.name} · ${qualityLabel(b)}`}
function closeCompare(){$('#compareView').classList.add('hidden')}
function showMergeModal(){if(selectedPhotoIds.size<2)return toast('Select at least 2 photos');$('#mergeBackdrop').classList.remove('hidden')}
async function mergeSourceCanvases(list,max=1800){const bitmaps=await Promise.all(list.map(p=>createImageBitmap(photoBlob(p))));try{const first=bitmaps[0],scale=Math.min(1,max/Math.max(first.width,first.height)),w=Math.max(2,Math.round(first.width*scale)),h=Math.max(2,Math.round(first.height*scale)),buffers=[];for(const bmp of bitmaps){const c=document.createElement('canvas');c.width=w;c.height=h;const x=c.getContext('2d',{alpha:false}),ratio=Math.max(w/bmp.width,h/bmp.height),dw=bmp.width*ratio,dh=bmp.height*ratio;x.drawImage(bmp,(w-dw)/2,(h-dh)/2,dw,dh);buffers.push(x.getImageData(0,0,w,h).data)}return{w,h,buffers}}finally{bitmaps.forEach(b=>b.close?.())}}
async function createDerivedPhoto(canvas,name,sources,kind){const blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('Merge encoding failed')),'image/png'));const rec={id:uid(),name:`${name}.png`,type:'image/png',size:blob.size,created:Date.now(),modified:Date.now(),width:canvas.width,height:canvas.height,blob,originalBlob:null,raw:false,rawMeta:{derivedFrom:sources.map(p=>p.name),mergeType:kind},edits:defaultEdits(),adjustmentLayers:[],lut:null,skyReplacementId:null,localEdits:[],healOps:[],favorite:false,rating:0,flag:'none',albumIds:[]};await put('photos',rec);return rec}
async function mergePanorama(list){const bitmaps=await Promise.all(list.map(p=>createImageBitmap(photoBlob(p))));try{const targetH=Math.min(1600,Math.max(...bitmaps.map(b=>b.height))),scaled=bitmaps.map(b=>({bmp:b,w:Math.round(b.width*targetH/b.height)})),overlap=Math.round(targetH*.12),totalW=scaled.reduce((n,x)=>n+x.w,0)-overlap*(scaled.length-1),c=document.createElement('canvas');c.width=totalW;c.height=targetH;const x=c.getContext('2d',{alpha:false});let dx=0;scaled.forEach((o,i)=>{if(i===0)x.drawImage(o.bmp,dx,0,o.w,targetH);else{const temp=document.createElement('canvas');temp.width=o.w;temp.height=targetH;temp.getContext('2d').drawImage(o.bmp,0,0,o.w,targetH);for(let col=0;col<o.w;col++){x.globalAlpha=col<overlap?col/Math.max(1,overlap):1;x.drawImage(temp,col,0,1,targetH,dx+col,0,1,targetH)}x.globalAlpha=1}dx+=o.w-overlap});return c}finally{bitmaps.forEach(b=>b.close?.())}}
async function mergeSelected(kind){const list=selectedPhotos();if(list.length<2)return;$('#mergeBackdrop').classList.add('hidden');toast(`${kind} merge…`);let c;if(kind==='panorama')c=await mergePanorama(list);else{const {w,h,buffers}=await mergeSourceCanvases(list),merged=kind==='hdr'?DarkRoomEngine.mergeHDR(buffers):kind==='focus'?DarkRoomEngine.mergeFocus(buffers,w,h):DarkRoomEngine.mergeAverage(buffers);c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').putImageData(new ImageData(merged,w,h),0,0)}const label=kind==='hdr'?'HDR':kind==='focus'?'Focus-Stack':kind==='panorama'?'Panorama':'Noise-Stack';await createDerivedPhoto(c,`${label}-${new Date().toISOString().slice(0,10)}`,list,kind);await refreshData();setSelectionMode(false);toast(`${label} created`)}
function showRenameModal(){if(!selectedPhotoIds.size)return;$('#renameBackdrop').classList.remove('hidden');$('#renamePrefix').focus()}
async function batchRename(){const list=selectedPhotos(),prefix=$('#renamePrefix').value.trim()||'DarkRoom',start=Math.max(1,+$('#renameStart').value||1);for(let i=0;i<list.length;i++){const p=list[i],ext=(p.name.match(/\.[^.]+$/)||[''])[0];p.name=`${prefix}-${String(start+i).padStart(3,'0')}${ext}`;await put('photos',p)}$('#renameBackdrop').classList.add('hidden');await refreshData();selectedPhotoIds=new Set(list.map(p=>p.id));renderPhotos();updateBatchBar();toast('Photos renamed')}

async function findSimilarPhotos(){const list=selectedPhotos();if(list.length!==1)return toast('Select one reference photo first');const ref=list[0];if(!ref.analysis?.phash)await analyzePhotoQuality(ref);toast('Finding visually similar photos…');for(const p of photos)if(!p.analysis?.phash){await analyzePhotoQuality(p);await put('photos',p)}const matches=photos.filter(p=>hashDistance(ref.analysis.phash,p.analysis?.phash)<=12);selectedPhotoIds=new Set(matches.map(p=>p.id));for(const p of matches)await put('photos',p);renderPhotos();updateBatchBar();toast(`${matches.length} similar photo${matches.length===1?'':'s'} selected`)}
async function batchMetadata(){const list=selectedPhotos();if(!list.length)return;const keys=prompt('Keywords for selected photos (comma separated)','')?.split(',').map(x=>x.trim()).filter(Boolean);if(!keys)return;const caption=prompt('Caption for selected photos (leave blank to keep existing)','');for(const p of list){p.keywords=[...new Set([...(p.keywords||[]),...keys])].slice(0,100);if(caption?.trim())p.caption=caption.trim();await put('photos',p)}await refreshData();selectedPhotoIds=new Set(list.map(p=>p.id));renderPhotos();updateBatchBar();toast('Local metadata updated')}
