function filterString(e){const bright=100+e.exposure*.55+e.whites*.17+e.shadows*.10-e.blacks*.11+e.highlights*.05;const contrast=100+e.contrast*.65+e.clarity*.22+e.texture*.10+e.dehaze*.28+e.sharpness*.05;const sat=100+e.saturation*.75+e.vibrance*.35+e.dehaze*.09-e.chromatic*.03;const sepia=Math.max(0,e.temp)*.16;const hue=e.tint*.12-Math.max(0,e.temp)*.08;const blur=Math.max(0,e.noise)*.009;return `brightness(${Math.max(10,bright)}%) contrast(${Math.max(10,contrast)}%) saturate(${Math.max(0,sat)}%) sepia(${sepia}%) hue-rotate(${hue}deg) blur(${blur}px)`}
function targetAspect(e,sourceAspect){if(e.cropAspect==='1:1')return 1;if(e.cropAspect==='4:3')return 4/3;if(e.cropAspect==='3:2')return 3/2;if(e.cropAspect==='16:9')return 16/9;if(e.cropAspect==='9:16')return 9/16;return sourceAspect}
async function renderCanvas(canvas,maxSize=1800,forceOriginal=false){if(!currentPhoto)return;const token=canvas.id==='editorCanvas'?++renderToken:null;const bmp=await createImageBitmap(currentPhoto.blob),e=forceOriginal?defaultEdits():currentPhoto.edits;const baseRot=((e.rotation||0)%360+360)%360,swap=baseRot===90||baseRot===270,srcW=swap?bmp.height:bmp.width,srcH=swap?bmp.width:bmp.height;const scale=Math.min(1,maxSize/Math.max(srcW,srcH));const tw=Math.max(1,Math.round(srcW*scale)),th=Math.max(1,Math.round(srcH*scale));const temp=document.createElement('canvas');temp.width=tw;temp.height=th;const tc=temp.getContext('2d',{alpha:false});tc.fillStyle='#000';tc.fillRect(0,0,tw,th);tc.filter=filterString(e);tc.translate(tw/2,th/2);const straight=(e.angle||0)+(e.geometryRotate||0);tc.rotate((baseRot+straight)*Math.PI/180);const geomScale=(e.geometryScale||100)/100*(1+Math.abs(e.lensCorrection||0)/100*.05);tc.scale((e.flipX?-1:1)*geomScale,(e.flipY?-1:1)*geomScale);tc.transform(1,(e.geometryY||0)/500,(e.geometryX||0)/500,1,0,0);tc.drawImage(bmp,-bmp.width*scale/2,-bmp.height*scale/2,bmp.width*scale,bmp.height*scale);tc.setTransform(1,0,0,1,0,0);tc.filter='none';bmp.close?.();
 if(e.vignette){const s=Math.abs(e.vignette)/100*.75,g=tc.createRadialGradient(tw/2,th/2,Math.min(tw,th)*.22,tw/2,th/2,Math.max(tw,th)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,e.vignette<0?`rgba(0,0,0,${s})`:`rgba(255,255,255,${s*.45})`);tc.fillStyle=g;tc.fillRect(0,0,tw,th)}
 if(e.grain>0){const count=Math.min(120000,Math.round(tw*th*e.grain/100*.018));tc.globalAlpha=Math.min(.15,e.grain/600);for(let i=0;i<count;i++){const v=Math.random()*255|0;tc.fillStyle=`rgb(${v},${v},${v})`;tc.fillRect(Math.random()*tw,Math.random()*th,1,1)}tc.globalAlpha=1}
 const sourceAspect=tw/th,aspect=targetAspect(e,sourceAspect);let cw=tw,ch=th;if(sourceAspect>aspect)cw=Math.round(th*aspect);else ch=Math.round(tw/aspect);const sx=Math.round((tw-cw)/2),sy=Math.round((th-ch)/2);const outScale=Math.min(1,maxSize/Math.max(cw,ch));canvas.width=Math.max(1,Math.round(cw*outScale));canvas.height=Math.max(1,Math.round(ch*outScale));if(token!==null&&token!==renderToken)return;const ctx=canvas.getContext('2d',{alpha:false});ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(temp,sx,sy,cw,ch,0,0,canvas.width,canvas.height)}
function applyTransform(){const w=$('#canvasWrap');w.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
function resetZoom(){zoom=1;panX=panY=0;applyTransform()}
function captureHistory(){if(!currentPhoto)return;const state={edits:clone(currentPhoto.edits),favorite:currentPhoto.favorite,rating:currentPhoto.rating,flag:currentPhoto.flag,albumIds:[...(currentPhoto.albumIds||[])]};if(historyIndex>=0&&JSON.stringify(history[historyIndex])===JSON.stringify(state))return;history=history.slice(0,historyIndex+1);history.push(state);historyIndex=history.length-1;updateHistoryButtons()}
function applyHistoryState(state){if(!state||!currentPhoto)return;currentPhoto.edits=clone(state.edits);currentPhoto.favorite=state.favorite;currentPhoto.rating=state.rating;currentPhoto.flag=state.flag;currentPhoto.albumIds=[...state.albumIds];syncEditorMeta();renderControls();renderCanvas($('#editorCanvas'),1800,beforeMode);debouncedSave()}
function undo(){if(historyIndex<=0)return;historyIndex--;applyHistoryState(history[historyIndex]);updateHistoryButtons()}
function redo(){if(historyIndex>=history.length-1)return;historyIndex++;applyHistoryState(history[historyIndex]);updateHistoryButtons()}
function updateHistoryButtons(){$('#undoBtn').disabled=historyIndex<=0;$('#redoBtn').disabled=historyIndex>=history.length-1}
async function openEditor(id){currentPhoto=photos.find(p=>p.id===id);if(!currentPhoto)return;currentPhoto.edits={...defaultEdits(),...(currentPhoto.edits||{})};currentPhoto.albumIds=currentPhoto.albumIds||[];currentPhoto.flag=currentPhoto.flag||'none';$('#editor').classList.remove('hidden');$('#editor').setAttribute('aria-hidden','false');currentPanel='light';beforeMode=false;history=[];historyIndex=-1;captureHistory();resetZoom();syncEditorMeta();renderControls();await renderCanvas($('#editorCanvas'))}
