function targetAspect(e,sourceAspect){if(e.cropAspect==='1:1')return 1;if(e.cropAspect==='4:3')return 4/3;if(e.cropAspect==='3:2')return 3/2;if(e.cropAspect==='16:9')return 16/9;if(e.cropAspect==='9:16')return 9/16;return sourceAspect}
function imageDimensions(image){return {width:image?.width||image?.naturalWidth||0,height:image?.height||image?.naturalHeight||0}}
function transformedSourceCanvas(bmp,e,maxSize){const {width,height}=imageDimensions(bmp);if(!width||!height)throw new Error('Decoded image has no dimensions');const baseRot=((e.rotation||0)%360+360)%360,swap=baseRot===90||baseRot===270,srcW=swap?height:width,srcH=swap?width:height,scale=Math.min(1,maxSize/Math.max(srcW,srcH)),tw=Math.max(1,Math.round(srcW*scale)),th=Math.max(1,Math.round(srcH*scale)),temp=document.createElement('canvas');temp.width=tw;temp.height=th;const tc=temp.getContext('2d',{alpha:false});tc.fillStyle='#000';tc.fillRect(0,0,tw,th);tc.translate(tw/2,th/2);const straight=(e.angle||0)+(e.geometryRotate||0);tc.rotate((baseRot+straight)*Math.PI/180);const geomScale=(e.geometryScale||100)/100*(1+Math.abs(e.lensCorrection||0)/100*.05);tc.scale((e.flipX?-1:1)*geomScale,(e.flipY?-1:1)*geomScale);tc.transform(1,(e.geometryY||0)/500,(e.geometryX||0)/500,1,0,0);tc.drawImage(bmp,-width*scale/2,-height*scale/2,width*scale,height*scale);tc.setTransform(1,0,0,1,0,0);return temp}
function cropCanvas(temp,e,maxSize){const sourceAspect=temp.width/temp.height,aspect=targetAspect(e,sourceAspect);let cw=temp.width,ch=temp.height;if(sourceAspect>aspect)cw=temp.height*aspect;else ch=temp.width/aspect;const zoom=Math.max(1,Math.min(4,(e.cropZoom||100)/100));cw=Math.max(1,cw/zoom);ch=Math.max(1,ch/zoom);const fx=Math.max(0,Math.min(1,(e.cropX??50)/100)),fy=Math.max(0,Math.min(1,(e.cropY??50)/100)),sx=Math.max(0,Math.min(temp.width-cw,fx*temp.width-cw/2)),sy=Math.max(0,Math.min(temp.height-ch,fy*temp.height-ch/2)),outScale=Math.min(1,maxSize/Math.max(cw,ch)),out=document.createElement('canvas');out.width=Math.max(1,Math.round(cw*outScale));out.height=Math.max(1,Math.round(ch*outScale));out.getContext('2d',{alpha:false}).drawImage(temp,sx,sy,cw,ch,0,0,out.width,out.height);return out}
function expandCanvas(source,amount){if(!amount)return source;const pad=Math.round(Math.min(source.width,source.height)*Math.min(.35,amount/100*.35)),out=document.createElement('canvas');out.width=source.width+pad*2;out.height=source.height+pad*2;const x=out.getContext('2d',{alpha:false});x.fillStyle='#111';x.fillRect(0,0,out.width,out.height);x.save();x.filter=`blur(${Math.max(5,pad/4)}px)`;x.drawImage(source,-pad,-pad,out.width+pad*2,out.height+pad*2);x.restore();x.drawImage(source,pad,pad);return out}

async function decodeImage(blob){if(!blob)throw new Error('Photo data is unavailable');const url=URL.createObjectURL(blob);try{const image=await new Promise((resolve,reject)=>{const img=new Image();img.decoding='async';img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Browser could not decode this image'));img.src=url});if(!image.naturalWidth||!image.naturalHeight)throw new Error('Decoded image has no pixels');image.__darkroomObjectUrl=url;return image}catch(imageError){URL.revokeObjectURL(url);try{return await createImageBitmap(blob)}catch{throw imageError}}}
let renderFallbackNoticeFor=null;
async function decodePhotoImage(blob){try{return await decodeImage(blob)}catch(primaryError){const fallback=currentPhoto?.thumbnailBlob;if(!fallback||fallback===blob)throw primaryError;try{const image=await decodeImage(fallback);if(renderFallbackNoticeFor!==currentPhoto?.id){renderFallbackNoticeFor=currentPhoto?.id;toast('Original preview unavailable — using the local thumbnail')}return image}catch{throw primaryError}}}
function releaseImage(image){image?.close?.();if(image?.__darkroomObjectUrl)URL.revokeObjectURL(image.__darkroomObjectUrl)}
function setEditorFallback(active){const stage=$('#photoViewport'),img=$('#editorFallbackImage');if(!stage||!img)return;stage.classList.toggle('preview-fallback',!!active);if(!active||!currentPhoto?.blob){img.classList.remove('active');img.removeAttribute('src');img.dataset.photoId='';return}img.classList.add('active');if(img.dataset.photoId===currentPhoto.id)return;const photoId=currentPhoto.id;img.dataset.photoId=photoId;img.dataset.source='original';img.onerror=()=>{if(img.dataset.photoId!==photoId)return;if(img.dataset.source==='thumbnail'||!currentPhoto?.thumbnailBlob)return;img.dataset.source='thumbnail';img.src=blobUrl(currentPhoto,true)};img.src=blobUrl(currentPhoto,false)}
async function applySkyReplacement(source,e){if(!currentPhoto?.skyReplacementId)return source;const ref=photos.find(p=>p.id===currentPhoto.skyReplacementId);if(!ref)return source;const bmp=await decodeImage(ref.blob),sky=document.createElement('canvas');sky.width=source.width;sky.height=source.height;const sx=sky.getContext('2d',{alpha:false}),scale=Math.max(source.width/bmp.width,source.height/bmp.height),dw=bmp.width*scale,dh=bmp.height*scale;sx.drawImage(bmp,(source.width-dw)/2,(source.height-dh)/2,dw,dh);releaseImage(bmp);const ctx=source.getContext('2d',{alpha:false}),base=ctx.getImageData(0,0,source.width,source.height),sd=sx.getImageData(0,0,sky.width,sky.height).data,mask=DarkRoomEngine.smartMaskRaster(base.data,source.width,source.height,'sky'),opacity=DarkRoomEngine.clamp((e.skyReplacementOpacity??100)/100);for(let i=0;i<base.data.length;i+=4){const m=(mask.data[i/4]||0)/255*opacity;base.data[i]=DarkRoomEngine.mix(base.data[i],sd[i],m);base.data[i+1]=DarkRoomEngine.mix(base.data[i+1],sd[i+1],m);base.data[i+2]=DarkRoomEngine.mix(base.data[i+2],sd[i+2],m)}ctx.putImageData(base,0,0);return source}


async function applyImageLayers(source,layers=[]){const active=layers.filter(l=>l&&l.enabled!==false&&l.sourcePhotoId);if(!active.length)return source;const ctx=source.getContext('2d',{alpha:false}),blendMap={normal:'source-over',multiply:'multiply',screen:'screen',overlay:'overlay',softlight:'soft-light'};for(const layer of active){const ref=photos.find(p=>p.id===layer.sourcePhotoId);if(!ref?.blob)continue;try{const bmp=await createImageBitmap(ref.blob),fit=Math.min(source.width/bmp.width,source.height/bmp.height)*(Math.max(.1,layer.scale??100)/100),dw=bmp.width*fit,dh=bmp.height*fit;ctx.save();ctx.globalAlpha=DarkRoomEngine.clamp(layer.opacity??1);ctx.globalCompositeOperation=blendMap[layer.blend]||'source-over';ctx.translate(source.width/2+(layer.x||0)/100*source.width/2,source.height/2+(layer.y||0)/100*source.height/2);ctx.rotate((layer.rotation||0)*Math.PI/180);ctx.drawImage(bmp,-dw/2,-dh/2,dw,dh);ctx.restore();bmp.close?.()}catch(e){console.warn('Image layer render failed',e)}}return source}
function applyGlobalPixels(img,e){const d=img.data,E=DarkRoomEngine;for(let i=0;i<d.length;i+=4){const p=E.applyTonePixel(d[i],d[i+1],d[i+2],e);d[i]=p[0];d[i+1]=p[1];d[i+2]=p[2]}return img}
function applyLensBlur(canvas,e){if(!(e.lensBlur>0))return canvas;const out=document.createElement('canvas');out.width=canvas.width;out.height=canvas.height;const ctx=out.getContext('2d',{alpha:false}),blur=document.createElement('canvas');blur.width=canvas.width;blur.height=canvas.height;const bx=blur.getContext('2d',{alpha:false});bx.filter=`blur(${Math.max(1,e.lensBlur/8)}px)`;bx.drawImage(canvas,0,0);ctx.drawImage(blur,0,0);if(e.bokehHighlights>0){const glow=document.createElement('canvas');glow.width=canvas.width;glow.height=canvas.height;const gx=glow.getContext('2d');gx.filter=`brightness(${135+e.bokehHighlights*.7}%) contrast(${110+e.bokehHighlights*.45}%) blur(${Math.max(1,e.lensBlur/12)}px)`;gx.globalAlpha=Math.min(.38,e.bokehHighlights/180);gx.drawImage(canvas,0,0);gx.globalCompositeOperation='screen';ctx.globalAlpha=.5;ctx.drawImage(glow,0,0);ctx.globalAlpha=1}const mask=document.createElement('canvas');mask.width=canvas.width;mask.height=canvas.height;const mx=mask.getContext('2d'),focus=(e.focusDepth||50)/100,range=Math.max(.03,(e.focusRange||35)/100),depth=currentPhoto?.depthRaster;if(depth?.data){const img=mx.createImageData(mask.width,mask.height);for(let y=0;y<mask.height;y++)for(let x=0;x<mask.width;x++){const dx=Math.min(depth.w-1,Math.round(x/Math.max(1,mask.width-1)*(depth.w-1))),dy=Math.min(depth.h-1,Math.round(y/Math.max(1,mask.height-1)*(depth.h-1))),d=(depth.data[dy*depth.w+dx]||0)/255,v=DarkRoomEngine.clamp(1-Math.abs(d-focus)/range),i=(y*mask.width+x)*4;img.data[i]=img.data[i+1]=img.data[i+2]=255;img.data[i+3]=Math.round(v*255)}mx.putImageData(img,0,0)}else{const cy=canvas.height*focus,band=Math.max(15,canvas.height*range*.55),g=mx.createLinearGradient(0,cy-band,0,cy+band);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(.35,'rgba(0,0,0,1)');g.addColorStop(.65,'rgba(0,0,0,1)');g.addColorStop(1,'rgba(0,0,0,0)');mx.fillStyle=g;mx.fillRect(0,0,mask.width,mask.height)}const sharp=document.createElement('canvas');sharp.width=canvas.width;sharp.height=canvas.height;const sx=sharp.getContext('2d');sx.drawImage(canvas,0,0);sx.globalCompositeOperation='destination-in';sx.drawImage(mask,0,0);ctx.drawImage(sharp,0,0);return out}
function applyCanvasEffects(canvas,e){const ctx=canvas.getContext('2d',{alpha:false}),w=canvas.width,h=canvas.height;if(e.bloom>0||e.halation>0){const glow=document.createElement('canvas');glow.width=w;glow.height=h;const gx=glow.getContext('2d');gx.filter=`blur(${2+Math.max(e.bloom,e.halation)/10}px) brightness(${110+e.bloom/2}%)`;gx.globalAlpha=Math.min(.35,(e.bloom+e.halation)/300);gx.drawImage(canvas,0,0);gx.globalCompositeOperation='screen';ctx.globalAlpha=.55;ctx.drawImage(glow,0,0);ctx.globalAlpha=1}if(e.vignette){const s=Math.abs(e.vignette)/100*.75,g=ctx.createRadialGradient(w/2,h/2,Math.min(w,h)*.22,w/2,h/2,Math.max(w,h)*.72);g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,e.vignette<0?`rgba(0,0,0,${s})`:`rgba(255,255,255,${s*.45})`);ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}if(e.grain>0){const count=Math.min(120000,Math.round(w*h*e.grain/100*.018));ctx.globalAlpha=Math.min(.15,e.grain/600);for(let i=0;i<count;i++){const v=Math.random()*255|0;ctx.fillStyle=`rgb(${v},${v},${v})`;ctx.fillRect(Math.random()*w,Math.random()*h,1,1)}ctx.globalAlpha=1}return canvas}
async function renderCanvasNow(canvas,maxSize=1400,forceOriginal=false){if(!currentPhoto)return;const token=canvas.id==='editorCanvas'?++renderToken:null,E=DarkRoomEngine,e=forceOriginal?defaultEdits():currentPhoto.edits,sourceBlob=!forceOriginal&&e.useAISource&&currentPhoto.aiSourceBlob?currentPhoto.aiSourceBlob:currentPhoto.blob,bmp=await decodePhotoImage(sourceBlob);let temp=transformedSourceCanvas(bmp,e,maxSize);releaseImage(bmp);temp=cropCanvas(temp,e,maxSize);if(!forceOriginal&&e.expand)temp=expandCanvas(temp,e.expand);if(!forceOriginal&&currentPhoto.skyReplacementId)temp=await applySkyReplacement(temp,e);let ctx=temp.getContext('2d',{alpha:false}),img=ctx.getImageData(0,0,temp.width,temp.height);if(!forceOriginal){img=applyGlobalPixels(img,e);let pixels=new Uint8ClampedArray(img.data);if(currentPhoto.lut)pixels=E.applyLUT(pixels,currentPhoto.lut,(e.lutIntensity??100)/100);pixels=E.applyAdjustmentLayers(pixels,temp.width,temp.height,currentPhoto.adjustmentLayers||[]);pixels=E.portraitProcess(pixels,temp.width,temp.height,e);pixels=E.frequencyProcess(pixels,temp.width,temp.height,e.frequencySmooth||0,e.frequencyDetail||0);pixels=E.redEyeProcess(pixels,temp.width,temp.height,e.redEye||0);pixels=E.detailProcess(pixels,temp.width,temp.height,e.noise||0,e.sharpness||0,e);pixels=E.restoreProcess(pixels,temp.width,temp.height,e);pixels=E.relightProcess(pixels,temp.width,temp.height,e,currentPhoto.depthRaster);for(const op of currentPhoto.healOps||[])if(op.enabled!==false&&!op.aiApplied){if(op.method==='clone'||op.mode==='clone')pixels=E.clonePaint(pixels,temp.width,temp.height,op,op.sourceDx??-.12,op.sourceDy??-.12);else if(op.method==='generative'||op.mode==='generative')pixels=E.generativeFill(pixels,temp.width,temp.height,op,op.prompt||'');else pixels=E.inpaint(pixels,temp.width,temp.height,op)}pixels=E.applyLocalEdits(pixels,temp.width,temp.height,currentPhoto.localEdits||[]);img.data.set(pixels);ctx.putImageData(img,0,0);temp=await applyImageLayers(temp,currentPhoto.imageLayers||[]);temp=applyLensBlur(temp,e);applyCanvasEffects(temp,e)}const sr=!forceOriginal?Math.max(1,Math.min(4,+e.superResolution||1)):1,outW=Math.max(1,Math.round(temp.width*sr)),outH=Math.max(1,Math.round(temp.height*sr));if(token!==null&&token!==renderToken)return;canvas.width=outW;canvas.height=outH;const out=canvas.getContext('2d',{alpha:false});out.imageSmoothingEnabled=true;out.imageSmoothingQuality='high';out.drawImage(temp,0,0,outW,outH);if(canvas.id==='editorCanvas'){drawHistogram(canvas);renderMaskOverlay();renderDiagnosticOverlay();updateCompositionOverlay();if(beforeSplit)updateBeforeSplit()}}
let editorRenderQueue=Promise.resolve(),editorRenderRequest=0;
function renderCanvas(canvas,maxSize=1400,forceOriginal=false){
  if(canvas?.id!=='editorCanvas')return renderCanvasNow(canvas,maxSize,forceOriginal);
  const request=++editorRenderRequest;
  const task=editorRenderQueue.then(async()=>{if(request!==editorRenderRequest)return;await renderCanvasNow(canvas,maxSize,forceOriginal)});
  editorRenderQueue=task.catch(error=>{console.error('Queued render failed',error)});
  return task.then(async()=>{if(request!==editorRenderRequest)await editorRenderQueue});
}
function drawHistogramLegacy(canvas){const hc=$('#histogramCanvas');if(!hc||!canvas.width)return;hc.width=150;hc.height=30;const tmp=document.createElement('canvas');tmp.width=Math.min(256,canvas.width);tmp.height=Math.max(1,Math.round(canvas.height*tmp.width/canvas.width));tmp.getContext('2d').drawImage(canvas,0,0,tmp.width,tmp.height);const data=tmp.getContext('2d').getImageData(0,0,tmp.width,tmp.height).data,h=DarkRoomEngine.histogram(data,48),max=Math.max(...h.r,...h.g,...h.b,...h.l,1),x=hc.getContext('2d');x.clearRect(0,0,hc.width,hc.height);const plot=(arr,stroke,alpha=.7)=>{x.beginPath();x.moveTo(0,hc.height);arr.forEach((v,i)=>x.lineTo(i/(arr.length-1)*hc.width,hc.height-v/max*hc.height));x.strokeStyle=stroke;x.globalAlpha=alpha;x.stroke()};plot(h.r,'#ff7373',.65);plot(h.g,'#7ee787',.65);plot(h.b,'#79a8ff',.65);plot(h.l,'#e6e6e6',.8);x.globalAlpha=1}
function drawHistogram(canvas){const hc=$('#histogramCanvas');if(!hc||!canvas.width)return;hc.width=220;hc.height=76;const tmp=document.createElement('canvas');tmp.width=Math.min(420,canvas.width);tmp.height=Math.max(1,Math.round(canvas.height*tmp.width/canvas.width));const tc=tmp.getContext('2d');tc.drawImage(canvas,0,0,tmp.width,tmp.height);const h=DarkRoomEngine.histogram(tc.getImageData(0,0,tmp.width,tmp.height).data,64),max=Math.max(...h.r,...h.g,...h.b,1),x=hc.getContext('2d');x.clearRect(0,0,hc.width,hc.height);x.fillStyle='#0f0f10';x.fillRect(0,0,hc.width,hc.height);x.strokeStyle='#292929';x.lineWidth=1;for(let i=1;i<4;i++){const y=i/4*hc.height;x.beginPath();x.moveTo(0,y);x.lineTo(hc.width,y);x.stroke()}for(const [arr,color] of [[h.r,'#ef5350'],[h.g,'#66bb6a'],[h.b,'#42a5f5']]){x.beginPath();x.moveTo(0,hc.height);arr.forEach((v,i)=>x.lineTo(i/(arr.length-1)*hc.width,hc.height-v/max*(hc.height-4)));x.lineTo(hc.width,hc.height);x.closePath();x.fillStyle=color;x.globalAlpha=.45;x.fill()}x.globalAlpha=1;x.strokeStyle='#f2f2f2';x.lineWidth=1.4;x.beginPath();const lmax=Math.max(...h.l,1);h.l.forEach((v,i)=>{const q=i/(h.l.length-1)*hc.width,y=hc.height-v/lmax*(hc.height-4);i?x.lineTo(q,y):x.moveTo(q,y)});x.stroke();const total=Math.max(1,h.l.reduce((a,v)=>a+v,0)),sh=h.l.slice(0,3).reduce((a,v)=>a+v,0)/total*100,hi=h.l.slice(-3).reduce((a,v)=>a+v,0)/total*100,readout=$('#histogramReadout');if(readout){const cells=readout.querySelectorAll('span');if(cells[0])cells[0].textContent=`Shadows ${sh.toFixed(1)}%`;if(cells[1])cells[1].textContent=`Range ${Math.min(...h.l)}–${Math.max(...h.l)}`;if(cells[2])cells[2].textContent=`Highlights ${hi.toFixed(1)}%`}}

function renderDiagnosticOverlay(){const overlay=$('#diagnosticOverlay'),base=$('#editorCanvas');if(!overlay||!base?.width)return;overlay.width=base.width;overlay.height=base.height;const x=overlay.getContext('2d'),mode=diagnosticOverlay||'none';x.clearRect(0,0,overlay.width,overlay.height);if(mode==='none'||photoOnly)return;const w=Math.min(420,base.width),h=Math.max(2,Math.round(base.height*w/base.width)),c=document.createElement('canvas');c.width=w;c.height=h;const cx=c.getContext('2d');cx.drawImage(base,0,0,w,h);const src=cx.getImageData(0,0,w,h).data,img=cx.createImageData(w,h),lum=(xx,yy)=>{const i=(yy*w+xx)*4;return .2126*src[i]+.7152*src[i+1]+.0722*src[i+2]};for(let yy=1;yy<h-1;yy++)for(let xx=1;xx<w-1;xx++){const i=(yy*w+xx)*4,l=lum(xx,yy);let a=0,r=0,g=0,b=0;if(mode==='highlights'&&l>248){r=255;g=55;b=55;a=175}else if(mode==='shadows'&&l<7){r=55;g=105;b=255;a=175}else if(mode==='focus'){const gx=Math.abs(lum(xx+1,yy)-lum(xx-1,yy)),gy=Math.abs(lum(xx,yy+1)-lum(xx,yy-1)),edge=gx+gy;if(edge>62){r=70;g=255;b=130;a=Math.min(220,80+edge)}}img.data[i]=r;img.data[i+1]=g;img.data[i+2]=b;img.data[i+3]=a}cx.putImageData(img,0,0);x.drawImage(c,0,0,overlay.width,overlay.height)}

function renderMaskOverlay(){const overlay=$('#maskOverlay'),base=$('#editorCanvas');if(!overlay||!base||!base.width)return;overlay.width=base.width;overlay.height=base.height;const x=overlay.getContext('2d'),mask=(currentPhoto?.localEdits||[]).find(m=>m.id===activeLocalId);x.clearRect(0,0,overlay.width,overlay.height);if(!mask||beforeMode||photoOnly)return;const w=Math.min(360,overlay.width),h=Math.max(1,Math.round(overlay.height*w/overlay.width)),small=document.createElement('canvas');small.width=w;small.height=h;const s=small.getContext('2d');s.drawImage(base,0,0,w,h);const src=s.getImageData(0,0,w,h).data,img=s.createImageData(w,h),palette={red:[235,65,90],green:[65,220,115],blue:[65,145,240],white:[240,240,240]},col=palette[localStorage.getItem('darkroom-mask-color')||'red']||palette.red;for(let yy=0;yy<h;yy++)for(let xx=0;xx<w;xx++){const i=(yy*w+xx)*4,r=src[i],g=src[i+1],b=src[i+2],l=(.2126*r+.7152*g+.0722*b)/255,v=DarkRoomEngine.maskValue(mask,xx/Math.max(1,w-1),yy/Math.max(1,h-1),r,g,b,l);img.data[i]=col[0];img.data[i+1]=col[1];img.data[i+2]=col[2];img.data[i+3]=Math.round(v*125)}s.putImageData(img,0,0);x.drawImage(small,0,0,overlay.width,overlay.height)}
function drawMaskOverlay(){renderMaskOverlay()}
function updateCompositionOverlay(){const o=$('#compositionOverlay');if(!o)return;o.className='composition-overlay '+(compositionOverlay||'none')}
function applyTransform(){const w=$('#canvasWrap');w.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
async function updateBeforeSplit(){const c=$('#beforeSplitCanvas'),range=$('#beforeSplitRange'),divider=$('#beforeSplitDivider');if(!c||!range||!divider)return;if(!beforeSplit||!currentPhoto){c.classList.remove('active');range.classList.add('hidden');divider.classList.add('hidden');return}const tmp=document.createElement('canvas');await renderCanvas(tmp,1400,true);const base=$('#editorCanvas');c.width=base.width;c.height=base.height;const x=c.getContext('2d',{alpha:false});x.drawImage(tmp,0,0,c.width,c.height);c.classList.add('active');range.classList.remove('hidden');divider.classList.remove('hidden');applyBeforeSplitClip()}
function applyBeforeSplitClip(){const c=$('#beforeSplitCanvas'),d=$('#beforeSplitDivider');if(!c||!d)return;const p=Math.max(5,Math.min(95,beforeSplitPct));c.style.clipPath=`inset(0 ${100-p}% 0 0)`;d.style.left=p+'%'}
function resetZoom(){zoom=1;panX=panY=0;applyTransform()}
function captureHistory(){if(!currentPhoto)return;const state={edits:clone(currentPhoto.edits),adjustmentLayers:clone(currentPhoto.adjustmentLayers||[]),imageLayers:clone(currentPhoto.imageLayers||[]),lut:clone(currentPhoto.lut||null),skyReplacementId:currentPhoto.skyReplacementId||null,localEdits:clone(currentPhoto.localEdits||[]),healOps:clone(currentPhoto.healOps||[]),depthRaster:clone(currentPhoto.depthRaster||null),favorite:currentPhoto.favorite,rating:currentPhoto.rating,flag:currentPhoto.flag,albumIds:[...(currentPhoto.albumIds||[])]};if(historyIndex>=0&&JSON.stringify(history[historyIndex])===JSON.stringify(state))return;history=history.slice(0,historyIndex+1);history.push(state);if(history.length>80)history.shift();historyIndex=history.length-1;updateHistoryButtons()}
function applyHistoryState(state){if(!state||!currentPhoto)return;currentPhoto.edits=clone(state.edits);currentPhoto.adjustmentLayers=clone(state.adjustmentLayers||[]);currentPhoto.imageLayers=clone(state.imageLayers||[]);currentPhoto.lut=clone(state.lut||null);currentPhoto.skyReplacementId=state.skyReplacementId||null;currentPhoto.localEdits=clone(state.localEdits||[]);currentPhoto.healOps=clone(state.healOps||[]);currentPhoto.depthRaster=clone(state.depthRaster||null);currentPhoto.favorite=state.favorite;currentPhoto.rating=state.rating;currentPhoto.flag=state.flag;currentPhoto.albumIds=[...state.albumIds];syncEditorMeta();renderControls();renderCanvas($('#editorCanvas'),1400,beforeMode);debouncedSave()}
function undo(){if(historyIndex<=0)return;historyIndex--;applyHistoryState(history[historyIndex]);updateHistoryButtons()}
function redo(){if(historyIndex>=history.length-1)return;historyIndex++;applyHistoryState(history[historyIndex]);updateHistoryButtons()}
function updateHistoryButtons(){$('#undoBtn').disabled=historyIndex<=0;$('#redoBtn').disabled=historyIndex>=history.length-1}
async function openEditor(id){currentPhoto=normalizePhoto(photos.find(p=>p.id===id));if(!currentPhoto)return;$('#editor').classList.remove('hidden','focus-view');$('#editor').setAttribute('aria-hidden','false');photoOnly=false;currentPanel='edit';beforeSplit=false;activeLocalId=currentPhoto.localEdits[0]?.id||null;activeLayerId=currentPhoto.adjustmentLayers?.[0]?.id||null;activeImageLayerId=currentPhoto.imageLayers?.[0]?.id||null;paintMode=null;beforeMode=false;history=[];historyIndex=-1;const canvas=$('#editorCanvas');if(canvas){canvas.width=1;canvas.height=1;canvas.getContext('2d',{alpha:false})?.clearRect(0,0,1,1)}setEditorFallback(true);captureHistory();resetZoom();syncEditorMeta();applyEditorMode(false);renderControls();await renderCanvas(canvas);updateCompositionOverlay()}
async function renderThumbnailFallback(canvas,maxSize=1400){const blob=currentPhoto?.thumbnailBlob;if(!blob)return false;try{const bmp=await decodeImage(blob),temp=transformedSourceCanvas(bmp,defaultEdits(),maxSize);releaseImage(bmp);canvas.width=temp.width;canvas.height=temp.height;const out=canvas.getContext('2d',{alpha:false});out.imageSmoothingEnabled=true;out.imageSmoothingQuality='high';out.drawImage(temp,0,0);if(canvas.id==='editorCanvas'){drawHistogram(canvas);renderMaskOverlay();renderDiagnosticOverlay();updateCompositionOverlay()}const sample=out.getImageData(0,0,Math.min(canvas.width,160),Math.min(canvas.height,160)).data;let sum=0;for(let i=0;i<sample.length;i+=4)sum+=sample[i]+sample[i+1]+sample[i+2];return sum>=3*sample.length/4}catch(error){console.warn('Thumbnail fallback failed',error);return false}}
const renderCanvasNowBase=renderCanvasNow;
renderCanvasNow=async function(canvas,maxSize=1400,forceOriginal=false){
  const photoId=currentPhoto?.id;
  try{await renderCanvasNowBase(canvas,maxSize,forceOriginal)}
  catch(error){
    console.error('Render failed',error);
    if(photoId!==currentPhoto?.id)return;
    if(canvas?.id==='editorCanvas'&&await renderThumbnailFallback(canvas,maxSize)){
      setEditorFallback(false);toast('Original preview unavailable — showing the local thumbnail');
    }else if(canvas?.id==='editorCanvas'){
      setEditorFallback(true);toast('Could not decode this image — showing the original preview');
    }
    return;
  }
  if(photoId!==currentPhoto?.id)return;
  if(forceOriginal||canvas?.id!=='editorCanvas'||!canvas.width||!canvas.height){
    if(canvas?.id==='editorCanvas')setEditorFallback(false);
    return;
  }
  const data=canvas.getContext('2d').getImageData(0,0,Math.min(canvas.width,160),Math.min(canvas.height,160)).data;
  let sum=0;for(let i=0;i<data.length;i+=4)sum+=data[i]+data[i+1]+data[i+2];
  if(sum<3*data.length/4){
    const recovered=await renderThumbnailFallback(canvas,maxSize);
    if(recovered){setEditorFallback(false);toast('Preview is empty — showing the local thumbnail');return}
    toast('Preview is empty — showing the untouched photo');
    await renderCanvasNowBase(canvas,maxSize,true);
  }
  setEditorFallback(false);
}
const renderCanvasStatusBase=renderCanvas;renderCanvas=function(canvas,maxSize=1400,forceOriginal=false){const status=$('#renderStatus');const isEditor=canvas?.id==='editorCanvas';if(isEditor&&status){status.classList.remove('hidden');status.textContent='Rendering preview…';canvas.setAttribute('aria-busy','true')}const result=renderCanvasStatusBase(canvas,maxSize,forceOriginal);return Promise.resolve(result).finally(()=>{if(isEditor&&status){status.classList.add('hidden');canvas.removeAttribute('aria-busy')}})};
