import fs from 'node:fs';
import assert from 'node:assert/strict';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const js=fs.readFileSync(new URL('../app.js',import.meta.url),'utf8');
const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8');
const sw=fs.readFileSync(new URL('../sw.js',import.meta.url),'utf8');
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
const direct=[...js.matchAll(/\$\('#([A-Za-z0-9_-]+)'\)/g)].map(m=>m[1]);
for(const id of direct) assert(ids.has(id),`Missing HTML element #${id}`);
for(const id of ['photoViewport','editorCanvas','canvasWrap','zoomIn','zoomOut','zoomReset','zoomLabel','albumActions','renameAlbum','deleteAlbum','storageMode']) assert(ids.has(id),`Missing required #${id}`);
for(const panel of ['light','color','effects','detail','transform','albums','info']) assert(html.includes(`data-panel="${panel}"`),`Missing panel ${panel}`);
for(const key of ['exposure','contrast','highlights','shadows','whites','blacks','temp','tint','vibrance','saturation','texture','clarity','dehaze','vignette','grain','sharpness','noise']) assert(js.includes(`${key}:0`),`Missing default edit ${key}`);
assert(js.includes('renderCanvas(c,4096)'), 'Export must use shared renderer');
assert(js.includes("navigator.storage?.persist?.()"), 'Persistent local storage request missing');
assert(js.includes("currentRoute==='album'"), 'Album route missing');
assert(js.includes('touchmove'), 'Pinch/pan touch support missing');
assert(css.includes('.editor-panel') && css.includes('.editor-stage'), 'Split editor layout missing');
assert(css.includes('grid-template-rows:54px minmax(180px,1fr) 300px'), 'Fixed mobile parameter region missing');
assert(sw.includes('darkroom-v2') && sw.includes('skipWaiting'), 'Service worker upgrade policy missing');
console.log(`DarkRoom smoke checks passed (${direct.length} bound element references verified).`);
