import fs from 'node:fs';
import assert from 'node:assert/strict';
const read=p=>fs.readFileSync(new URL(p,import.meta.url),'utf8');
const html=read('../index.html'),css=read('../styles.css'),sw=read('../sw.js');
const modules=['../core.js','../library.js','../renderer.js','../editor.js','../app.js'];
const js=modules.map(read).join('\n');
const ids=new Set([...html.matchAll(/id="([^"]+)"/g)].map(m=>m[1]));
const direct=[...js.matchAll(/\$\('#([A-Za-z0-9_-]+)'\)/g)].map(m=>m[1]);
for(const id of direct)assert(ids.has(id),`Missing HTML element #${id}`);
for(const id of ['photoViewport','editorCanvas','canvasWrap','zoomIn','zoomOut','zoomReset','zoomLabel','albumActions','renameAlbum','deleteAlbum','storageMode','undoBtn','redoBtn','beforeAfterBtn','pickBtn','rejectBtn','copyEdits','pasteEdits'])assert(ids.has(id),`Missing required #${id}`);
for(const panel of ['presets','light','color','effects','detail','optics','geometry','transform','albums','info'])assert(html.includes(`data-panel="${panel}"`),`Missing panel ${panel}`);
for(const key of ['exposure','contrast','highlights','shadows','whites','blacks','temp','tint','vibrance','saturation','texture','clarity','dehaze','vignette','grain','sharpness','noise','rotation','angle','geometryX','geometryY','geometryRotate','lensCorrection','chromatic'])assert(js.includes(`${key}:0`)||js.includes(`${key}:100`),`Missing default edit ${key}`);
assert(js.includes('renderCanvas(c,4096,false)'), 'Export must use shared renderer');
assert(js.includes('navigator.storage?.persist?.()'), 'Persistent local storage request missing');
assert(js.includes("currentRoute==='album'"), 'Album route missing');
assert(js.includes('touchmove')&&js.includes('pinch'), 'Pinch/pan touch support missing');
assert(js.includes("setFlag('picked')")&&js.includes("setFlag('rejected')"),'Flag controls missing');
assert(js.includes('captureHistory')&&js.includes('function undo()')&&js.includes('function redo()'),'Undo/redo missing');
assert(js.includes('editClipboard'),'Copy/paste edits missing');
assert(css.includes('grid-template-columns:minmax(0,1fr) var(--right)'),'Fixed desktop editor split missing');
assert(css.includes('grid-template-rows:50px minmax(180px,1fr) 300px'),'Fixed mobile parameter region missing');
assert(css.includes('.editor-stage')&&css.includes('.editor-panel'),'Split editor layout missing');
assert(sw.includes('darkroom-v3')&&sw.includes('./core.js')&&sw.includes('./editor.js')&&sw.includes('skipWaiting'),'Service worker modular cache missing');
for(const src of ['core.js','library.js','renderer.js','editor.js','app.js'])assert(html.includes(`<script src="${src}"></script>`),`Missing script ${src}`);
assert(!modules.map(read).some(x=>/fetch\s*\(/.test(x)),'Application runtime should not upload/fetch photo data');
console.log(`Static smoke checks passed (${direct.length} bound element references verified).`);
